### ISSUE TITLE
People List is Incomplete

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#1]
Please add yourself to the list of people in https://github.com/ipfs/community#people if you wish to be listed :)

@whyrusleeping 
@cryptix
@mappum
@briantigerchow
@mildred
@chriscool
@travisperson
@hosh
@tv42
@zignig
@dylanPowers
@dborzov
@cleichner
@luzifer
@ebuchman

And everyone else i forgot!

**Comment by diasdavid** [comment]
Reminder to everyone that hasn't added themselves yet :) 

https://github.com/ipfs/community/pull/72
https://github.com/ipfs/community/pull/71
https://github.com/ipfs/community/pull/48
https://github.com/ipfs/community/pull/3
