### ISSUE TITLE
Lisbon IPFS Sunday Hack Day

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#103]
# Lisbon IPFS s/Sunday/Hack Day/g

![image](https://cloud.githubusercontent.com/assets/1211152/12694801/61e5fc0a-c730-11e5-96d8-bdba15844d21.png)

I'm going to spend this Sunday with @xicombd and @johnytiago hacking on IPFS things :D (mostly the JavaScript parts) from Lisbon. 

**If you are around and interested in joining, come along! :D**

I'll be going through some of the IPFS parts (the ones participants are interested in) and guiding through first good contributions.

We will start around 10am, address is Rua Ramalho Ortigão, n8 3rd floor.

> PS: I wonder if we can convince people to change the name of one of the days of the week to HackDay, instead of Monday,Tuesday, etc :D

**Comment by RichardLitt** [comment]
@diasdavid Add this to the calendar?

**Comment by diasdavid** [comment]
@RichardLitt thank you for reminding me, added :)

**Comment by diasdavid** [comment]
Thank you all that joined the event :D let's do it more!
