### ISSUE TITLE
David Mazieres talk about Stellar Consensus Protocol @ NYU (NYC) Feb 3 11:30am

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#104]
See https://cs.nyu.edu/dynamic/news/colloquium/720/

> **THE STELLAR CONSENSUS PROTOCOL: A FEDERATED MODEL FOR INTERNET-LEVEL CONSENSUS**
>
> **Synopsis:**
>
> This talk will present federated Byzantine agreement (FBA), a generalization of the standard Byzantine agreement problem. Unlike traditional Byzantine agreement--which presupposes unanimous agreement on system membership--the FBA model grants organizations individual control over whom to trust, allowing membership to grow organically out of pairwise relationships between participants. Compared to proof-of-work and proof-of-stake, two other decentralized alternatives to Byzantine agreement, FBA enables far more efficient constructions with greater margins of computational security. The talk will further present the Stellar consensus protocol (SCP), the first FBA protocol. SCP forms the backbone of the Stellar payment network, where it secures financial transactions.  Other potential applications include secure timestamping and strengthening certificate transparency.
>
> **Speaker Bio:**
>
> David Mazières was a faculty member at NYU from from 2000-2007 and currently serves as the Chief Scientist of Stellar Development Foundation, where he conducted the work presented in this talk. Additionally, he is a Professor of Computer Science at Stanford and a co-founder of Intrinsic (formerly GitStar).  Prof. Mazières works on operating systems, distributed systems, and security, but is perhaps best known for co-authoring "Get Me Off Your F------ Mailing List," a novelty paper that in 2014 was accidentally accepted for publication by the International Journal of Advanced Computer Technology (IJACT).

I will be going. if you're in NYC, join :)

**Comment by RichardLitt** [comment]
This looks cool! Post notes!

**Comment by diasdavid** [comment]
Is there a vídeo?

**Comment by se3000** [comment]
From SF BitDevs around the same time: https://www.youtube.com/watch?v=hjRQLYF599w

**Comment by diasdavid** [comment]
thank you @se3000 !:D
