### ISSUE TITLE
2016 Conferences and Meetup Suggestions

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#105]
#### This Issue

If there are conferences or meetups in 2016 you think that the IPFS community should go to, present talks about IPFS at, be aware of, or in general check out, post them here! The goal is to surface events so that we can prepare for them, submit proposals, and do our best to see if someone in the IPFS community can make it.

**Comment by brimstone** [comment]
I'd like to present IPFS at [Hope XI](http://xi.hope.net/). I'm still gathering an outline before I submit to the CFP.

**Comment by chriscool** [comment]
April 4-5: Git Merge 2016 (http://git-merge.com/) in New York City. Git Developer Summit the 4th and Git Merge for everyone else the 5th. I will probably be there, maybe presenting.

**Comment by chriscool** [comment]
June 19-21: DockerCon 2016 (http://2016.dockercon.com/) in Seattle.

**Comment by chriscool** [comment]
August 22-24: LinuxCon North America (http://events.linuxfoundation.org/events/linuxcon-north-america) in Toronto.
