### ISSUE TITLE
PR and Issue templates

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#108]
We now are able [to implement these natively in GitHub](https://github.com/blog/2111-issue-and-pull-request-templates). There are some examples in [this awesome-list](https://github.com/devspace/awesome-github-templates). Do you think we should enable them for, say, go-ipfs?

**Comment by noffle** [comment]
I'm in favour of not racing into additional bureaucracy unless we're sure it's needed. Did you have specific requirements in mind?

**Comment by RichardLitt** [comment]
No. I was wondering if it might help if some of the repos had templates: which ipfs version, etc.

**Comment by whyrusleeping** [comment]
I'd like if we at least had something like:

```
# short issue description

# steps to reproduce

# system information
## operating system:
## ipfs version:
## other info:
```

**Comment by diasdavid** [comment]
What's left here? This was implemented in go-ipfs. Can we close this issue?

**Comment by dignifiedquire** [comment]
Do we want those in js-land as well?

**Comment by RichardLitt** [comment]
That's the question. Do we want it elsewhere?

I'm not sure that there are enough issue-heavy repos to require it. We have it for ipfs/ipfs, too, which works well (thanks @whyrusleeping).
