### ISSUE TITLE
Swag

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#11]
We're designing some ipfs swag (hoodies, stickers, socks, etc).

**Comment by RichardLitt** [comment]
How do I get a hold on one of those hoodies? I saw @jbenet wearing one in a video recently...

**Comment by VictorBjelkholm** [comment]
Oh, count me in to buy one as well! Would be awesome

**Comment by harlantwood** [comment]
Same :smile:

**Comment by nicola** [comment]
same for hoodie here ^^

**Comment by yangwao** [comment]
Count me in!

**Comment by chpio** [comment]
:+1: we need more yolo swag cloud

**Comment by rjrotheryjr** [comment]
Oh Snap... hoodies I'm in !

**Comment by harlantwood** [comment]
where can we order swag?  are we set up on cafepress or similar?

**Comment by RichardLitt** [comment]
@harlantwood @rjrotheryjr We're working on it! Thanks for bumping this, all. Prioritizing stickers first, then other swag. Please drop your addresses to me, or in #50, and we'll send them out soonish.

**Comment by chpio** [comment]
What's the price for the stickers?

**Comment by RichardLitt** [comment]
Free! Want some?

**Comment by RichardLitt** [comment]
Stickers! See #175.

**Comment by asymmetric** [comment]
How are we doing re: swag? :D

**Comment by whyrusleeping** [comment]
We've got a shopify store close to being set up, and are prepping a few things on it. @skylarnorris can probably provide more info

**Comment by skylarnorris** [comment]
@asymmetric hey, yes we are close to launching our swag store -- we just have a few adjustments to make and are awaiting the inventory for the final few items we need.  Anticipate this launch date being the end of the next week.  :)  Let me know if you have any other questions I can answer!

**Comment by llopv** [comment]
@skylarnorris How is the store going? Do you need any help on this?

**Comment by nicola** [comment]
Swag store is out! https://shop.ipfs.io/

**Comment by asymmetric** [comment]
And we can only pay in USD with PayPal? 😢

**Comment by skylarnorris** [comment]
Swag store has been out for awhile, but I don't think it was posted anywhere? Thanks for putting the link out @nicola <3

>And we can only pay in USD with PayPal? 😢

Yes, sadly. :( For now. Hope to add other options in the future!

**Comment by RichardLitt** [comment]
Might be worth adding a link to the README about Swag, instead of keeping this issue open.

**Comment by skylarnorris** [comment]
@RichardLitt how do I add people to this repo?

**Comment by RichardLitt** [comment]
@skylarnorris Go to "Settings". If that isn't an option, ask @lgierth or @diasdavid or someone similar to enable you as an admin for this repo. Then, in "Collaborators", you should be able to add people. 

Feel free to add me back if you need something done. Doesn't take me much effort. :)

**Comment by skylarnorris** [comment]
@lgierth :) Can you add Jamie? I don't have admin access. 

@RichardLitt thanks, always appreciate you!

**Comment by eric-holobyn** [comment]
@skylarnorris How can I grab 2 stickers from the team??

**Comment by skylarnorris** [comment]
@eric-holobyn send me an email with your address and I'll ship some to you: skylar@protocol.ai
