### ISSUE TITLE
Squatconf in Berlin

### ISSUE THREAD

**Issue by ianopolous** [ipfs/community#113]
I believe a bunch of us are going to [Squatconf](http://squatconf.eu/), with some people arriving up to a week early for some other conferences. It would be awesome to coordinate. I'm thinking of going a day or two beforehand.

**Comment by Kubuxu** [comment]
Many people from cjdns community are coming, this includes me and @lgierth, also @dignifiedquire proposed a talk so I think he is coming too.

**Comment by dignifiedquire** [comment]
Yep I will be going.

**Comment by ianopolous** [comment]
How many days before are people arriving? It'd be great to meet up beforehand.

**Comment by haadcode** [comment]
I'll be attending Squatconf.

**Comment by RichardLitt** [comment]
So will @diasdavid and @noffle.

**Comment by lgierth** [comment]
Squatconf never ends, but this issue does.
