### ISSUE TITLE
Boston/MIT Meetup 

### ISSUE THREAD

**Issue by creckhow** [ipfs/community#115]
Hi @jbenet and @RichardLitt here's the first draft of the meetup.com event for the event http://www.meetup.com/Boston-Ethereum-Enthusiasts/events/230202901/ 

Please let me know if I'm ok to post it -- next steps would be to create a more in depth eventbrite page. 

For space -- Nchinda booked an auditorium/room in Stata -- but we could still wait on Nicola for a Media Lab space.

**Comment by creckhow** [comment]
Also we want to think about agenda (date is Wednesday 4/20) 

For a very preliminary agenda I'd propose:

- Juan gives his IPFS into talk & IPLD talk (30 minutes)
- Richard (or someone else from Protocol Labs?) talk slot (15 minutes)
- ConsenSys Ethereum dApp (likely uPort) on IPFS demo slot (15 minutes)
- Questions, food, networking..

@jbenet  -- what's your vision?

**Comment by RichardLitt** [comment]
Sorry, I should have been more on top of this. But I think we settled all of this via email. 

For anyone watching, the eventbrite is here! https://www.eventbrite.com/e/ipfs-ethereum-mit-meetup-tickets-24578852008

**Comment by jbenet** [comment]
Exciting! thanks very much @creckhow and @RichardLitt 

cc @nicola @Stebalien

![](https://ipfs.io/ipfs/QmT7kuXkrpG9TeCdZWfCkE7eqVu5aoje1dDAURmvVSuJ1k/ipfs-meetup-mit.jpg)

**Comment by RichardLitt** [comment]
Done! Thanks everyone!
