### ISSUE TITLE
IPFS Berlin Meetup - May 2nd 2016

### ISSUE THREAD

**Issue by haadcode** [ipfs/community#116]
Hi all,

We're planning on having an IPFS Berlin Meetup around Squatconf. The current dates we're thinking are **Thursday the 28th and Monday the 2nd of May**.

Proposed locations are: C-Base and CoUp. Anyone well-connected to C-Base who could check if they can host us? @bergie @lgierth?

If anyone has suggestions for other places that could host us, let me know.

Follow this thread for more information!

**Comment by bergie** [comment]
I'm not available on 28th, but 2nd would work. 

There seems to be a Sailfish OS meetup in the evening, but we could probably fit IPFS too at c-base https://www.c-base.org/cal/day.php?cal=regular,termine&getdate=20160502

The best way to check that is to get in touch with cultorga.

**Comment by Kubuxu** [comment]
I am in Berlin for 29th to 7th, so Squatconf and following week.

**Comment by haadcode** [comment]
I've emailed C-Base re. 2nd of May. Co.up would be able to host on the 28th (they have room for 75+ ppl). Will give an update as soon as I have more information.

**Comment by haadcode** [comment]
**IPFS Berlin Meetup will happen on Monday the 2nd of May**

We have secured C-Base as the meetup location \o/ More info to follow.

**Comment by jbenet** [comment]
Awesome! 

BTW: sorry, it's looking way less likely that I can make May 2nd :(  i have to be at http://www.coindesk.com/events/consensus-2016/

**Comment by jbenet** [comment]
(feel free to have the meetup without me, plenty of ipfs folks in berlin)

**Comment by haadcode** [comment]
We have finally an official event announcement & registration online, see here: https://www.eventbrite.com/e/ipfs-berlin-meetup-tickets-24998261473

If you're coming, please register as we have limited seats (70). Feel free to spread to word and invite people who might be interested. Hope to see you all there on Monday!

**Comment by haadcode** [comment]
If you'd like to present something and give a (short) talk, please let us know! We currently have the following talks:

Agenda
Introduction to IPFS (10min).
Davis Dias -- IPFS core dev and member of Protocol Labs -- will attempt a short but deep introduction to The IPFS Project. This should give enough context for newcommers to follow the rest of the talks.

Registry Mirror -- NPM on IPFS. (20min)
David Dias -- IPFS core dev and member of Protocol Labs-- will speak about registry-mirror and package management. IPFS is fantastic for package managers, because of its decentralized, secure, and permanent linking. registry-mirror is a node.js module that makes it so you can install npm packages directly from IPFS, peer-to-peer!

Orbit -- Distributed p2p chat on IPFS. (15min)
Samuli Poyhtari -- IPFS core dev and member of Protocol Labs -- will speak about Orbit, a distributed p2p chat on IPFS. Think decentralized Slack or IRC! This talk will demo it, discuss how it works, and its components. And we will discuss how we can build realtime apps on IPFS.

IPFS dead drop -- Publish Files to IPFS from USB stick (15min)
Uwe Kamper -- IPFS contributor and C-Base member -- will talk about IPFS Dead Drop, an anonymous, offline, peer to peer file-sharing network in public space. Located at C-Base, you plug a USB memory into the dead drop device and it will automatically access the memory stick and publish all the files on the web using IPFS. After files have been published, you'll get a shareable link to your files. Uwe will present the project and you can give it a go at meetup premises at C-Base.

**Comment by haadcode** [comment]
We have one more lightning talk for the meetup:

[IPFSDroid ](https://github.com/ligi/IPFSDroid) -- Making IPFS an implementation detail on android for now (5min?)
Markus Ligi. This is a lightning talk to spark conversation about IPFS on Android.

**Comment by haadcode** [comment]
There will be a talk from Ascribe/BigchainDB also (don't have the details yet).

Also, **we'll be live streaming the meetup talks!** Will post links tomorrow before starting the meetup.

**Comment by haadcode** [comment]
This is happening tonight!

It was pointed out to me that the entrance to c-base is "non-standard", so here's a little more details on how to find it:

If you come from S/U-Bahn Jannowitzbrücke, walk across the river and after the bridge, take a left and walk all the way down to the river. There's a narrow sidewalk that takes you further, keep walking. You'll come to the end of it and think "can't get further" but not to worry! Continue towards the trees, walk up towards the little garden and you'll see the building under construction up ahead. Keep walking further, past the building being renovated and you'll finally reach the house c-base is located at (the red building).

We'll try to put up some posters, arrows or stickers along the way.

**Comment by biafra23** [comment]
What time does the Meetup start?

**Comment by haadcode** [comment]
Due to a organizational mishap, we don't have snacks at theeetup. Sorry everyone.

The meetup will start at 1900 (7pm).

**Comment by noffle** [comment]
LIVE(tm) STREAM: https://www.youtube.com/watch?v=UOC_QqtEJtg

**Comment by RichardLitt** [comment]
Thanks everyone! Was great to watch the Livestream. 

Let's do another one. For now, closing this.

**Comment by ligi** [comment]
This was a great meetup! Was especially blown away by the implications of the orbit demo / dynamic apps on IPFS  - great stuff! Also the follow-up was great - I now have a real IPFS node running on android - thought I will stick to mocks/centralized solutions way longer. The future is bright - hope there will be one more IPFS meetup this year in Berlin!
