### ISSUE TITLE
IPFS Paris meetup on April 26

### ISSUE THREAD

**Issue by chriscool** [ipfs/community#118]
As Juan will be in Paris on April 26, maybe we can have a (possibly small) meetup.
Please comment if you are interested.

cc @jbenet @mildred @gorhgorh @cjdelisle @ansuz @lgierth @diasdavid

**Comment by diasdavid** [comment]
I would love too, but can add any more travelling to my schedule. Thank you @chriscool :)

**Comment by lgierth** [comment]
I'll still be in the US by then

**Comment by mildred** [comment]
I'll try to come. That would be very nice. Where / when would that be ?

**Comment by noffle** [comment]
Would've loved to, but I'm flying into Berlin on the 26th.

**Comment by gorhgorh** [comment]
I'll be in berlin as well too close from squatconf for me

2016-04-18 22:31 GMT+02:00 Stephen Whitmore <notifications@github.com>:

**Comment by cjdelisle** [comment]
I'm still in Paris that day, can meet up for dinner after work...

**Comment by mildred** [comment]
So, who can be there?

- jbenet
- chriscool
- mildred
- cjdelisle

There is still a number of people who can't be there. Would another date work better? Early may perhaps?

**Comment by chriscool** [comment]
Yeah, if we can only be 4, it's better to postpone.

**Comment by dignifiedquire** [comment]
I would love to come another time, paris is only 3h by train from my place. But I will be travelling to squatconf as well this week

**Comment by RichardLitt** [comment]
Reopen if there is going to be a new one! :)
