### ISSUE TITLE
Apps using IPFS

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/community#12]
Just some apps I've found around the interwebz that use IPFS. I'll try to keep this list updated in order of activity. Make a comment to be added and I'll comment when I find something. Feel free to subscribe to stay up to date.

* [git-ipfs-rehost](https://github.com/whyrusleeping/git-ipfs-rehost): A script to rehost your git repos in ipfs.
Author: [Jeromy Johnson](https://github.com/whyrusleeping)

* IPFS playback support in [Playback](https://mafintosh.github.io/playback/) video player. This allows casting a video in IPFS to a Chromecast. 
Patch Author: [Juan Benet](https://github.com/jbenet)

* [ipfs-firefox-addon](https://github.com/lidel/ipfs-firefox-addon): A Firefox addon for redirecting gateway.ipfs.io links to your local gateway. 
Author: [Marcin Rataj](https://github.com/lidel)

* [IPFS Linux Init Daemon](https://github.com/dylanPowers/ipfs-linux-service): For anyone running ipfs on a server somewhere (like an rpi in your living room), I've created a script that will install the ipfs daemon as a Linux system daemon. No more screen processes! :D
Author: [Dylan Powers](https://github.com/dylanPowers)

* [IPFS Gateway Redirect](https://github.com/dylanPowers/ipfs-chrome-extension): A Chrome extension that allows you to access gateway.ipfs.io urls the way they were meant: from your locally running ipfs daemon.
Author: [Dylan Powers](https://github.com/dylanPowers)

* [ipfs-userscript](https://github.com/loadletter/ipfs-redirect-userscript): Browser userscript for redirecting gateway.ipfs.io links to your local gateway. This should work on any browser that hasn’t had an extension written for it yet and has support for userscripts.
Author: [loadletter](https://github.com/loadletter)

* [IPFS Share](https://github.com/rameshvarun/ipfs-share): An IPFS backed Pastebin / Image Host / File Sharing application.
Author: [Varun Ramesh](https://github.com/rameshvarun)

* [IPFS Event Drop](https://github.com/travisperson/ipfs-event-drops): An app that allows for improved visualization of ipfs events.
Author: [Travis Person](https://github.com/travisperson)

* [Cohort](https://github.com/zignig/cohort): A golang app to preset a threejs interface and get all of its assets out of IPFS.
Author: [zignig](https://github.com/zignig)

**Comment by dylanPowers** [comment]
IPFS playback support in Playback video player. This allows casting a video on IPFS to a Chromecast. 
Patch Author: Juan Benet

**Comment by dylanPowers** [comment]
[git-ipfs-rehost](https://github.com/whyrusleeping/git-ipfs-rehost): A script to rehost your git repos in ipfs.
Author: [Jeromy Johnson](https://github.com/whyrusleeping)

**Comment by diasdavid** [comment]
This list is pretty sweet, can we bring it to https://github.com/ipfs/awesome-ipfs and make that the location for all of these links?

Plus, would love if the list could be embed on ipfs.io. @RichardLitt ? :)

**Comment by RichardLitt** [comment]
@diasdavid I think moving all of these links over would be a good thing to do. I'll add that to my things to do next sprint. Embedding it also sounds good.

**Comment by RichardLitt** [comment]
Closing as ipfs/awesome-ipfs satisfies this need.

**Comment by Madji** [comment]
please write a simple GUI to manage files. and then I added files and delete them can't anymore. many simply unrealistic to use this because of the difficulties
