### ISSUE TITLE
Module Release Guidelines

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#121]
We should make it more explicit when a module is totally ready for public consumption. This means more than just having a Readme that conforms to standards we set as a community; I mean taking a repo from an idea to a releasable 1.0.0 version. We should also have notes about why the module has been made, what the roadmap is for that ecosystem, and link to relevant discussion elsewhere.

Things I think it would be good to be able to rate module releasability on:
- [ ] Does it use semver
- [ ] Readme
  - [ ] Stubbed
  - [ ] Standardized
- [ ] Tests
- [ ] Does it have a Spec
  - [ ] Is that fleshed out
  - [ ] Implemented
  - [ ] Followed
- [ ] Planning, outline, and goals for the module

What am I missing? What do you think? This doesn't just apply to js modules, but to all modules we have that have a releasability vector.

**Comment by RichardLitt** [comment]
How do we enforce this? Write up a guideline markdown file?

**Comment by diasdavid** [comment]
Is this not happening by default already?

**Comment by RichardLitt** [comment]
> Is this not happening by default already?

It isn't. We don't have a way of tracking this information - would be great to do with something like project-repos - and we don't have clear guidelines. A lot of our modules are very basic, and it would be good to be able to grade them on a point scale for how finished or polished they are. Right now, we don't have measurable ways to track this.

**Comment by diasdavid** [comment]
Lot's of these are already included/revamped on https://github.com/ipfs/community/blob/master/js-code-guidelines.md and any future work around guidelines should be done through PR to the doc itself. Closing this issue as it has some spider webs :)
