### ISSUE TITLE
Use standard-readme for all Readmes

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#124]
I would like to enforce [standard-readme](//github.com/RichardLitt/standard-readme) throughout IPFS. You can look at the spec on the main Standard-Readme README, and look at the IPFS subset I want to lint for [here](https://github.com/RichardLitt/standard-readme/issues/9), or below:

Please give a thumbs up to this issue or open issues on standard-readme if you want or do not want specific sections. Or, discuss below. 
# 

These requirements are only for the [IPFS](https://github.com/ipfs) organization. They are included here because some people may still be curious how IPFS and Standard-Readme are related. Since this work is supported and will be used by the IPFS organization, they are relevant here, too, I think.
- [ ] Buttons
  - [ ] All repos: irc, made by Protocol Labs, IPFS project
  - [ ] Language repos: langdoc references, code style, dependencies, coverage
  - [ ] Travis
  - [ ] CI
  - [ ] Discussion repos
- [ ] Contribute banner with link to [global contribute.md](https://github.com/ipfs/community/blob/master/contributing.md)
- [ ] Link to questions
- [ ] `LICENSE` file
- [ ] `PATENTS` file
- [ ] `Contribute.md` file

**Comment by dignifiedquire** [comment]
Why do we have to have a `PATENTS` file? (A link to previous discussion is enough if this was already discussed somewhere else)

**Comment by noffle** [comment]
Heya Richard. Some aggressive grilling on many of your items:  :grinning:   I'm being aggressive on asking for concrete justifications on these only because the formula `(work to get 1 repo on standard) x (# of IPFS repos)` is so large. Having to change any aspect of this later ends up being multiplied across all of these repos -- it's better in my experience -- to start with less (only the things you 100% definitely need) and add more later as justification becomes very apparent. Without further ado:

1. What value does a IPFS button have? These'll be in the IPFS org, so ownership is already clear.
2. What value does a Protocol Labs button have? This doesn't affect contributors, and anyone who it would affect would already know about this relationship.
3. What is "langdoc references"?
4. Is "Travis" a subset of "CI"?
5. What does "discussion repos" refer to in this context?
6. What does "link to questions" refer to in this context?
7. Do we legally require a `LICENSE` file, or is mentioning it in the README sufficient? The latter would be preferred, since it reduces the amount of files in the repo root dir (less noise), and one less place to make a mistake (accidentally mismatch license in repo /w one in LICENSE file).
8. We're already adding a contribute banner and link to our contribution guidelines -- do we need a `contribute.md` file as well? Is there information in one that isn't in the other? Can we deduplicate?

**Comment by diasdavid** [comment]
One good way to get very concrete feedback is to submit 2 to 3 PR to projects inside the IPFS community that are lead by different people (2 to 3 projects per Lead maintainer), because as soon as you do that, each project maintainer will give a very throughout review if the readme matches what are their expectations.

**Comment by RichardLitt** [comment]
> I'm being aggressive on asking for concrete justifications on these only because the formula `(work to get 1 repo on standard) x (# of IPFS repos)` is so large. Having to change any aspect of this later ends up being multiplied across all of these repos -- it's better in my experience -- to start with less (only the things you 100% definitely need) and add more later as justification becomes very apparent. 

I agree with this. Thank you.

> 1. What value does a IPFS button have? These'll be in the IPFS org, so ownership is already clear.

Not all IPFS repositories are in the IPFS organization. We should really be applying this standard to anything developed under IPFS purview - libp2p and Orbit might also apply. But then, they shouldn't be tagged IPFS, I guess.

But branding is also important. I think the redundancy is OK. When filecoin and the like come out, we can re-evaluate this - for now, IPFS is the main name people know for this project, and we should reference that. Also, repos exist independantly of the organization - for instance, when cloned and in a local filesystem. There should be some note in the README about the organization.

**Suggestion**: Keep this.

> 2. What value does a Protocol Labs button have? This doesn't affect contributors, and anyone who it would affect would already know about this relationship.

Branding, really. It's another entry point, says where these things came from. Name recognition.

**Suggestion**: Keep this.

> 3. What is "langdoc references"?

Link back to js-contribute.md in community, or go-contribute.md. Language-relevant contribution guidelines.

**Suggestion**: Keep this.

> 4. Is "Travis" a subset of "CI"?

Yes. This label only applies when we actually have CI for a repo - obviously this doesn't happen for all of them.

**Suggestion**: Make optional.

> 5. What does "discussion repos" refer to in this context?

Something like https://github.com/ipfs/notes - repos which have no or minimal code in them, where all of the discussion happens in the GitHub issues.

**Suggestion:** Use a subset of standard-readme where there is no 'install' or 'usage' section. 

> 6. What does "link to questions" refer to in this context?

Link to the issues. This happens in the Contribute. 

> 7. Do we legally require a `LICENSE` file, or is mentioning it in the README sufficient? The latter would be preferred, since it reduces the amount of files in the repo root dir (less noise), and one less place to make a mistake (accidentally mismatch license in repo /w one in LICENSE file).

I believe we legally do. This is not a question I know the answer to, and I haven't seen conclusive proof either way. However, I think that the redundancy is important - licensing is something that should be clear from the README (the first entry point into a module), because it is relevant to contributors. I think it is more important to have it here than to worry about noise or the chance of a mistake.

**Suggestion:** Keep this.

> 8. We're already adding a contribute banner and link to our contribution guidelines -- do we need a `contribute.md` file as well? Is there information in one that isn't in the other? Can we deduplicate?

No, we don't need a contribute.md for each repo - a contribute section is enough.

**Suggestion:** Reword. 

====

> One good way to get very concrete feedback is to submit 2 to 3 PR to projects inside the IPFS community that are lead by different people (2 to 3 projects per Lead maintainer), because as soon as you do that, each project maintainer will give a very throughout review if the readme matches what are their expectations.

Good idea. Doing that now.

**Comment by Kubuxu** [comment]
Separate license files are important, if not from the pure law perspective then from the user and packaging perspective. If project has license file and I want to package the project (for example to AUR), I will copy the file to the license folder of your system. If it has no such file then I have to dig through README.

Also please, include name of the license in your LICENSE files. Especially if it is some of the more of a unusual license or BSD (there are two commonly used BSD variants and one more used early).

_I might have gone a bit of topic_

**Comment by RichardLitt** [comment]
Agreed on separate license file being mandatory. 

Not agreed on contribute file being mandatory for all repos - some can point to community just fine, or just have a small section (discussion repos). Good point about the notice for GitHub, though. Lean towards using it whenever possible?

**Comment by RichardLitt** [comment]
This is a tracking comment for all IPFS repos. Add links and checks here as appropriate.

- [x] apps https://github.com/ipfs/apps -- https://github.com/ipfs/apps/pull/28
- [ ] archive-format https://github.com/ipfs/archive-format
- [ ] archives https://github.com/ipfs/archives
- [ ] astralboot (fork) https://github.com/ipfs/astralboot
- [ ] awesome-ipfs https://github.com/ipfs/awesome-ipfs
- [ ] bitswap-ml https://github.com/ipfs/bitswap-ml
- [ ] blockchain-data https://github.com/ipfs/blockchain-data
- [ ] blog https://github.com/ipfs/blog
- [ ] browserify-zlib (fork) https://github.com/ipfs/browserify-zlib
- [ ] community https://github.com/ipfs/community
- [ ] connections-globe https://github.com/ipfs/connections-globe
- [ ] container-demos https://github.com/ipfs/container-demos
- [ ] dataviz https://github.com/ipfs/dataviz
- [ ] dir-index-html https://github.com/ipfs/dir-index-html
- [ ] distributions https://github.com/ipfs/distributions
- [ ] dnslink-deploy https://github.com/ipfs/dnslink-deploy
- [ ] examples https://github.com/ipfs/examples
- [ ] faq https://github.com/ipfs/faq
- [ ] file-browser https://github.com/ipfs/file-browser
- [ ] fs-repo-migrations https://github.com/ipfs/fs-repo-migrations
- [ ] fs-stress-test https://github.com/ipfs/fs-stress-test
- [ ] glossary https://github.com/ipfs/glossary
- [ ] go-blocks https://github.com/ipfs/go-blocks
- [ ] go-commands https://github.com/ipfs/go-commands
- [ ] go-datastore (fork) https://github.com/ipfs/go-datastore
- [ ] go-ipfs https://github.com/ipfs/go-ipfs
- [ ] go-ipfs-api https://github.com/ipfs/go-ipfs-api
- [ ] go-ipfs-util https://github.com/ipfs/go-ipfs-util
- [ ] go-ipld https://github.com/ipfs/go-ipld
- [ ] go-iprs https://github.com/ipfs/go-iprs
- [ ] go-key https://github.com/ipfs/go-key
- [ ] go-libp2p https://github.com/ipfs/go-libp2p
- [ ] go-libp2p-crypto https://github.com/ipfs/go-libp2p-crypto
- [ ] go-libp2p-loggables https://github.com/ipfs/go-libp2p-loggables
- [ ] go-libp2p-peer https://github.com/ipfs/go-libp2p-peer
- [ ] go-libp2p-peerstore https://github.com/ipfs/go-libp2p-peerstore
- [ ] go-libp2p-pubsub https://github.com/ipfs/go-libp2p-pubsub
- [ ] go-libp2p-secio https://github.com/ipfs/go-libp2p-secio
- [ ] go-libp2p-transport https://github.com/ipfs/go-libp2p-transport
- [ ] go-log https://github.com/ipfs/go-log
- [ ] golang-build (fork) https://github.com/ipfs/golang-build
- [ ] http-api-spec https://github.com/ipfs/http-api-spec
- [ ] infrastructure https://github.com/ipfs/infrastructure
- [ ] install-go-ipfs https://github.com/ipfs/install-go-ipfs
- [ ] interface-ipfs-core https://github.com/ipfs/interface-ipfs-core
- [ ] ipfs https://github.com/ipfs/ipfs
- [ ] ipfs-blob-store https://github.com/ipfs/ipfs-blob-store
- [ ] ipfs-geoip https://github.com/ipfs/ipfs-geoip
- [ ] ipfs-hubot https://github.com/ipfs/ipfs-hubot
- [ ] ipfs-interop https://github.com/ipfs/ipfs-interop
- [ ] ipfs-js-defaults https://github.com/ipfs/ipfs-js-defaults
- [ ] ipfs-npm https://github.com/ipfs/ipfs-npm
- [ ] ipfs-update https://github.com/ipfs/ipfs-update
- [ ] ipfs-web-app https://github.com/ipfs/ipfs-web-app
- [ ] ipfs.js https://github.com/ipfs/ipfs.js
- [ ] ipget https://github.com/ipfs/ipget
- [ ] ipld-examples https://github.com/ipfs/ipld-examples
- [ ] ipld.io https://github.com/ipfs/ipld.io
- [ ] java-ipfs-api https://github.com/ipfs/java-ipfs-api
- [x] js-ipfs https://github.com/ipfs/js-ipfs -- https://github.com/ipfs/js-ipfs/pull/324
- [ ] js-ipfs-api https://github.com/ipfs/js-ipfs-api
- [ ] js-ipfs-bitswap https://github.com/ipfs/js-ipfs-bitswap
- [ ] js-ipfs-block https://github.com/ipfs/js-ipfs-block
- [ ] js-ipfs-block-service https://github.com/ipfs/js-ipfs-block-service
- [ ] js-ipfs-examples https://github.com/ipfs/js-ipfs-examples
- [ ] js-ipfs-ipld https://github.com/ipfs/js-ipfs-ipld
- [ ] js-ipfs-path https://github.com/ipfs/js-ipfs-path
- [ ] js-ipfs-repo https://github.com/ipfs/js-ipfs-repo
- [ ] js-ipfs-unixfs https://github.com/ipfs/js-ipfs-unixfs
- [ ] js-ipfs-unixfs-engine https://github.com/ipfs/js-ipfs-unixfs-engine
- [ ] js-ipfsd-ctl https://github.com/ipfs/js-ipfsd-ctl
- [ ] js-ipld https://github.com/ipfs/js-ipld
- [ ] js-ipld-cli https://github.com/ipfs/js-ipld-cli
- [ ] js-libp2p-crypto https://github.com/ipfs/js-libp2p-crypto
- [ ] js-libp2p-ipfs https://github.com/ipfs/js-libp2p-ipfs
- [ ] js-libp2p-ipfs-browser https://github.com/ipfs/js-libp2p-ipfs-browser
- [ ] js-libp2p-secio https://github.com/ipfs/js-libp2p-secio
- [ ] logo https://github.com/ipfs/logo
- [ ] newsletter https://github.com/ipfs/newsletter
- [ ] notes https://github.com/ipfs/notes
- [ ] npm-go-ipfs https://github.com/ipfs/npm-go-ipfs
- [ ] ops-requests https://github.com/ipfs/ops-requests
- [ ] orbit https://github.com/haadcode/orbit -- https://github.com/haadcode/orbit/pull/35
- [ ] paperhub https://github.com/ipfs/paperhub
- [ ] papers https://github.com/ipfs/papers
- [ ] pinbot-irc (fork) https://github.com/ipfs/pinbot-irc
- [ ] pm https://github.com/ipfs/pm
- [ ] POST https://github.com/ipfs/POST
- [ ] project-repos https://github.com/ipfs/project-repos
- [ ] py-ipfs https://github.com/ipfs/py-ipfs
- [ ] py-ipfs-api https://github.com/ipfs/py-ipfs-api
- [ ] refs https://github.com/ipfs/refs
- [ ] refs-denylists-dmca https://github.com/ipfs/refs-denylists-dmca
- [ ] refs-solarnet-storage https://github.com/ipfs/refs-solarnet-storage
- [ ] scala-ipfs-api https://github.com/ipfs/scala-ipfs-api
- [ ] specs https://github.com/ipfs/specs
- [ ] starlog https://github.com/ipfs/starlog
- [ ] station https://github.com/ipfs/station
- [ ] support https://github.com/ipfs/support
- [ ] swift-ipfs-api https://github.com/ipfs/swift-ipfs-api
- [ ] website https://github.com/ipfs/website
- [ ] webui https://github.com/ipfs/webui

**Comment by RichardLitt** [comment]
What ought we to do about forks? For instance, [astralboot](https://github.com/ipfs/astralboot) is forked from @zignig's repo. Should I PR his README, too?

**Comment by RichardLitt** [comment]
This is relevant. Feedback would be great: https://github.com/RichardLitt/standard-readme/issues/20

**Comment by bryongloden** [comment]
Greetings @RichardLitt. Lean towards using GH GH whenever possible

**Comment by RichardLitt** [comment]
GH GH?

**Comment by bryongloden** [comment]
@RichardLitt yup. That's what she said

**Comment by RichardLitt** [comment]
So... lean towards using GitHub whenever possible?

**Comment by bryongloden** [comment]
Yup. Lean towards using GitHub whenever possible

**Comment by RichardLitt** [comment]
I would consider this now done. Anyone else want to weigh in?
