### ISSUE TITLE
Berlin Meetup June 2nd

### ISSUE THREAD

**Issue by lgierth** [ipfs/community#127]
On June 1st there's Decentralizes & Encrypted: https://medium.com/@BlueYard/join-the-people-working-on-upgrading-the-internet-decentralized-encrypted-7ff2b6ac1f8#.1cjgr0qtc

The evening of the 1st, StorJ are hosting a party, so that's not a good day for a meetup. Maybe Tuesday 31st or Thursday 2nd? @haadcode do you wanna ask c-base? You have the contact from last time, but I can do it tomorrow too.

What cool new stuff do we wanna show? Maybe someone would like to get familiar with AKASHA and demo it?

**Comment by lgierth** [comment]
I also just had another idea for a demo format: take something similar to (a part of) IPFS, e.g. ethereum's swarm, or freenet, or dat, etc. -- explain the essential differences, and show/demo examples.

I'm just coming up with this because it'd be pretty boring to just show the same stuff as at the meetup here 3 weeks ago.

**Comment by lgierth** [comment]
Meetup on May 2nd: https://github.com/ipfs/community/issues/116

**Comment by aistich** [comment]
Hi @lgierth & @haadcode 
I am here to help with getting this set up. Please let me know what i can do/ anything i need to know to contribute.
💃

**Comment by diasdavid** [comment]
I arrive on the 31st and leave on the 1st night to WebRebels conf, won't be able to make it to the meetup

**Comment by ligi** [comment]
We got a go from c-base cultorga for the 2.6. - we will have to share the space with the go-lounge ( the game and not the language ) - but go-players are very friendly and there should be nice co-existence.
Tuesday c-base is blocked by Berlin-Hack&Tell also a very nice event - @jbenet was presenting there last time - http://www.meetup.com/de-DE/Berlin-Hack-and-Tell/events/231484893
Content-wise I could give a short update on IPFSDroid at the meetup

**Comment by jbenet** [comment]
Excellent! thanks very much for making this happen @ligi! 

Our meetup will start at 8pm (talks at 8:30p) so that we overlap very little with the Storj meetup and they can have their event without people being conflicted.

**Comment by jbenet** [comment]
### talk ideas

@lgierth we can definitely muster new things to talk about. like the idea about picking some tech and comparing and contrasting!

while we should mention js-ipfs again and maybe show updated orbit demo ("now in 100% javascript!") -- since this is properly new. 

But you're right, we should def talk about new things too. 

I can muster one of these:

- libp2p, or libp2p parts (very relevant to D&E attendants) 
  - libp2p transports
  - authenticated transport survey
- modeling something in IPLD (blockchains? git? CRDTs?)
- multiprotocols -- have been meaning to give a talk on these forever.

i'm sure others can talk about other things.

you or I  could give a talk on the gateway itself! and how to run one for yourself.

**Comment by lgierth** [comment]
The DialMe/NAT/switching issue can be made a little talk too: https://github.com/ipfs/notes/issues/110

**Comment by aistich** [comment]
Hi team,
Can we get together a more formalized list of topics and speakers?

**Comment by ligi** [comment]
Do you already know how many people will participate approx? Would be good to know for setting up the chairs - same as last time?

**Comment by jbenet** [comment]
@ligi what was that last time? 50? 100? or so?

**Comment by aistich** [comment]
@ligi I will keep an eye on our eventbrite and post the approximate participation numbers for you to have early tomorrow morning.

**Comment by bergie** [comment]
Eventbrite link appears to be https://www.eventbrite.com/e/berlin-ipfs-meetup-at-c-base-2016-06-02-tickets-25807833926

**Comment by aistich** [comment]
^^ 👍 
## IPFS Meetup is back in Berlin following the Decentralized and Encrypted conference!
#### Thursday, June 2nd 20:00- 22:00 hrs.
 This time we will be seeing a continuation of the demo's presented at D&E, and hearing from @jbenet (Juan Benet) . Don't miss this opportunity to hang out with us! 

IPFS -- the InterPlanetary File System -- is making the web faster, safer, decentralized, and more open. It is a new hypermedia distribution protocol, addressed by content and identities. Think Git + BitTorrent + The Web. IPFS is in use by thousands of developers, for all kinds of things from distributing files more efficiently, to making decentralized chat applications, to giving permanent addresses to content, to hosting content for Blockchains. 
You can learn more about IPFS at https://ipfs.io and https://github.com/ipfs/ipfs

### Format: Mingling, 3 short talks,  and a  little more mingling.
  Drinks: We will provide drink credits for  beers and non-alcoholic drinks
  Food: Sorry, no snacks this time.

### Location: C-Base
Directions: https://www.c-base.org/cv50f/core/impressum.html and http://www.openstreetmap.de/karte.html?zoom=17&lat=52.51298&lon=13.42012&layers=B0

### Agenda
TBA

Here is the [link to our Eventbrite]( https://www.eventbrite.com/e/berlin-ipfs-meetup-at-c-base-2016-06-02-tickets-25807833926) one more time

**Comment by ligi** [comment]
I think last time we where 50ish - but I did not count

**Comment by jbenet** [comment]
Hey everyone! 

@shea256 from Blockstack is also in Berlin and they were also doing a meetup same day at 7p. Since our interested communities overlap a lot, we figured we should combine our meetups. Blockstack's meetup page is this: http://www.meetup.com/Blockstack-Berlin/events/231428283/

**Comment by jbenet** [comment]
@christianlundkvist @wanderer could you fwd https://www.eventbrite.com/e/berlin-ipfs-meetup-at-c-base-2016-06-02-tickets-25807833926 to whoever may be interested in coming from Eth? or maybe the berlin list?

thanks

**Comment by wanderer** [comment]
@jbenet ack

**Comment by shea256** [comment]
Hey thanks @jbenet. Looking forward to the joint meet up. See everyone later today!

**Comment by lgierth** [comment]
@aistich 

### Connectivity is easy!

Said noone ever. It's 2016 and still plenty of issues get in our way
when our computers try to connect to each other over the internet.
There's NATs to be traversed, holes to be punched, overzealous firewalls
to be evaded. @lgierth will show how these affect IPFS, what measures it takes
to still establish connections, and how packet switching might save us all.

**Comment by ligi** [comment]
here the recording from yesterday: https://www.youtube.com/watch?v=JDX10HNTqU0
Thanks for the meeting everyone - I think this issue can be closed now

**Comment by shea256** [comment]
Thanks for the recording @ligi! Did anyone happen to take pictures from the event?

**Comment by ligi** [comment]
I wasn't recording - just posted the link. Also I am not aware of photos taken - I even had to tell people to not take or even delete some - had to especially enforce this after someone took a photo in the nerd-area and there was some trouble around it ( there are really photo shy people and a very strict no photo area) And as I would love some more IPFS meetups at c-base I had to take care of this.
Btw. what do you guys think about a monthlyish IPFS Stammtisch - does not have to be as big as the meetups - just a small get-together and exchange of Ideas.

**Comment by diasdavid** [comment]
Just as a heads up to everyone that has attended in the past to IPFS meetup, me @lgierth @haadcode and @hsanjuan will be at http://www.dapphack.org/ this week, join us for the hacking! :) (+ I heard there will be some quite fine beers!)
