### ISSUE TITLE
IRC: Op and voicing for #ipfs

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#129]
The #ipfs channel on IRC is part of the IPFS community; as such, the [Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) for IPFS still applies. Occasionally, it is important that someone moderate the channel to make sure that it stays a safe space; today, we had to ban a bot that was spamming irrelevant information, for instance. 

Current ops are: @jbenet @whyrusleeping @lgierth @diasdavid @dignifiedquire @RichardLitt and @noffle. 

I'd also like to add a few people in the community; maybe @eminence @Kubuxu @cryptix @davidar and @mappum. We don't have to auto-op; it's not that we're keen on banning or kicking people, we just need to have someone be able to moderate when needed. Would you be interested? 

If anyone thinks they would like to help, feel free to ping us.

**Comment by Kubuxu** [comment]
I am a lot of IRC and I could help moderate it (so we don't have Allah bots on channel).

**Comment by eminence** [comment]
I'm flattered you thought to include me, @RichardLitt .  I would happy accept, but for the following caveat:  I'm not much in the IRC channel these days (though I'll often respond quickly if pinged).   I know that chanops are not really a limited resource, but feel free to promote other community members first.
