### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#133]
Currently, there are a few translation efforts going on - some on the website (see https://github.com/ipfs/website/pull/87), and some on the webui (see https://github.com/ipfs/webui/pull/396). 

While this is totally awesome, I am not sure it is a good use of effort right now. This community moves very fast, and documentation swiftly gets out of date. It might be better to encourage translators to hold off, for now, by adding a note to the contribute guide saying that we are not currently accepting translations. 

What do you think? @dignifiedquire @lgierth 

Note: If anyone has any issues understanding the English documentation, please let us know! If you would like to do so privately, please email me - I am very sensitive to language issues, and do not want to turn anyone away from hacking because of language issues. In particular, I imagine that some Chinese translations may be useful for their community, when they start using IPFS.

**Comment by lgierth** [comment]
While I think it's okay for the webui (it's relatively small and scoped), it's a gamble for the website and everything else, for the same reasons you lay out:

> While this is totally awesome, I am not sure it is a good use of effort right now. This community moves very fast, and documentation swiftly gets out of date.

I agree that it'd be good to explicitly encourage holding off. This will hopefully also prevent these drive-by translation PRs like the ipfs/website#87.

**Comment by diasdavid** [comment]
Shipped by @lidel with https://www.transifex.com/
