### ISSUE TITLE
Good Reads

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#134]
Let's collect some links for protocol engineering.

**Comment by jbenet** [comment]
- https://www.nanog.org/sites/default/files/Paasch_Network_Support.pdf on TCP Fast Open and the experiences with real deployment. Curse the middleboxes.

**Comment by RichardLitt** [comment]
Possible duplicate of https://github.com/ipfs/ipfs/pull/24.

**Comment by pawal** [comment]
[RFC 5218](https://tools.ietf.org/html/rfc5218), "What Makes for a Successful Protocol?".

**Comment by diasdavid** [comment]
-> https://github.com/ipfs/reading-list
