### ISSUE TITLE
Hacking in Lisbon - July 20 onwards

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#135]
Hi y'all!

The IPFS crowd will be present in Lisbon for a big chunk of July and since a lot of people showed interest in joining us for some days for some IPFS hacking, I'm opening an invitation to everyone that wants to join us :)

The dates that you should be looking at is July 20 onwards. If you will be joining us, please comment on this issue, we might get some office space for everyone or just hack from coffee shops or historical sites while easting some typical portuguese pastries :)

I'll be looking if we can do a meetup/mini conference one of the days, if folks are available to give talks, of course :)

**Comment by JGAntunes** [comment]
I would be in for that! \o/

**Comment by joaobelo92** [comment]
I'm in!! Looking forward to go!

**Comment by shamb0t** [comment]
I'm in

**Comment by yoshuawuyts** [comment]
Yeah I'm def in too! :tada:

**Comment by diasdavid** [comment]
We just announced the IPFS Workshop http://www.meetup.com/ipfs-lisbon-meetup/events/232483114 :D save the dates and book the flights!

**Comment by RichardLitt** [comment]
Closing this as this is happening! See #142.
