### ISSUE TITLE
Directory of people in charge of endeavors

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#140]
I would like to create a list of people in charge of various IPFS-related endeavors. For instance:
- @diasdavid : js-ipfs, libp2p
- @whyrusleeping : go-code in all of it's forms
- @lgierth : Infrastructure
- @RichardLitt : community infrastructure and docs

This way, if anyone wants to hack on say, Javascript related things, they would know to contact @diasdavid about the best place to start. Rust has [something similar](https://www.rust-lang.org/community.html#the-rust-team) that I think we could copy. 

What do you think about this? Where should it go? Would you use it?

**Comment by dignifiedquire** [comment]
I generally agree, but I would suggest making it teams like the Rust example rather than individuals.

**Comment by condiosluzverde** [comment]
Link to rust example?

----
james mcfarland
james@jamesmcfarland.com
www.jamesmcfarland.com

**Comment by dignifiedquire** [comment]
@condiosluzverde above in the original post under "something similar"

**Comment by condiosluzverde** [comment]
Thanks - read on mobile originally and missed the link.

I agree, I really like the Rust-lang look and team-based approach.

On Thu, Jun 23, 2016 at 6:15 PM, Friedel Ziegelmayer <
notifications@github.com> wrote:

> @condiosluzverde <https://github.com/condiosluzverde> above in the
> original post under "something similar"
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ipfs/community/issues/140#issuecomment-228201822>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABzw8ZV7cUWKW23ssfAx9ofbMt_phSPZks5qOwVogaJpZM4I70ZT>
> .
>



-- 
james mcfarland
james@jamesmcfarland.com
http://jamesmcfarland.com
