### ISSUE TITLE
Location of the Lisbon Workshop

### ISSUE THREAD

**Issue by chriscool** [ipfs/community#144]
On [Eventbrite](https://www.eventbrite.com/e/ipfs-workshop-q3-and-beyond-tickets-26559316631?utm-medium=discovery&utm-campaign=social&utm-content=attendeeshare&utm-source=cp&utm-term=listing) the location is:

Cowork Lisboa LX Factory - Rua Rodrigues Faria 103 Edifício I - 4º Piso, , Lisbon, Portugal

but on [Meetup](http://www.meetup.com/ipfs-lisbon-meetup/events/232483114/) it has been updated to:

`Beta-i` at Avenida Casal Ribeiro, 28, Lisbon (Saldanha subway station)

I think it would be good to update the location so that it is the same everywhere.

cc @diasdavid

**Comment by RichardLitt** [comment]
Thanks, @chriscool. @aistich, can you help here?

**Comment by chriscool** [comment]
Sorry I thought that I had opened this issue in the workshop repo (https://github.com/ipfs/2016-Q3-Workshop) instead of this repo.
I can move it there if it is prefered.

**Comment by aistich** [comment]
@chriscool 

Sorry for any confusion the new location is 

Beta-i 
Av. Casal Ribeiro 28, 1000-092 Lisboa
Floor 8

**Comment by chriscool** [comment]
@aistich Yeah, sure I am there. Can you update the Eventbrite location?
