### ISSUE TITLE
Signed commits

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#147]
go-ipfs has a long running best practice of requesting their contributors to sign their commits -- https://github.com/ipfs/community/blob/master/contribution-guidelines.md#a-license-and-a-signed-off-by-trailers-are-required --, since it is the same project, we should do that for js-ipfs, libp2p and all their modules.

In fact, I even created a module just to run the bash script (I kept looking for it) https://www.npmjs.com/package/sign-commit

Thoughts?

@RichardLitt could you help us set up this guideline for the js ecosystem? Thank you :)

**Comment by dignifiedquire** [comment]
@jbenet answered this here: https://github.com/ipfs/distributions/pull/76 so lets figure out the best steps to ensure this happens everywhere, including setting up validation.

**Comment by diasdavid** [comment]
ping @RichardLitt

**Comment by diasdavid** [comment]
This is now part of #253
