### ISSUE TITLE
ipfs-gh on freenode

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#151]
I really like these:

![image](https://cloud.githubusercontent.com/assets/1211152/17405250/bdc9d8b6-5a56-11e6-8b2c-bf03f80eb5e0.png)

But having all of them in the main channel might be a bit too much. What if we have a #ipfs-gh just for the github notifications from the project?

**Comment by whyrusleeping** [comment]
Maybe `#ipfs-dev` ?

**Comment by dignifiedquire** [comment]
As mentioned before the Rust community does an awesome job of different channels: https://www.rust-lang.org/en-US/community.html

**Comment by Kubuxu** [comment]
I have ignored the bot because of the spam.

**Comment by RichardLitt** [comment]
If we have another channel, we can have work for all repos in it, too, not just for go-ipfs.

**Comment by jbenet** [comment]
Lets use #ipfs-bots and NOT #ipfs-dev. The latter encourages dev
conversation out of the main channel. We want the opposite: we want the
main channel to have much more dev conversation

**Comment by RichardLitt** [comment]
@diasdavid Where are the current notifications going? Did we remove them?

**Comment by diasdavid** [comment]
They were disabled, by @lgierth or @whyrusleeping, don't recall. Seems to be 'working' for everyone.

**Comment by RichardLitt** [comment]
Why don't we throw them in #ipfs-bots? @VictorBjelkholm has been squatting the channel, and it's active. As we want to move pinbot somewhere, too, that would be a good place for it.

**Comment by diasdavid** [comment]
No more need for this
