### ISSUE TITLE
Contribution Guidelines should display Code of Conduct first

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#154]
The first item in the [Contribution Guidelines](https://github.com/ipfs/community/blob/master/contributing.md) for all repositories should mention the code of conduct and give a plain-language single-sentence synopsis of the code of conduct.

cc @RichardLitt @em-ly

**Comment by RichardLitt** [comment]
I agree that there should be a CoC mention in each repository. Can you back up why it should be the first item?

**Comment by flyingzumwalt** [comment]
Ah. I see that there is already a [Community Guidelines](https://github.com/ipfs/community/blob/master/contributing.md#community-guidelines) section. That's what I meant.  Why put that first? 

 1. It's the most important thing to convey when orienting someone. If they only read that and actually operate by those guiding principles the community will help them figure out the rest. 
 2. It conveys a message about the community's priorities. We get things done (the work speaks for itself) but we do it with the sense of integrity conveyed by the community guidelines.

**Comment by RichardLitt** [comment]
OK. I think it should go after security, because that's been prioritized as first before. Would you be OK with me moving it there?

**Comment by flyingzumwalt** [comment]
:+1: that makes sense.
