### ISSUE TITLE
Request for signup-style newsletter

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#16]
Some users have expressed desire for a signup-style newsletter. We will have to do this eventually.

**Comment by RichardLitt** [comment]
I could set up one on Mailchimp? We might want to go with a Listserv or something, though.

**Comment by whyrusleeping** [comment]
Does google groups satisfy this?

**Comment by RichardLitt** [comment]
It might. You can set it so that only managers can view list of members, and only managers can post. Downside is that it would be annoying to send out beautiful emails, and I'm not sure the analytics is anywhere near as good.

**Comment by jbenet** [comment]
I'm :+1: on doing a proper, nice looking newsletter in the long run. This is different than a community mailing list. however, i dont think we should jump on that unless we have someone who could commit to doing this indefinitely and would not miss it. (meaning that a newsletter must be a regular thing).

another option is periodic updates like the ["State of Go"](https://www.google.com/search?q=the+state+of+go) talks.

cc @kyledrake

**Comment by RichardLitt** [comment]
A good example to follow would be [NPM's weekly newsletter](https://www.npmjs.com/npm-weekly?utm_campaign=newsletter20150917). I think monthly or so would be fine, though.

**Comment by RichardLitt** [comment]
This has been set up. :!
