### ISSUE TITLE
Create a place to list/track papers about IPFS

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#164]
People have started presenting papers at conferences about the things they're doing with IPFS.   We should create some place for people to post links to those papers, so we can have a sort of running bibliography of papers about IPFS.

**Comment by RichardLitt** [comment]
I think this should go in:

ipfs/awesome-ipfs
ipfs/papers
or https://github.com/ipfs/reading-list

I think that the first and the last would be best. I don't know what @jbenet had in mind for ipfs/papers.

**Comment by flyingzumwalt** [comment]
I'm glad to see that they already exist. Let's discuss it briefly on the all-hands call?

**Comment by VictorBjelkholm** [comment]
My five cents about how I see these different repos.

ipfs/awesome-ipfs random stuff around the internet that is awesomely using IPFS

ipfs/papers papers that have come out from speccing, implementing and deploying IPFS

ipfs/reading-list interesting papers/books/posts that is related to P2P

**Comment by jbenet** [comment]
+1 to @VictorBjelkholm's characterization. 

We could make a list in ipfs/papers of papers _not written by ipfs team_ but that involve ipfs

**Comment by RichardLitt** [comment]
@VictorBjelkholm Said it well. I agree completely. Let's make a section in ipfs/papers for this, to close this issue?

**Comment by flyingzumwalt** [comment]
Before we close the ticket, I'd like to know 
1. Where are the trails leading people to find these repositories?
2. Do we need more links leading to these repositories? If so, where?
3. Do the README files need to be updated? If so, we should create issues for them before closing this one.

**Comment by flyingzumwalt** [comment]
READMEs:
* 👍 https://github.com/ipfs/reading-list README looks fine
* 👍 https://github.com/ipfs/awesome-ipfs looks fine
* ❗ https://github.com/ipfs/papers README needs to be updated

Should they all be updated to point to each other?

**Comment by RichardLitt** [comment]
1. Where are the trails leading people to find these repositories?

 ipfs.io/docs, ipfs/ipfs, and ipfs/community.

2. No, I don't think so - this should cover the main use cases. We could also link to them in the go-ipfs and js-ipfs READMEs, though.

3. Most likely. I should also update https://ipfs.io/docs and ipfs/ipfs.

**Comment by flyingzumwalt** [comment]
Cool. @RichardLitt are you willing to do these updates? Are you cool with creating the tickets for that work? If so, go ahead and close this issue.

**Comment by RichardLitt** [comment]
Yes, I am happy to do this. I will keep this open and refer to it as the tracker.

**Comment by flyingzumwalt** [comment]
Thank you.

**Comment by RichardLitt** [comment]
@jbenet Are you ok with me captaining ipfs/papers? You may not have time for it, and there are a few open issues and PRs.

**Comment by RichardLitt** [comment]
> We could also link to them in the go-ipfs and js-ipfs READMEs, though.

I am changing my mind on this; I don't think it is necessary. ipfs/ipfs, ipfs.io/docs, and ipfs/community is probably enough.

**Comment by RichardLitt** [comment]
Added a few PRs.

**Comment by RichardLitt** [comment]
#### What

I think we need to overhaul how we reference papers and refer to community repos.

#### How

I think we should have one reference point for where to look for other repos; having a directory in ipfs.io/docs makes sense, because the website is a huge entry-point for the organization, especially for those not used to GitHub. Having a link to docs repos in ipfs/ipfs also makes sense, because we have made that kind of like an entry point into the GitHub organization - it's where you go to find out about community, pm, and the like. 

But I'm not sure that we should duplicate these two lists in ipfs/community, or anywhere else; I think we should use the ipfs/ipfs repo as what it is - an entry point to the rest of the organization - and not farm out that to other repos.

#### Multiple Papers Repos

I'm not sure why there needs to be two different repos for papers, it can be confusing. I know why awesome-ipfs exists; I made it, and it highlights things that are, well, awesome. Not all papers are or will be, and not all papers belong there - but having ipfs/papers and ipfs/reading-list will get confusing.

**Actionable**: 
- We should link to ipfs/ipfs from all of the other GitHub repos, most likely, because right now we don't. 
- Merge ipfs/papers, ipfs/reading-list, and ipfs/ipfs papers that are in the git repo into ipfs/papers.

**Comment by flyingzumwalt** [comment]
The two actions you suggest make sense to me. 

What do you mean by "having a directory in ipfs.io/docs makes sense"? I don't see an action item related to that. Are you suggesting that the page at ipfs.io/docs should have a section about papers? A link? It sounds like you're suggesting that there should be a directory on the website with papers in it, but that doesn't make sense.

**Comment by RichardLitt** [comment]
Sorry for not being clear: having a directory of IPFS repositories that may be useful to newcomers, on ipfs.io/docs, is smart. We can link to the papers repos from there. What I don't want to do is to have 30 different directories of the IPFS project, because then the risk of each growing stale is higher.

**Comment by flyingzumwalt** [comment]
Ah. You mean directory in the wayfinding sense. I thought you meant directory like unix directory (aka "folder").

**Comment by flyingzumwalt** [comment]
On #170 @jbenet commented

> Worth mentioning: The goal for reading-list repo was a bibliography for us
to read, i.e. Other people's papers in relevant fields. Not neceassarily
papers about ipfs. I'm fine keeping this all in one repo,. Just want to
mention that use case

This is an important use case to cover -- I plan to start curating those reading lists and might even start hosting online "reading clubs". @RichardLitt do you have ideas about how to distinguish between "papers about IPFS" and "reference papers for technologies related to IPFS" within the ipfs/papers repo if we consolidate the two lists?

**Comment by RichardLitt** [comment]
Yes; I think a section heading would be enough. 

````
### Papers about IPFS

- IPFS is the best, Joe 2016 ...
- IPFS is awesome and here is why, Tanuki, 2015

### Papers on related technology

- P2P will save the world, Professor Oak, 2016
- ...
```

Like this. 

Let's add these papers in [this PR](https://github.com/ipfs/ipfs/pull/24/files) into ipfs/papers. Sound good?

**Comment by flyingzumwalt** [comment]
:+1:

**Comment by jbenet** [comment]
> @jbenet Are you ok with me captaining ipfs/papers? You may not have time for it, and there are a few open issues and PRs.

I don't have time to captain this. But do have lots of desires and strong opinions on the goals for this repo. 

What are you trying to do there?

> there are a few open issues and PRs.

If you're referring to PRs against the paper, i'm not merging them for a reason. I am not merging to avoid contributions that I do not want (rearrangements, more information, changes, etc). Even simple fixes (like typos) may start a bunch of other PRs. That paper needs a large re-write, and i will rewrite it when I'm ready to.

If people desperately want to correct the typos, I may be open to that, but that's it. No re-arrangements, or information additions or deletions, or anything. That paper sorely needs a full re-write, and incremental improvements will only waste my time-- time I would rather put towards more pressing issues or a proper rewrite.

This makes me think we should separate paper listings and the papers themselves -- ie we _should not_ work on the papers we write in the ipfs/papers repo (as originally intended), but instead in independent, per-paper, repos (eg `ipfs/paper-cap2pfs` or something).

**Comment by RichardLitt** [comment]
> I don't have time to captain this. But do have lots of desires and strong opinions on the goals for this repo.

I thought so, and makes sense. 

I would simply like to have a listing of papers in the ipfs/papers repo. We would collapse ipfs/reading-list into it. 

Regarding current PRs and issues to the ipfs/papers repo, to do with your scholarly papers in there; I don't really want to touch those. I could close them, or move them. It may be a lot easier if we just rename ipfs/reading-list to ipfs/bibliography, and just mention that ipfs/papers is only for scholarly papers, which aren't a priority. We can use ipfs/bibliography (or ipfs/reading-list) for the things mentioned above.

**Comment by diasdavid** [comment]
Anything left to be done for this one?

**Comment by RichardLitt** [comment]
For now, I am happy with ipfs/reading-list. I've added a couple of PRs referring to it; those need to be closed, and then this can be. I think the central purpose of this issue will be done then. 

Looking back now, I'm not sure that editing ipfs/papers makes sense. I think it would encourage people to ask about the PRs on it; and my guess is that we're not going to to be merging those soon. I'd prefer having a repository that is just about including links to papers; reading-list encapsulates that.
