### ISSUE TITLE
IPFS Meetup in Barcelona around FullStackFest

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/community#166]
Fullstack Fest is a conference in Barcelona that hosts talks about everything software. @jbenet will be there to talk about IPFS, @neoteo is around as well so we thought it would be a great idea to host an IPFS meetup at the same time, or around

## When

Around [FullStackFest](https://2016.fullstackfest.com/) (September 5-9), one idea is on the 7th (wednesday) (https://twitter.com/FullStackFest/status/770875288360259584), there is a "Hack Room" that seems to be available in the venue then.

## Where

Barcelona, Spain. Probably around where FullstackFest is being organized

Preliminary Address: Avinguda Diagonal 547, 08029, Barcelona

## Format

A couple of talks (about IPFS in general, IPLD, libp2p and multiformats?) and some time to pair up with fellow hackers to work on something.

**Comment by VictorBjelkholm** [comment]
cc @neoteo @xicombd @masylum

**Comment by NeoTeo** [comment]
Gah, looks like it's a bit too late for me. I'm out on the 5th and flying home on 6th. :/

**Comment by jbenet** [comment]
ahh bummer @NeoTeo -- my talk is on the 6th.

**Comment by jbenet** [comment]
+1 to this meetup, i can announce it tomorrow at the end of my talk

**Comment by jbenet** [comment]
We should figure out a time with the FullStackFest coordinators. i dont have time for this tonight, maybe tomorrow. (unless you can follow up on that twitter thread @VictorBjelkholm ?)

**Comment by VictorBjelkholm** [comment]
@jbenet yeah, I've been in touch with them before, I'll contact them.

**Comment by NeoTeo** [comment]
@juanbenet Yeah. Next time :)

**Comment by jbenet** [comment]
Starts in 20min at Auditori AXA

https://twitter.com/IPFSbot/status/773486380836061184

**Comment by VictorBjelkholm** [comment]
Done! Was not a lot of people but some productive time was spent on hacking some things and talking with a person from openSuse about rpm on ipfs (https://github.com/ipfs/notes/issues/164) and such.
