### ISSUE TITLE
Assemble workshop learning materials

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#168]
Assemble workshop material that can be used at nodeschool-style in-person workshops.

Some reference materials:
- #167: Outline a Curriculum for Learning IPFS-related Topics
- https://github.com/ipfs/go-ipfs/issues/171: `ipfs tour`
- https://github.com/ipfs/go-ipfs/issues/1764: Detailing the Tour functionality
- [NodeSchool](http://nodeschool.io/)
- [Better community building for IPFS](https://github.com/ipfs/community/issues/64)

Whichever format we use to present the info, the thing I really care about is curriculum design.  For each workshop we need to identify the
- Key Concepts
- Learning Objectives
- Learning Activities
- Conceptual Framework

The more we can do to be clear about those things, the easier it will be to produce great learning materials that are easy to maintain over time.
## Optional Formats: Nodeschool workshopper/adventure and RailsBridge

We could create these as nodeschool workshoppers or adventures. Alternatively we could follow the format used by RailsBridge.

refs #161

**Comment by diasdavid** [comment]
moved convo to https://github.com/ipfs/docs/issues/123
