### ISSUE TITLE
Assemble docs on how to host a workshop or meetup

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#169]
_@RichardLitt please fill in here..._

Some reference materials
  - [NodeSchool](http://nodeschool.io/)
  - [Better community building for IPFS](https://github.com/ipfs/community/issues/64)

refs #161

**Comment by RichardLitt** [comment]
Is there anything would like to see which wasn't included in #171, @flyingzumwalt?

**Comment by flyingzumwalt** [comment]
Nope. #171 covers it fine for a first pass.
