### ISSUE TITLE
Want IPFS Stickers?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#175]
IPFS has stickers that you can get. Unfortunately, Stickermule has closed their marketplace, so you will have to direct requests [through Skylar](https://github.com/ipfs/community/issues/11#issuecomment-357773361). 

[![ipfs-logo](https://cloud.githubusercontent.com/assets/910753/18646531/0770399a-7e80-11e6-80d6-8eda63f72569.png)](https://www.stickermule.com/marketplace/11503-ipfs-logo)

In the past, I've asked for addresses and mailed them out -- see https://github.com/ipfs/community/issues/50 for an example of that. Going forward, we think it would be better if people who want them order them for themselves, and we can reimburse you using Bitcoin. To request reimbursement, send an email to `skylar+stickers@protocol.ai` with your bitcoin address and a copy of the receipt from Stickermule. 

Let us know if you're ordering more than 50, with a request here on why you want that many (to stop everyone ordering 1000 and then billing us for it. :D) 

Stickers! 🎉 \o/

**Comment by jdorfman** [comment]
@RichardLitt let me know if we can help: jdorfman @stickermule .com

**Comment by dysbulic** [comment]
I got 10 for $16.

bitcoin:1QFkZVw3xitVKXJamyyBiu4HQZvhUzL7tb

-W

**Comment by diasdavid** [comment]
@skylar, just signaling this to you as I know you have been working on making it easier for the community to get Stickers and other types of swag. Currently, this is the only information publicly available, a very old issue. I'm not sure if now is the best time, but in the future we can bump this to the readme of the repo :)

**Comment by RichardLitt** [comment]
I've updated this comment to reflect Skylar's email address. Send her your sticker reimbursements, peeps!

**Comment by eric-holobyn** [comment]
The link has died :(

**Comment by RichardLitt** [comment]
@eric-holobyn Changed it. See #11. https://github.com/ipfs/community/issues/11#issuecomment-357773361

**Comment by skylar** [comment]
Wrong skylar...

skylar

**Comment by RichardLitt** [comment]
@skylarnorris Ping. :)

**Comment by skylarnorris** [comment]
Weird, I definitely left a comment last week. 

I've updated the README. Stickermule no longer offers their marketplace, so sticker requests require an email to me (address in readme).
