### ISSUE TITLE
33c3 - Chaos Communication Congress Dec 27-30 2016

### ISSUE THREAD

**Issue by pawal** [ipfs/community#178]
Is there enough interest to have a meetup at 33c3 in Hamburg?

**Comment by dignifiedquire** [comment]
@lgierth wants to come and myself, I guess others as well, so we could think about it.

**Comment by lgierth** [comment]
Yes I'd say we should have an assembly and workshops and lightning talks again. We also submitted a lecture talk on the Ethics/Society/Politics track.

**Comment by diasdavid** [comment]
# It is that time of the year!

![image](https://cloud.githubusercontent.com/assets/1211152/19827495/52818586-9da4-11e6-98f4-724c301d925c.png)

# Who is coming this year?

If you are coming this year, make sure to post in this issue :)

# Make sure to get your tickets

Tickets do SOLD OUT, make sure to pay attention to batch ticket sales and get yours:

https://events.ccc.de/2016/10/16/33c3-tickets-status-und-freier-verkauf/

# Last year's planning issue

https://github.com/ipfs/community/issues/74

![image](https://cloud.githubusercontent.com/assets/1211152/19827502/6ef5a8a0-9da4-11e6-9688-743881856144.png)

![image](https://cloud.githubusercontent.com/assets/1211152/19827501/68494462-9da4-11e6-9beb-877d048e516f.png)

**Comment by pawal** [comment]
I am coming (already booked everything), and will definitely join any workshops related to IPFS. Not sure about joining the assembly, but I will definitely want to hangout there for a bit.

**Comment by cryptix** [comment]
Got my ticket and I will be there. ;)

**Comment by ralphtheninja** [comment]
Haven't planned on going this year. But if someone has a spare ticket and a place where I can crash I might change my mind :D If not, ya'll have an amazing time!

**Comment by Kubuxu** [comment]
@diasdavid you forgot to include me.

**Comment by diasdavid** [comment]
<3 <3 <3 @Kubuxu

**Comment by noffle** [comment]
I'd *love* to come, but I'll be traveling during this time! :cry:  Have a blast!

**Comment by flyingzumwalt** [comment]
I'll be there.

**Comment by mafintosh** [comment]
Also going

**Comment by watson** [comment]
I'm going of cause - still need to get a hold on a ticket. When does the next batch go on sale?

**Comment by diasdavid** [comment]
@watson: @lgierth has an eye on the next batch and will get a bunch. @lgierth are you getting a couple of extras this year?

**Comment by feross** [comment]
Going to try to nab a ticket!

**Comment by lgierth** [comment]
@ralphtheninja @watson I'm trying to grab tickets for you two

**Comment by mafintosh** [comment]
@lgierth could you grab one for me also?

**Comment by lgierth** [comment]
> @lgierth could you grab one for me also?

ok sure

**Comment by lgierth** [comment]
Will have to try again next batch -- all sold out and I didn't get through the waves of 504.

**Comment by RichardLitt** [comment]
@lgierth Can we help with that?

**Comment by lgierth** [comment]
Yes help ordering is probably appreciated -- the other two sale dates are 19-Nov 2pm utc, and 25-Nov 9am utc, so ping me whoever wants to help pressing F5

**Comment by RichardLitt** [comment]
Added that date to my calendar. Let's do this.

**Comment by ribasushi** [comment]
@lgierth and others: I have an outstanding order for **2** tickets, in `payment pending` state, with payment of **EUR200** due by **Nov 17th**. Apparently the folks I got the tickets for got them elsewhere, so if you are interested: email me or dm me on twitter or whatever works for you.

Cheers

**Comment by ribasushi** [comment]
>  I have an outstanding order for 2 tickets...

Preorder email forwarded to @watson, which leaves me with no spare tickets. See you all after xmas!

**Comment by ribasushi** [comment]
https://botbot.me/freenode/ipfs/2016-11-19/?msg=76734709&page=6

Ouch :/

So how many tickets are missing still? People could help still at the last sale you know...

**Comment by lgierth** [comment]
Thanks @ribasushi!

Unfortunately we don't have any tickets yet for anyone in the IPFS team. We'll talk about how to proceed tomorrow in the sprint calls.

**Comment by diasdavid** [comment]
Let's organise so that we can all be at the same time trying to buy tickets when the next batch is released, we now know there is a limit of 2 max per person, @lgierth can't buy them all at once.

@lgierth when is the next batch released?

**Comment by ribasushi** [comment]
Next (and **LAST(!)**) batch happens [this Friday 10am Berlin time](https://tickets.events.ccc.de/33c3/). It would really help to know how many tickets are needed, as over-purchasing would be a shit-thing to do, especially given this is the last round.

@lgierth please get an actual count, then folks can report back here as soon as they have secured the pair they were trying to nab.

**Comment by watson** [comment]
I'll be online trying to get more tickets and I'll see if I can recruit others to do the same. How many do we need?

**Comment by hsanjuan** [comment]
I don't think there will be a problem re-colocating tickets if we have too many. Everyone just try to buy 2.

**Comment by diasdavid** [comment]
To make the process faster and increase our chances of success, @watson made some very good questions, namely:

- Which will be the information required for the form? Getting that ready in advance for C&P will make things easier
- How do they check that we are reaching the ticket limit per person? Is it through Credit Card number?
- Do they only accept Credit Card? What about PayPal or Bitcoin?
- Do we have the exact URL for the purchase?

@lgierth do you have answers for these questions?

**Comment by ribasushi** [comment]
@diasdavid During the **first** round (when I got tickets for myself and subsequently @watson ) all that was needed was a working email address. The payment / info / etc is all taking place asynchronously (one has 7 days to pay).

I am not sure if the current last round will require payment on the spot, but given the strong preference for bank transfers, I don't see how instant-pay is possible anyway.

**Comment by pawal** [comment]
@ribasushi @diasdavid I have never payed directly online for a congress ticket, only with bank transfers. During the voucher sales the process was exactly the same as for previous years, and I have no reason to believe they have changed anything.

As for the other payment methods, from the FAQ:
> We accept wire transfers to our German bank account and credit cards via Stripe. Unfortunately we cannot accept any other form of payment like checks, bitcoin or cash.

**Comment by feross** [comment]
I decided I can't make it anymore. See you guys at CCC 2017!

**Comment by watson** [comment]
Ok, so probably you just need a working e-mail address. Maybe they track your session as well, but it does sound like you could order multiple sets of 2x tickets if you run different browsers and enter different e-mail addresses.

And since it sounds like we don't have to pay up front, we shouldn't have to worry about ordering too many tickets either. So let's just get as much as we can 😃

**Comment by RichardLitt** [comment]
@feross You do you. You'll be missed!

**Comment by ralphtheninja** [comment]
> I decided I can't make it anymore. See you guys at CCC 2017!

Same here. See you in 2017 :)

**Comment by ribasushi** [comment]
> And since it sounds like we don't have to pay up front, we shouldn't have to worry about ordering too many tickets either. So let's just get as much as we can :smiley:

@watson That would be a rather shitty thing to do, as it would lock out those who want to go, but couldn't manage the queue: after all tickets **are** limited (due to venue capacity).

This is why I kept asking @lgierth how many tickets are roughly still missing...

**Comment by diasdavid** [comment]
> And since it sounds like we don't have to pay up front, we shouldn't have to worry about ordering too many tickets either. So let's just get as much as we can 

Probably that is what is already happening, someone is locking all the tickets.

**Comment by watson** [comment]
@ribasushi I agree, I'm not saying we should just get 50 tickets, but it's gonna be hard to coordinate. We don't know who of us gets through the queue, so if we need 10 tickets and end up getting 14 because we're "too lucky", I imagine we could just release the 4 back into the queue afterwards.

**Comment by watson** [comment]
And of course, it would be nice to have a ballpark figure of how many tickets we'd like to get 😃

**Comment by hsanjuan** [comment]
@watson 20-25 should be a safe ballpark.

**Comment by watson** [comment]
Does anyone know what link to use when the tickets go on sale?

**Comment by lgierth** [comment]
> 20-25 should be a safe ballpark.
more like 15.

**Comment by watson** [comment]
Anyone found out which website to use?

**Comment by lgierth** [comment]
https://tickets.events.ccc.de/33c3/

Also make sure to not get the cheapest tickets -- see you at 9am UTC :)

**Comment by lgierth** [comment]
![33c3 tickets](https://pbs.twimg.com/media/CwsGf2JXEAA_iUt.jpg:large)

**Comment by watson** [comment]
We're going for the 100 EUR tickets right?

**Comment by VictorBjelkholm** [comment]
@watson yes :)

**Comment by ribasushi** [comment]
In case sufficient amount of folks are going to organize a table - please post info here: inquiring minds want to know.

If tickets are still missing [there is this final option](https://events.ccc.de/congress/2016/wiki/TicketExchange). I personally did manage to get a couple last year on Dec 24th(!) through this exchange (requires much attention though, whenever someone posts "I have a few" they get 100 emails the next minute).

Good luck!

**Comment by diasdavid** [comment]
Hope to see you all at this year's CCC :)
