### ISSUE TITLE
Get #ipfs featured on botbot.me

### ISSUE THREAD

**Issue by lgierth** [ipfs/community#181]
There's a list of featured channels on https://botbot.me/, which we use for public logging of #ipfs.

**Comment by VictorBjelkholm** [comment]
Maybe if we ask nicely to @bartTC, @ipmb or @yml, they could add #ipfs to the featured list

**Comment by ipmb** [comment]
👍

**Comment by VictorBjelkholm** [comment]
Thanks a bunch @ipmb! 💯
