### ISSUE TITLE
Add 2016 Events to README

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#182]
Self explanatory. Assigning to myself. :)

**Comment by diasdavid** [comment]
2017 :) 🍾

**Comment by RichardLitt** [comment]
Removed the events calendar from the README, anyway.

**Comment by diasdavid** [comment]
yeah, it would be good to get the habit of github hygiene, so that we keep all of these tasks and ideas in check.

**Comment by RichardLitt** [comment]
@diasdavid Not sure how that's relevant. Do you mean closing old issues? :)
