### ISSUE TITLE
Involve more people in the community in the release cycle, trying and testing out new features

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/community#183]
We want to give a voice to the fact that we are giving a lot of thought to community process. From decision making process, to engagement in sprint calls we want to improve and get better.

This is the place to discuss anything related to this. 
## 

This is issue was opened in reference to the sprint call on 10/10  https://github.com/ipfs/pm/issues/217

**Comment by RichardLitt** [comment]
Thanks, @dignifiedquire. Can you give a bit more context? Is this an issue to log complaints, or pain points, or to track notes in docs about how to join in?

**Comment by dignifiedquire** [comment]
The main goal for now is to figure out how we can improve the feedback cycle with the community, such that it feeds better into the decisions we make on a day to day basis. 

I think @diasdavid has some more  notes on what exactly he wants to see here happening as well.
