### ISSUE TITLE
London IPFS Meetup

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#189]
Sounds like lots of people in the UK are using IPFS. Let's put together a London IPFS Meetup! If we do it in January 2017 @flyingzumwalt could attend. @edsilv and @irv might you be interested in helping with this? Who else is interested? Who would want to know about this?

If you're interested in this, please chime in on this issue so we know to keep you up to date.

**Comment by RichardLitt** [comment]
There was one of these before, too: See #107. We should post in that issue (or close it, and redirect traffic here), and ping the [London Meetup Group](http://www.meetup.com/IPFS-London-Meetup/).

**Comment by flyingzumwalt** [comment]
Closing this one and redirecting to #107
