### ISSUE TITLE
Try out discourse.org for Community Forums

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#190]
Following up from the discussion here: https://github.com/ipfs/community/issues/69#issuecomment-255583867
- Look into what would be involved in using discourse.org for IPFS community forums.
- Do a trial run -- be careful to minimize confusion in the community during this trial
- Identify benefits & tradeoffs 
- Decide whether to officially adopt discourse.org
- Update documentation, etc. accordingly

cc @RichardLitt

**Comment by flyingzumwalt** [comment]
@erlend-sh can you help me set up a trial run? Would you be willing to join a call with IPFS maintainers to talk about the possibility of using discourse.org for ipfs community?

**Comment by erlend-sh** [comment]
Sure! Just sign up on [the form here](http://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/).

I *might* be able to join a call this week if we manage to schedule something for Wednesday or Thursday. I'm in GMT+1. Find my email on my profile and get in touch!

**Comment by flyingzumwalt** [comment]
Who wants to help us configure discourse and try it out?  
Who is interested in being moderators?
What content should we set up as "seed" data to give this a trial run?

The trial site is up at http://ipfs.trydiscourse.com/

**Comment by dignifiedquire** [comment]
I'm going to be around and try my best :)

**Comment by donothesitate** [comment]
I might put a hand or so in it, not all time though.  I would like a category in-between commoners and moderators. Moderators give impression that they directly represent IPFS.
As for seed, there should be definitely some categories to keep stuff organized:
- Help
- How-To

(To be revised when I have more ideas)

**Comment by dignifiedquire** [comment]
Just added some categories, now seeing your post @donothesitate :)

I have most of them, except for `coding`. I am not sure we want that category as we still want bug reports etc to go to github.

**Comment by dignifiedquire** [comment]
@RichardLitt let's sync up when you are around on what important things we should copy/link into there as you have the best overview of currently existing content.

**Comment by flyingzumwalt** [comment]
We hit the limit of 5 "staff" right away. I emailed @erlend-sh to clarify about this. Here's his helpful explanation (I probably should have just asked him on here!): 

> Moderators also count as staff, yes. All standard plans are limited to 5 staff. It's usually not a problem, but I made an exception for you and doubled it to 10, hope that will suffice!

**Comment by pyhedgehog** [comment]
ipfs.trydiscourse.com has following disadvantages:
 1. It doesn't support anonymous posting/commenting.
 2. It doesn't support https, so it's unreasonable to send email there to register.
 3. Anonymous emails (i.e. mailinator) not allowed.

It's vicious circle.

**Comment by flyingzumwalt** [comment]
@erlend-sh is it possible to enable https? How about anonymous posts?

There are pros and cons to anonymous posts, but it would be nice to have the option of enabling it.

Note: we will still use IRC, so there is still a path for communicating with the maintainers and the community anonymously.

**Comment by hsanjuan** [comment]
I've seen a few discourses under https. Maybe trydiscourse.com does not offer that option though because it's just a testing site. As a side note, github does not allow anonymous posting either so it's pretty much the same on that front.

**Comment by pyhedgehog** [comment]
Github doesn't leak user emsils via http.

**Comment by erlend-sh** [comment]
> is it possible to enable https?

Yes, if you start using your own domain we can set that up for you.

> How about anonymous posts?

Yes. To enable it search for `allow anonymous posting` in your admin panel. Of course, [for true anonymity you have to take additional precautions](https://meta.discourse.org/t/options-for-truer-anonimity/51259/2?u=erlend_sh).

p.s. I'm signed up to your forum and will be easier to reach through a mention or PM there; I check my email/Discourse notifications more frequently than GitHub.

**Comment by flyingzumwalt** [comment]
We've finished the Trial (fwiw). Time to decide how to proceed.

Redirecting all "whether to pull the trigger" discussion to ipfs/community#69 so we can close out that long-running issue. Tracking the follow-up work based on those conclusions in https://github.com/ipfs/docs/issues/7
