### ISSUE TITLE
Watch the IPFSChan effort & Identify any Points of Pain for IPFS Implementations Like Theirs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#192]
The notes on https://pad.riseup.net/p/judgement-day include a thorough technical assessment of what it would take to build a 4chan clone on IPFS (at the moment the IPFS notes start on line 98).

These notes are a great reference document for seeing what it takes to implement IPFS on a large scale. We should use this as an opportunity to clarify our understanding of the "critical path" for  IPFS adopters and to identify any
- points of pain
- ways to make the experience more rewarding for adopters
- missing documentation
- factors that motivate people to use IPFS instead of other protocols/technologies

**Comment by lgierth** [comment]
text mirror: https://ipfs.io/ipfs/Qmeaod9hstM7ni13GFxrc4oWZMKpMnT9eJotpusPNqBHWk

**Comment by VictorBjelkholm** [comment]
Is there any more associated material for this? An 4chan thread or something, or where this initially comes from?
