### ISSUE TITLE
FOSDEM 2017

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#194]
![image](https://cloud.githubusercontent.com/assets/1211152/19884530/058aed74-a012-11e6-9828-e57c78644672.png)

**Who is going to FOSDEM next year?**

I personally love FOSDEM, it is huge, a massive crowd, but it has tracks with content that you don't see in most conferences. You can see the panoply of tracks available at: https://fosdem.org/2017/schedule/

**Comment by RichardLitt** [comment]
I could go! Would probably have to stay in Europe after CCC.

**Comment by VictorBjelkholm** [comment]
I've never been but only heard good things about FOSDEM but all the tracks are empty at this moment so hard to judge if worth going (for the talks at least).

**Comment by xicombd** [comment]
I'm in 🎉

**Comment by diasdavid** [comment]
@ara4n will be also attending FOSDEM next year 🎉🎉🎉

**Comment by diasdavid** [comment]
@VictorBjelkholm true and it takes a bit for the schedule to be up, nevertheless you can get a feeling, specially for the dedicated tracks like SDR, by looking at last year schedule:

https://archive.fosdem.org/2016/schedule/track/software_defined_radio/

**Comment by diasdavid** [comment]
@sericaia and Pedro are also joining 🎉🎉🎉

**Comment by chriscool** [comment]
Yeah the FOSDEM is great!
This year there is also the Git Merge in Brussels on Feb 2 and 3, so just before the FOSDEM.
I will be at the Git Merge, but unfortunately I will have to leave early on Feb 3 so I will not be able to attend the FOSDEM this year.

**Comment by chriscool** [comment]
http://git-merge.com/

**Comment by chriscool** [comment]
By the way about the Git Merge there is a (unconference style) contributor summit on Feb 2 that is not mentioned on the web site.

**Comment by chriscool** [comment]
Tell me if you want to go to the contributor summit as there is a special code you have to give when you buy a ticket for the Git Merge.

**Comment by chriscool** [comment]
See also: https://public-inbox.org/git/20161205133519.dsjhaptk6ezl63zr@sigill.intra.peff.net/

**Comment by dignifiedquire** [comment]
I will try and join as well :)

**Comment by diasdavid** [comment]
I'll be flying Friday, who will be at FOSDEM this year? :)

**Comment by ara4n** [comment]
matrix will be there en masse - come say hi!

**Comment by lgierth** [comment]
Did a meetup happen?

**Comment by diasdavid** [comment]
Not a formal meetup, but we did all meet :)

**Comment by diasdavid** [comment]
Hi everyone that subscribed to this issue, are you planning on going to FOSDEM in 2018? Follow up on the new issue https://github.com/ipfs/community/issues/271
