### ISSUE TITLE
Propose Demos for Weekly All-Hands Here!

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#195]
We've allocated time for Demos on the Weekly All-Hands call. What should be showcased there? Who should we invite to give demos? 

Add comments here if you have ideas, or if you would like to give a demo.

**Comment by flyingzumwalt** [comment]
Should we invite people from [awesome-ipfs](https://github.com/ipfs/awesome-ipfs)?

**Comment by VictorBjelkholm** [comment]
Feels like this should be a little bit tied to awesome-ipfs. At least we can invite the people who create stuff that goes into the list to talk about their own thing. 

Also, people from the things mentioned here: https://github.com/ipfs/awesome-ipfs/issues/65

**Comment by RichardLitt** [comment]
I would love to see the IPFS Pics people come and talk about their work. Also, I would like to know more about Mesh networks and if they use IPFS at all (@lgierth?).

**Comment by VictorBjelkholm** [comment]
Yeah, maybe @cloutier is interested in participating next Monday calls to talk about IPFS Pics?

**Comment by diasdavid** [comment]
# Last week, July 3, 2017 we had:

- IIIF Annotations over IPFS - https://www.youtube.com/watch?v=hmAniA6g9D0&feature=youtu.be&t=10m40s
- Ethereum over IPFS - https://www.youtube.com/watch?v=hmAniA6g9D0&feature=youtu.be&t=35m42s

🎉
