### ISSUE TITLE
Should we use a different collaborative note-taking tool than Etherpads? 

### ISSUE THREAD

**Issue by keks** [ipfs/community#196]
This just came up in the all-hands call.

Etherpads have been the go to solution for collaborative notetaking, but there reasons we might want to have some other solution.
1. Formatting. Instead of saying "This is heading 1" you can only say "This is bold and underlined". This does not represent semantics very well.
2. It's centralized. I mean, c'mon. Seriously?

Let's discuss our options!

**Comment by keks** [comment]
@dignifiedquire mentioned [ipfsbin](http://ipfsbin.xyz). Obviously it wins at point 2, but it also doesn't give us strong formatting. Also it does not allow etherpad-like live collaborative editing.

@flyingzumwalt said he used [Confluence] before, which let's you choose between a WYSIWYG and some markup language. This one has good formatting but is also centralized and can not do etherpad-like collaborative editing.

I mentioned [HackMD], which gives you Markdown formatting (no WYSIWYG, though it gives you a live view of what you type) and has etherpad-like formatting.

Finally I guess the solution we all want runs on IPFS. Since etherpad-like systems afaik usually use CRDTs, maybe this is another use case for OrbitDB? Does our solution *need* to be live collaborative? 

[Confluence]: https://www.atlassian.com/software/confluence
[HackMD]: https://hackmd.io/

**Comment by VictorBjelkholm** [comment]
I think the feature of etherpad is really nice, that you can (if you want) collaboratively work on them together and at least see the changes live together.

I think our current solution is not that bad actually, to write the notes during the meeting in etherpad over at mozilla.org and the paste it into Github so we can keep it in SCM. Is there a reason this doesn't work anymore?

Formatting issues are more about how you write the notes or how you format them before pasting them into SCM, rather than about the platform itself.

**Comment by lgierth** [comment]
Gonna suggest https://cryptpad.fr

**Comment by dignifiedquire** [comment]
HackMD looks to  me to have everything we like on etherpads, but with a nicer UI

**Comment by flyingzumwalt** [comment]
I just want to clarify that the discussion here is not about where to publish notes. It's about what tool to use to take the notes collaboratively in real time while meetings are happening.

We _Publish_ notes for all meetings here: https://github.com/ipfs/pm/tree/master/meeting-notes

Currently we write those notes in etherpad and then the notetaker is responsible for posting those notes to github as a markdown file in a Pull Request.

**Comment by VictorBjelkholm** [comment]
> what tool to use to take the notes

Before we discuss what tool to use, can we agree that what tool we're using now is actually not good-enough? Formatting is a thing no tool will automagically will fix for us.

**Comment by flyingzumwalt** [comment]
HackMD looks great!

Problems with etherpad that I've found painful
* Doesn't render well on mobile devices -- and almost impossible to edit from mobile
* Needs a real-time HTML preview -- this would encourage better formatting and make the notes/agenda easier to read during meetings

HackMD handles both of these really well.

**Comment by keks** [comment]
Thanks for all the feedback! TBH I'm not yet too familiar with the pm workflow, just started joining the calls if I can a few weeks ago and had no idea notes were published on Github and the pads are volatile.
I think HackMD is actually suited much better for our use case because you get a Markdown preview that will look quite similar in Github.

Anyway, I'd love to see both the source code versioning and the project management as apps on IPFS, both for us and other projects. Decentralizing the tools we use to build our software seems like a good idea to me. But that's an entirely different story :)

**Comment by VictorBjelkholm** [comment]
@flyingzumwalt indeed, it does look very good. The mobile point and the live html preview are good points (etherpads non-mobile UI have bitten me before in the past) and after trying it out lightly, I would be happy to try out to use Hackmd instead etherpad for future calls.

**Comment by RichardLitt** [comment]
Hey @keks! Awesome issue, thanks a ton.

### Markdown editing

> Formatting. Instead of saying "This is heading 1" you can only say "This is bold and underlined". This does not represent semantics very well.

I don't understand this. We use Markdown in the text - the only issue is that there isn't a preview. It looks like Cryptpad allows a ton of other options through it's WISYWIG editor. However, these won't port over to GitHub, which is where we generally post our notes. They can be seen using GitHub markdown, both in the issues and through the repo markdown viewer. We use Markdown for historical reasons - we used to put all of the notes in issues - which are now gone, as we have a different workflow. However, having a situation-agnostic syntax is useful, and if the WISYWIG editor doesn't port to markdown, I'd be wary of using it. It doesn't look like it does - do you see an option for that? 

### Centralization

100% agreed it is centralized. However, it doesn't matter all that much for us, I think - we use a few different etherpad instances, and we don't keep the content around longer. We put the pads on GitHub if we're going to save them. What I really think we should do is to host our own instance (see this issue https://github.com/ipfs/pm/issues/230), or to rewrite an etherpad that uses Orbit-DB on the backend. 

### Good enough

I think that Etherpad is good enough, for now. @flyingzumwalt raises really good points about mobile, and about having a markdown rendering. I'd like to use Cryptpad, if it allowed you to use Markdown and not a WISYWIG editor, but again, unless I'm misreading it, that's not an option. We could look for an etherpad-like preview tool? 

We've also had issues with poor internet and etherpads locking up. Another reason to get it on IPFS.  

### Hack.md

So, having written all that -- This is beautiful. Can we try this out on the next IPFS call? :)

**Comment by keks** [comment]
Hey @RichardLitt, thanks for the feedback.

Like I said before, I wasn't aware that the notes are posted on Github after the call. Obviously Markdown does formatting the way I like it, but I like already having the formatting during the call so it's easier for non-notetakers to follow the notes as they are written. I often feel lost when looking at etherpads, but maybe that's just me.

Now that I know that they are being posted to Github after the calls, the centralization idea is kind of void, I agree. I guess it's just a general approach: let's transition our workflow to decentralized apps to show that they are practical. Also using them will make us make them practical. I know this is not a short-term transition though.

re cryptpad: I really like the idea, but it kind of defeats the purpose if you post the keys to decrypt the pad publicly (which we would do). Also I'm not sure an open call like this one needs to be stored encrypted.

> Can we try [HackMD] out on the next IPFS call?

yes please :)

**Comment by RichardLitt** [comment]
> I often feel lost when looking at etherpads, but maybe that's just me.

It's not just you. I think one of the reasons for this is that we tend to split between the notes and the agenda, but that may be a separate topic. 

>  I guess it's just a general approach: let's transition our workflow to decentralized apps to show that they are practical. Also using them will make us make them practical. I know this is not a short-term transition though.

I like this very much. 

Ok. Let's try HackMD this next week.

**Comment by dignifiedquire** [comment]
> Ok. Let's try HackMD this next week.

I would like to suggest https://beta.cryptpad.fr/ Which is made by some cool people and an encrypted version of a collaborative editor.

**Comment by keks** [comment]
Yeah the authors are great people and I love the tool. I've been using it a few times in the last months.
However, I stand by my points that (a) ipfs notes are public and don't require encryption and (b) even if you encrypt everything, this doesn't give you anything if you post the key at untrusted places (like a github issue since that is basically public).

While it doesn't support Markdown preview, there is Markdown syntax highlighting, adding some visual structure.

That being said, I'm open to both editors. It's just that I don't feel like encrypted pads bring much value in this context.

**Comment by VictorBjelkholm** [comment]
@dignifiedquire cryptpad seems to be a wysiwyg rather than markdown editor with preview though. Not sure if that's helpful since we paste the text into Github issues, but maybe it's just me who can't find the edit mode with markdown in cryptpad.

**Comment by lidel** [comment]
@VictorBjelkholm  I was able to create Markdown one under `/code/` version: 
https://beta.cryptpad.fr/code/#/1/edit/JaZJYrbdat9PM5uuefrAEw/LRrI68Xe3oLvAyWVtQSW1We2
There is no preview tho.

**Comment by RichardLitt** [comment]
@haadcode HackMD can be found [here](https://github.com/hackmdio/hackmd). I've prepared this issue text:

> Hey there! We just started hackmd at [ipfs](https://ipfs.io), after having a discussion about moving on from etherpads [here](https://github.com/ipfs/community/issues/196). A few of us were wondering if it might be possible to use IPFS as a backend for HackMD, making it possible to run on a decentralized, distributed internet. 

> Would you be interested in working with us to make this possible? We would love to be able to use HackMD along with IPFS. 

We could also go check out their gitter channel. What do you think? Should I post this?

**Comment by VictorBjelkholm** [comment]
@RichardLitt that sounds good to me! We could also just ping the folks under https://github.com/orgs/hackmdio/people and see if they can leave some input here :)

**Comment by RichardLitt** [comment]
I think that HackMD worked great. Shall we use it for the next sprint, again? 

If people say yes, I think I can go through and update our docs to use HackMD instead of etherpads going forward.

**Comment by em-ly** [comment]
Yes to using it for the next sprint - this is a great tool.

Thanks for the recommendation @keks!!!

**Comment by VictorBjelkholm** [comment]
Since we agreed to use a different tool, let's close this off :) Thanks everyone!

**Comment by jbenet** [comment]
I am so glad we use hackpads now. so much nicer.
