### ISSUE TITLE
Evolution of js-ipfs (Visualization)

### ISSUE THREAD

**Issue by thisconnect** [ipfs/community#200]
Fonud this by accident https://www.youtube.com/watch?v=rfMk1mSobMY

**Comment by diasdavid** [comment]
Pretty cool! :D THank you

**Comment by RichardLitt** [comment]
This is fascinating!

**Comment by diasdavid** [comment]
How easy is to generate these?

**Comment by thisconnect** [comment]
the video mentions Gource Visualization in the title 

https://github.com/acaudwell/Gource

something like this:
```bash
gource --hide dirnames,filenames --seconds-per-day 0.1 --auto-skip-seconds 1 -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.mp4
````
example from: http://www.fullybaked.co.uk/articles/getting-gource-running-on-osx

(I haven't tried this myself)

**Comment by diasdavid** [comment]
@lgierth would you be interested in setting this up for js-ipfs, go-ipfs, js-libp2p and go-libp2p and make them availble through, for example: `gource.ipfs.io/{js-ipfs, go-ipfs, ..}` ?

**Comment by lgierth** [comment]
> @lgierth would you be interested in setting this up for js-ipfs, go-ipfs, js-libp2p and go-libp2p and make them availble through, for example: gource.ipfs.io/{js-ipfs, go-ipfs, ..} ?

Nope not interested :) Gource is just a CLI tool that uses OpenGL for rendering - everything else for making this run in browsers is missing.

I'll happily set up a domain though if someone else makes it work and puts it into ipfs.
