### ISSUE TITLE
Apps on IPFS Call

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#201]
We've recently added the **Apps on IPFS** call back onto the weekly sprint calls on Monday. Nominally, this is about all apps on IPFS - at the moment, however, it is mostly a call for @haadcode to talk about Orbit. 

It would be great if we could make it more than that! So, I have some questions for you: are there other apps on IPFS that you think ought to have a call? Would any other apps on top of IPFS benefit from a weekly or occasional call to help development along? 

In particular, I want to ping: @noffle @fazo96 @whyrusleeping @hydrusnetwork @travisperson @harlantwood @VictorBjelkholm @davidar @mafintosh @cloutier and @dokterbob. 

For more, see: https://github.com/ipfs/pm/issues/253.

**Comment by noffle** [comment]
`ipget` is [very close](https://github.com/ipfs/ipget/issues/18) to a 1.0.0 release. I could talk a bit about that and see if it encourages contributions.

**Comment by pjz** [comment]
I've got a paid IPFS pinning service about ready to beta.

**Comment by RichardLitt** [comment]
@noffle That sounds good to me. Want to add it to the agenda here? https://github.com/ipfs/pm/issues/258

@pjz Would you be interested in talking about it on the ops call, today?

**Comment by pjz** [comment]
Sure; the ops call is at noon EST, correct?

**Comment by RichardLitt** [comment]
The All Hands call is at noon; would be great to have a demo in that call, as we normally open it up for demos after getting through the main agenda items. The Apps on IPFS call is a bit later - 1:30 EST - where it would be awesome for you to ask questions, talk about dev issues, or otherwise contribute. :)

**Comment by pjz** [comment]
I'll try and make one or both, aiming for at least the Apps on IPFS call.

**Comment by noffle** [comment]
@RichardLitt Oops, I wasn't fast enough to see your comment. I'll add myself for next week.

**Comment by RichardLitt** [comment]
No worries! Catch you then.

**Comment by lgierth** [comment]
We've been doing the apps calls regularly for a couple of weeks now
