### ISSUE TITLE
Terminate Greenkeeper

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#205]
I'm going to go directly to the arguments why I believe (and others do too) terminate the Greenkeeper subscription in our repos:

- destroys our Travis-CI execution pool. I've literally waited for more than an hour just to see travis starting to run some tests, this affects both js-ipfs and go-ipfs development as both use the same travis pool for being in the same work
- create a lot of noise in github notifications
- create a lot of noise in the waffle board - I need to spend a ton of time just resolving Greenkeeper stuff.
- I don't believe we have had a single issue where Greenkeeper has saved us from some issue.

**Comment by Kubuxu** [comment]
I know that it is quite valuable for some JS developers. Is there some less "noisy" alternative or separate webui for greenkeeper like app?

**Comment by RichardLitt** [comment]
> I don't believe we have had a single issue where Greenkeeper has saved us from some issue.

How would you know? That's assuming that there would be a breaking issue between the time you commit and the Greenkeeper's PR is merged, right? 

You could always ignore it more. We could also build a bot to automatically remove it's PRs, possible.

**Comment by VictorBjelkholm** [comment]
We should continue this discussion in the issue that is already open: https://github.com/ipfs/community/issues/197
