### ISSUE TITLE
"Help Wanted" Issue

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#21]
Idea.

Many times there's random help I need with things -- e.g. tasks I'm not the best at, that others may be able to or want to help with. This is across repositories (e.g. the blog, or webui, etc). And often people willing to help are not aware of (or following) those repos. 

So, what if we had a `help-wanted` repo (or an issue in this repo), that everyone in the community watches. We can encourage people who want to contribute to watch it. Then, we can post to it about small things (referencing other issues if needed, etc) whenever we need help handling something. 

thoughts @whyrusleeping @cryptix @wking @dylanPowers

**Comment by wking** [comment]
On Sat, May 09, 2015 at 07:00:14AM -0700, Juan Batiz-Benet wrote:
> Many times there's random help I need with things -- e.g. tasks I'm
> not the best at, that others may be able to or want to help
> with. This is across repositories (e.g. the blog, or webui,
> etc). And often people willing to help are not aware of (or
> following) those repos.

Hrm.  “Folks interested in helping IPFS in any of many areas, but not
interested enough to follow a particular area.  And also folks good at
plugging @jbenet gaps” doesn't sound like a nice, cohesive community
to me ;).  I'd suggest folks following via email get good filters in
place to cull out stuff they're not interested in (although it doesn't
look like GitHub sets a header with a list of labels :/), and folks
following via GitHub's web UI just bookmark something like [1].

[1]: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+org%3Aipfs+label%3A%22help+wanted%22

**Comment by jbenet** [comment]
> “Folks interested in helping IPFS in any of many areas, but not
> interested enough to follow a particular area.  And also folks good at
> plugging @jbenet gaps” 

i didn't mean it specific to me-- but rather for everyone. i.e. a common stream for people to drop an issue and say "i need help with X".

there are a lot of repos and most of the time everyone will not be following random repo Z. If we direct people to a _single one to follow_ then we can post links in that one. (irc is working like this for us, but irc has a low SNR, and also there's many more people on github repos than on irc).

> https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+org%3Aipfs+label%3A%22help+wanted%22

Oh nice, that's very useful!

**Comment by diasdavid** [comment]
Woa, didn't know of that view, very cool indeed! What if we start to add a badge to link to a page with Contributing Guidelines and a 'where to start' (issues with help wanted)

**Comment by jbenet** [comment]
@diasdavid +1 for the badge. i think we should make the badge cooler. 

here's one attempt:

![](http://gateway.ipfs.io/ipfs/Qmedj6MNRCoQQxauFz6HZqgExqSQoGdEX2PVjFVnpUcnoR/contribute.gif)

Cyberwizardry!

**Comment by RichardLitt** [comment]
Closing this as we now do this!
