### ISSUE TITLE
NYC IPFS Meetup

### ISSUE THREAD

**Issue by Zanadar** [ipfs/community#210]
I was trawling around the issues and found https://github.com/ipfs/community/issues/186 but was sad to discover that it didn't happen....
So I registered [Meetup group](https://www.meetup.com/IPFS-NYC/) and I'm gonna organize it damnit!

I've scheduled a first date for January 26th, and would like to run a monthly event.

I'd like to have this run more like a seminar than a lecture, with an emphasis on two topics:
1. Studying background material to fill out the groups' knowledge of IPFS concepts
2. Making contributions to the codebase

My hope is that the content and format of monthly meetings can develop organically based on the goals of everyone involved. The idea is that this would be an IPFS focussed group, with room for the larger world of decentralized/p2p applications.

I've got food covered (thanks to my employer ;) but I'm still searching for a location.  I have no idea what attendance will be like, so I haven't quite figured out a venue that makes sense... but watch this space.

**Comment by lgierth** [comment]
cc @meyerscr @nitinics @bhny

**Comment by meyerscr** [comment]
We can probably get access at Hack Manhattan if you would like for it to be public. Otherwise, I know of a couple co-working spaces that have offered things. However, people have to RSVP for those spaces, making them a bit more restricted. 

I will reach out to Hack Manhattan about using their space. In the past, they have accepted donations in lieu of membership.

**Comment by jbenet** [comment]
This sounds great! 👍  :tada: would love to see this happen and would stop by when im in NYC.

would be useful to _distinguish_ this from traditional developer meetups or what we've been calling meetups (usually 2-3 talks, stand up conversations, etc). because i'd love to see major cities with both that kind of meetup, and this kind of meetup. We could call _those_ "small conferences" or something. but perhaps there's a better word for this one that fits well. 

throwing things out there:
- Study group
- IPFS School (like nodeschool)
- Dev Meetup
- Hack night / Hack day
- Learn Meetup

**Comment by jbenet** [comment]
btw we can help promote it and announce it over blog, twitter, etc.

**Comment by RichardLitt** [comment]
> because i'd love to see major cities with both that kind of meetup, and this kind of meetup.

I've seen this more and more. It might be a useful time for a distributed, decentralized meet up group that allows for longer interactions. 

@Zanadar This sounds great. Let me know if you need any help - logos, etc. Regarding the format, @flyingzumwalt is making a decentralized web primer that might be good starting material. See https://github.com/flyingzumwalt/decentralized-web-primer.

**Comment by Zanadar** [comment]
I love the idea of calling this an IPFS school or study group or something like that to differentiate from the "mini-conference" variety of meetups. These names convey the aims well, although I'm not sold on any particular name... will have to think about that.
As for space, thanks @meyerscr for the suggestion of Hack Manhattan; if that can be swung it'd be perfect. I was planning on having this be public, but maybe capping attendance?  But perhaps it will be self limiting given the above description.
And once we get the details settled a little promotion will be awesome thanks @jbenet

**Comment by flyingzumwalt** [comment]
Keep me posted when you nail down the date and location. I'll try to come up from Philadelphia.

**Comment by Zanadar** [comment]
@meyerscr Did you get an answer RE Hack Manhattan? That would be an awesome place for this.

**Comment by nycoliver** [comment]
Any updates?

**Comment by Zanadar** [comment]
As of yet, I'm still casting around for a place to host. I have a couple leads and may end up just booking a conference room at my job, but that's not exactly ideal.

As to the structure, I'm thinking of two groups I would ideally like to support:
1. People working _with_ IPFS -> App developers and the like who build on top of the platform
2. People working _on_ IPFS -> Contributors who want to meet each other in person, collaborate etc.

For the first meeting, I think that running session supporting people to go through https://github.com/flyingzumwalt/decentralized-web-primer serves group 1 and then just providing a space and food so people can meet, talk about what they're working on, and get ideas about what the needs of the group are kind of helps group 2.

**Comment by Zanadar** [comment]
I've gotten too swamped at work and life to organize or seek out a location. If anyone is interested in organizing or taking over the meetup group, be in touch.

**Comment by meyerscr** [comment]
I can take over the meetup group.

**Comment by Zanadar** [comment]
sounds great @meyerscr Send me you email, and I'll pass of the meetup group that I registered to you.

**Comment by meyerscr** [comment]
I sent you an email through your company. I don't have Twitter.

**Comment by Zanadar** [comment]
Didn't get it. Best to use zmackie at gmail do com

**Comment by meyerscr** [comment]
Go ahead and delete that comment.
