### ISSUE TITLE
[Docs] Write Files API Documentation

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#214]
Explore the Files API and write documentation for the Primer.  The most current explanation of the files API is in the discussion here: https://github.com/ipfs/specs/issues/98

cc @RichardLitt

**Comment by flyingzumwalt** [comment]
If people have other reference info to offer, please let me know. cc @diasdavid @whyrusleeping

**Comment by diasdavid** [comment]
Can we just use https://github.com/ipfs/specs/issues/88 to track this? Closing, reopen if you see necessity in having two issues.

**Comment by RichardLitt** [comment]
This isn't about the specs, which is a separate issue, but about documenting it with examples. Much of the work for this is being done in https://github.com/flyingzumwalt/decentralized-web-primer by @flyingzumwalt now, I believe.

**Comment by diasdavid** [comment]
Now on https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md
