### ISSUE TITLE
[Docs] Document the DAG API (which uses IPLD)

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#215]
Explore the DAG API and write documentation for the Primer.  See discussion in  https://github.com/ipfs/specs/issues/98

Also make sure to remove any reference to `ipfs object` in the Primer, since that uses protobuf objects, which are being deprecated.

If people have other reference info to offer, please let me know. cc @nicola @RichardLitt @diasdavid @whyrusleeping 

## Example Audience/Use Cases:

* OpenBazaar adding JSON info to IPFS as IPLD blocks on the DAG

## Reference Info

* https://github.com/ipfs/specs/issues/98
* http://ipld.io

**Comment by diasdavid** [comment]
Documentation: https://github.com/ipfs/interface-ipfs-core/tree/master/API/dag
Examples: https://github.com/ipfs/js-ipfs/tree/master/examples/dag

**Comment by diasdavid** [comment]
//cc @vmx :)

**Comment by diasdavid** [comment]
Documented https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DAG.md, lots of design work happening on https://github.com/ipfs/interface-ipfs-core/issues/81
