### ISSUE TITLE
All Hands "Check Ins"

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#217]
### Syncs

This issue is for discussing whether it is a good idea to spend time each sprint going over what everyone is doing, briefly.

### Background

Last week, @haadcode suggested that we briefly go over what each other are doing in the All Hands call. We hadn't done that in a while, so we all agreed that this was a good idea, and everyone spent a minute saying what they were working on that week. This matched what we used to do in the Sprint syncs. 

This week, @lgierth asked if we should do the same thing again. There was a bit of discussion after this; some saying yea, because it is a nice way to know what others are working on, and others saying nay, largely because this is the purpose of the other calls. The conversation quickly ballooned out of scope, and rather than take up the call, we decided to move it here. 

### Arguments against

- This is the purpose of the other calls. If we all say what we are doing in the All Hands call, then we will have to repeat ourself later. This is not great, and is wasting a lot of resources, at scale.
- We need a space to ‘check in’ on projects that don’t have a space allocated for them.

### Arguments for

- This allows us to sync up as a team, and to know what other, different people are working on. Not all of us go to every call - and we probably shouldn't. This allows us to get the gist of what others are doing, and we can then be better informed to follow up after if needed.
- Sprint issues are empty. It might be a good idea to dump some sprints into All Hands, thus freeing up time at other events. (Conversely, this means that those events may be cancelled at the expense of being able to notify community members who may have planned to make them. Events shouldn't be cancelled on the fly, or in the All Hands, as not all participants are on that call). 

### Other Suggestions

There are a couple of ways we can do this, without leading to time wastage. 

#### Project leads give the update for their teams

This would save time, and make it clear who is working on what and who to ask questions of. (On the other hand, we have _dozens_ of projects, so choosing a meaningful subset may be difficult.) Everyone could give an update on what they were working the previous week, and we could invite members the community to give their updates. We used to do something similar before the sprint process overhaul.

#### Repeat the Sync event once every four weeks

We started this event on the first of the month. It might be a good idea to do it now and then, but not all of the time. That way, we get the benefits of both. 

### Actionable Suggestions or Discussion

Please post your ideas or comments below! Thank you.

**Comment by VictorBjelkholm** [comment]
I like the idea, it's good to get an overview of what's going on around the different efforts.

> This is the purpose of the other calls. If we all say what we are doing in the All Hands call, then we will have to repeat ourself later. This is not great, and is wasting a lot of resources, at scale.

I think, if you're repeating things that would be said in different calls, this would be a waste of time.

But I can see value in having a quick, broad show-and-tell of what people are focused on. In the all-hands, I can mention that I did something on js-ipfs, while in the actual js-ipfs call, go more into details about what/why and what's next. Nothing would be repeated, but we would still learn about what others are doing.

We would need some sort of time limit, something like one minute per person in the "everyone share what they done", to not drag it out too much.

**Comment by Admin-DataRoads** [comment]
> Project leads give the update for their teams.

This suggestion best matches "all hands" and multi-project weekly sync up meetings I have organized at past jobs, along with listing any inter-project dependency blockers. There are a lot of projects here, but there also seems to be a lot of project sets that are being driven by a single developer, so in many of these cases developer-updates and project-lead-updates will be one in the same.

If developer per project count increases to the point where 1-minute per lead updates take up a 30 minute call time alone, moving this to once a month and then allowing it more than 30 minutes makes sense. 

If all the leads write change summaries based on their [project board](https://waffle.io/ipfs?tab=projects) status each Friday, the 1 minute limit should not be reached too often in any Monday call. They should also add this write-up to the agenda _before_ each meeting, to give the notetaker a break and give attendees a preview. Optionally, they can also assign this "all hands update" task to the developer most responsible for project changes in the prior week.

> RichardLitt commented on Dec 12, 2016

This discussion is about a year older than my own involvement, so I'm just speaking to what I usually expect to see in a meeting called "all hands" or "weekly sync ups" in other environments. As of 2018 this kind of project check-in seems to have been abandoned, and I personally would like to see it come back.
