### ISSUE TITLE
Build a registry of apps, projects & orgs using IPFS

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#218]
While awesome-ipfs lists a curated set of stuff that the community has identified as "awesome", we also need a running sense of the whole community -- how many people are out there working on IPFS? What are they building? What organizations do they represent? What needs are they trying to address? Where are they posting their work?

cc @RichardLitt

**Comment by RichardLitt** [comment]
SGTM.

**Comment by diasdavid** [comment]
@mishmosh I know you have been collecting a lot of the uses of IPFS, you might have some thoughts on how to work with the community to organize this information collaboratively :)

**Comment by balupton** [comment]
this can probably be replaced by https://github.com/ipfs/awesome-ipfs

**Comment by RichardLitt** [comment]
@diasdavid I can't seem to unassign myself, but I won't be getting to this in the near future. 

If someone from the community wants to take this, go for it!

**Comment by RichardLitt** [comment]
I can't unassign myself, but I won't be getting to this soon. If anyone wants to take it, go ahead!
