### ISSUE TITLE
@llopv's Master Thesis: Open issues on the P2P Web

### ISSUE THREAD

**Issue by llopv** [ipfs/community#221]
IPFS provides a good starting point for the Permanent Web. In our master’s tesis we are going to discuss how we can construct a Secure Dynamic Permanent Web on the top of it.

Nowadays centralized web services provide users with the following desirable features: mutability (CRUD - create, read, update, and delete data), capabilities (through authentication), computation (such as compute queries on search engines), "global" data (such as hashtags), anonymity (through TOR), confidentiality, integrity (both through SSL), and availability.

We are going to review those features to IPFS current or planned ones, such as content addressing for integrity, `ipfs crypt` for confidentiality, and IPNS and `libp2p/pubsub` for mutability, etc.

**Comment by flyingzumwalt** [comment]
Do you plan to also cover identity on the decentralized web? Example: In order to mark a dataset as authentic, an authoritative person/group/institution might want to sign the hashes and publish the signed hashes. This topic touches a lot of topics & tech outside of IPFS, but it is directly relevant as an issue on the P2P web.

**Comment by llopv** [comment]
Yes, definitely *identity* must be one of those topics. I've seen you are writting some documentation for [decentralized web primer](https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/dynamic-content/index.html). It would be cool if my master's tesis could help to improve that documentation in some way (my writtings are all open access).

**Comment by flyingzumwalt** [comment]
😄 I had the same thought about the primer.

**Comment by diasdavid** [comment]
@llopv mind opening an issue on ipfs/notes? Take example of https://github.com/ipfs/notes/issues/268. Closing this one.
