### ISSUE TITLE
IPFS at Code4Lib 2017

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#223]
At [Code4Lib 2017 in Los Angeles](http://2017.code4lib.org/) there will be an IPFS workshop during the pre-conference and there will be a presentation about IPFS in the main conference.

### Workshop 
[Introduction to IPFS and Distributed Technologies](http://2017.code4lib.org/workshops/Introduction-to-IPFS-and-Distributed-Technologies) 
Presenters: @RichardLitt and @flyingzumwalt

### Presentation
[How the distributed web could bring a new Golden Age for Libraries](http://2017.code4lib.org/talks/How-the-distributed-web-could-bring-a-new-Golden-Age-for-Libraries) 
Presenter: @flyingzumwalt

**Comment by diasdavid** [comment]
@flyingzumwalt could you post the url to the video? Would love to also link it from the IPFS youtube channel.

**Comment by flyingzumwalt** [comment]
here's @flyingzumwalt's presentation: https://youtu.be/xRuPShYelm4?t=3h7m40s

Slides:

PDF: Code4Lib 2017 - Golden Age for Libraries - Storing Data Together.pdf
Keynote: Code4Lib 2017 - Golden Age for Libraries - Storing Data Together.key

The avatars mentioned in the Q&A have been published at https://github.com/ipfs/artwork

**Comment by flyingzumwalt** [comment]
Also @jschell42 made an edit of the video that's just my talk. https://www.dropbox.com/s/fy7tj35450rdmx2/Matt_C4L.mov?dl=0

**Comment by RichardLitt** [comment]
@flyingzumwalt This can probably be closed now. :)
