### ISSUE TITLE
Form a DWebLAM Community?

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#224]
Anyone interested in forming a community around Distributed Web in Libraries, Archives and Museums?

## Related

* IPFS at Code4Lib #233
* https://github.com/ipfs/archives
* Tweets looking for interest: 
  * https://twitter.com/flyingzumwalt/status/812004084756709376
  * https://twitter.com/ennomeijers/status/811517251950145536
* IIIF on IPFS: ([lots of issues](https://github.com/search?q=org%3Aipfs+iiif&type=Issues&utf8=%E2%9C%93)

**Comment by denisnazarov** [comment]
Hey from @mediachain!

Mediachain is a sister project of IPFS (built on top of libp2p).

Mediachain builds upon foundational properties of decentralized/p2p systems (immutability, content-addressing, distributed routing) and adds a decentralized **directory** and the concept of **namespaces** to provide a single port of entry for discovering, publishing and collaborating on media metadata (media assets live in IPFS).

We started a community effort to aggregate and decentralize cultural heritage data [earlier this year](https://github.com/mediachain/apps/tree/master/museums). So far over a million museum works have been aggregated, as well as over 100 million works from Creative Commons image sharing platforms. You can read more about how Mediachain works [here](https://mediachain.github.io/mediachain-docs/).

We'd love to join forces and participate in a DWebLAM community effort!

**Comment by edsilv** [comment]
Hey, I'd love to be involved too. Just to carry on from the Twitter conversation, I've been using riot.im to follow the IPFS IRC and like it as an OSS alternative to slack. Also, big fan of mediachain :-)

**Comment by flyingzumwalt** [comment]
A couple people have suggested doing this on Slack, possibly in the code4lib Slack (as suggested by @cmh2166 [here](https://github.com/ipfs/archives/issues/68#issuecomment-294166467)). I want to do whatever works for the most people. Personally I'm suffering from Slack overload due to the proliferation of Slack teams that I'm obligated to be on.

Would it make sense to try using the new IPFS discourse instance at https://discuss.ipfs.io ?

**Comment by flyingzumwalt** [comment]
related conversation on twitter https://twitter.com/ennomeijers/status/852561763052793856

**Comment by lidel** [comment]
Regarding Slack and open initiatives: https://dave.cheney.net/2017/04/11/why-slack-is-inappropriate-for-open-source-communications 🙃 

I got low key feeling that sub-category in Discourse could improve discovery and cross-pollination.

**Comment by flyingzumwalt** [comment]
I've created a "Libraries Archives and Museums" category on discuss.ipfs.io and opened a thread asking [Who's using IPFS in Libraries Archives and Museums](https://discuss.ipfs.io/t/whos-using-ipfs-in-libraries-archives-and-museums/130). I hope you'll all chime in with info, ideas, links and requests for collaborators!

**Comment by cmh2166** [comment]
thanks, @lidel !

fwiw, i'm not trying to be a slack apologist here. just wanting some sort of communication coordination for the various threads (some not getting picked up by others) and communication methods already presented.

**Comment by flyingzumwalt** [comment]
This conversation moved to https://discuss.ipfs.io/t/community-ipfs-in-libraries-archives-and-museums/130

We have had 2 GLAM community calls so far.
