### ISSUE TITLE
Update JavaScript community guidelines

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#225]
- [ ] Make sure it is up to date and that it incorporate the last week's discussion notes

@RichardLitt tagging you as you volunteered

**Comment by RichardLitt** [comment]
SGTM.

**Comment by diasdavid** [comment]
Could you provide an ETA? I believe this is going to be super valuable to kick off the quarter :)

**Comment by RichardLitt** [comment]
@diasdavid Tomorrow? Whenever this is merged? :)

**Comment by diasdavid** [comment]
List of things to be done:

- [ ] Merge https://github.com/ipfs/community/blob/master/js-commit-guidelines.md and https://github.com/ipfs/community/blob/master/js-project-guidelines.md to a single document
- [ ] List out every package in js-ipfs and js-libp2p main repo that those modules use (created by us) and add a column with their main Captain
- [ ] Add a section how modules should provide docs with jsdoc (referencing the awesome documentation endeavour)
- [ ] https://github.com/ipfs/community/blob/master/js-project-guidelines.md#linting--code-style should explain that `aegir-lint` checks for all the linting
- [ ] https://github.com/ipfs/community/blob/master/js-project-guidelines.md#building is completely out of date
- [ ] It would be great to have a section for the badges that we always put in every repo
- [ ] There should be no dependencies that rely in commits, instead there should be WIP PR and each PR that depends in other WIP PR should list what it depends too and yes, everyone will have to do the extra work of npm link everything, but that is what avoids most problems
- [ ] Have a clause that every module below 1.0.0 should use`~` instead of `^`. Submit PR to change all of these in all the modules
- [ ] update the .*ignore examples https://github.com/ipfs/community/blob/master/js-project-guidelines.md#gitignore

**Comment by RichardLitt** [comment]
> List out every package in js-ipfs and js-libp2p main repo that those modules use (created by us) and add a column with their main Captain

Which modules? Can we use project-repos for this?

**Comment by RichardLitt** [comment]
> - [ ] Add a section how modules should provide docs with jsdoc (referencing the awesome documentation endeavour)
> - [ ]  https://github.com/ipfs/community/blob/master/js-project-guidelines.md#linting--code-style should explain that aegir-lint checks for all the linting
> - [ ]  https://github.com/ipfs/community/blob/master/js-project-guidelines.md#building is completely out of date

@dignifiedquire Can you help with this? I think you'd be the best at it. 

@diasdavid:

> There should be no dependencies that rely in commits, instead there should be WIP PR and each PR that depends in other WIP PR should list what it depends too and yes, everyone will have to do the extra work of npm link everything, but that is what avoids most problems
>  Have a clause that every module below 1.0.0 should use~ instead of ^. Submit PR to change all of these in all the modules
>  update the .*ignore examples https://github.com/ipfs/community/blob/master/js-project-guidelines.md#gitignore

Can you please point to where these decisions were made? They seem extemporaneous to me.

**Comment by diasdavid** [comment]
Apologies if it wasn't clear enough, @dignifiedquire @haadcode @VictorBjelkholm could you confirm with what you understood? Sad that we didn't take digital collaborative notes.

I remember describing the problem (3 times at least) during the discussions of 2 weeks ago and also described how we, within the js-ipfs and js-libp2p development, solve it, which is what I'm describing in that paragraph. At the time of the group focused discussion (in person), I asked if everyone understand the issue and is down to make this a commitment, I received positive feedback.

**Comment by diasdavid** [comment]
https://github.com/ipfs/community/issues/225#issuecomment-273251557

here:
- https://github.com/ipfs/js-ipfs#packages
- https://github.com/libp2p/js-libp2p#packages

**Comment by RichardLitt** [comment]
@diasdavid Why don't I just do all of the changes to the documentation you suggest, and then we can hash out in the PR if there are any difficulties? Will make it easier.

**Comment by diasdavid** [comment]
@RichardLitt that sounds good to me :)

**Comment by diasdavid** [comment]
@RichardLitt we really need some of these things urgently, starting with the shift from `^` to `~` while we are still pre-1.0.0, a lot of people have troubles with this. //cc @nicola

**Comment by RichardLitt** [comment]
@diasdavid Thank you for bringing that up. I'll highlight this on my list, and get to it in the next few days.

**Comment by RichardLitt** [comment]
> List out every package in js-ipfs and js-libp2p main repo that those modules use (created by us) and add a column with their main Captain

This should be done with [project-repos](https://github.com/ipfs/project-repos), I think. Or, at least, the captains should be noted there. Why did you think this would be useful?

**Comment by RichardLitt** [comment]
> There should be no dependencies that rely in commits, instead there should be WIP PR and each PR that depends in other WIP PR should list what it depends too and yes, everyone will have to do the extra work of npm link everything, but that is what avoids most problems

I don't feel like this is organic or coming from the team; it looks like it is you, @diasdavid, saying this (as you can tell from your explaining how it will help and yes it is hard). I don't want to open a PR for this, because I don't think it has been discussed enough. Can you point me to the issue you make // have made on this?

**Comment by RichardLitt** [comment]
> update the .*ignore examples https://github.com/ipfs/community/blob/master/js-project-guidelines.md#gitignore

@diasdavid Can you point me to a better one, or PR that?

**Comment by RichardLitt** [comment]
> Have a clause that every module below 1.0.0 should use~ instead of ^. Submit PR to change all of these in all the modules

Is this for js-ipfs, all js- modules, or just all modules in general in the `package.json`? Can you show me an example of a working `package.json` file you like?

**Comment by diasdavid** [comment]
@RichardLitt all of the items that I listed above were discussed during the gathering and agreed upon, nevertheless, to clarify:

> re: https://github.com/ipfs/community/issues/225#issuecomment-278114300

project-repos might also be also a place for this information to live, however, it wasn't what we came out from the roundtable as an action item. 

> re: https://github.com/ipfs/community/issues/225#issuecomment-278120398

It is actually the other way around, organically we have been doing the WIP PR across js-ipfs and js-libp2p module ecosystem, it was a thing that me, @dignifiedquire and other contributors have adopted organically, however, since it was never claimed as being part of the process, other users of the project, i.e @haadcode with Orbit, used commits to install module dependencies and had major issues because of that (i.e September).

This was brought up several times during lab week and as far as I can tell, the people that were at the JS round table agreed that we should limit ourselves and do WIP PR, so it is explicit which WIP branches depend on which WIP branch.

> re: https://github.com/ipfs/community/issues/225#issuecomment-278120570

Absolutely, every single `js-` repo share their .npmignore and .gitignore, the templates were never updated, see https://github.com/ipfs/js-ipfs as a good example (although all the other repos will contain the same)

> re: https://github.com/ipfs/community/issues/225#issuecomment-278120782

This is just for our own module dependencies.

Hope this helps, let me know if any other questions. Thank you :)

**Comment by RichardLitt** [comment]
### List all Js repos

Thee are 1871 dependencies for js-ipfs. Should I just list all ipfs/js-* and libp2p/js-* repos and leave it at that? Or ought I to be doing some more intelligent test? 

### Dependencies on commits

Opening a PR now. 

### .gitignore

looks like @diasdavid is getting it. 

### Tilde clause

Creating a PR now.

**Comment by diasdavid** [comment]
![image](https://cloud.githubusercontent.com/assets/1211152/22839363/ec75dc20-ef7d-11e6-82aa-1fca5a8a3604.png)

I handled switching ^ to ~

-------

![image](https://cloud.githubusercontent.com/assets/1211152/22839372/fa86d95e-ef7d-11e6-9c86-3353b850f118.png)

Note my note above "created by us". I meant completing these tables:

- https://github.com/ipfs/js-ipfs#packages
- https://github.com/libp2p/js-libp2p#packages

And adding an extra column to identify the 'Lieutenant' for that package.

**Comment by RichardLitt** [comment]
Sorry, I was not clear enough. I am not the best person to know what extra modules are created by us which are relevant. Someone who is more familiar with the actual ecosystem should be doing this.

**Comment by diasdavid** [comment]
continuation of this work is on #253
