### ISSUE TITLE
Is there any stats on IPFS network?

### ISSUE THREAD

**Issue by xhipster** [ipfs/community#227]
I am curious is there a site with stats about IPFS node network? Like [Bitnodes](https://bitnodes.21.co/) or [Ethernodes](https://www.ethernodes.org/network/1)?
- clients
- version
- locations

I know that my web console shows locations of nodes. But that seems that this is only about my peers. I'd like to see network wide stats.

Also it would be interesting to know how much information the network stores?
- unique files
- volume of unique files

I didn't find how to easy query this stats from daemon.

**Comment by 21xhipster** [comment]
After some research I found out that storage stats is impossible to know.

**Comment by Kubuxu** [comment]
It would be possible, just we haven't focused on it yet,
One could try crawling the DHT or DHT announcements, but then you would have to differentiate for between files, file chunks and directories.

**Comment by lanzafame** [comment]
//cc @olizilla
