### ISSUE TITLE
How do we help each other take better notes?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#230]
Now that we are switching to a model for our sprint calls where everyone is expected at some point to take notes, we should think about how we want to help people level up their note-taking skills. Rather than just dropping new notetakers in the deep end, let's source ways to help others take better notes, here.

**Comment by RichardLitt** [comment]
@diasdavid You mentioned [minutes.io](https://minutes.io/welcome). Can you tell us more about it?

**Comment by diasdavid** [comment]
I recommend watching https://www.youtube.com/watch?v=8gRVckc_IkA, minutes.io is the culmination of already some good research on how to take good meeting notes.

**Comment by diasdavid** [comment]
btw, shouldn't this be in `pm`? What are the next actions from here?

**Comment by RichardLitt** [comment]
It could be in either; `pm` might have been better. 

@flyingzumwalt You were the one who brought this up, IIRC. Can you help explain a bit more what you were hoping for?

**Comment by flyingzumwalt** [comment]
I didn't have specific ideas. I just wanted to source people's ideas for how to help each other take good notes. fwiw I'd say this belongs in ipfs/pm but there's not much point in moving it.

**Comment by diasdavid** [comment]
Also tracked in the `pm` repo https://github.com/ipfs/pm/issues/493. Closing this one
