### ISSUE TITLE
CCC and Battlemesh Trip

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#24]
Many people in the IPFS community are going to CCC and Battlemesh in August 2015. This issue is for coordinating plans.

(We will likely overlap / travel along with our node and CJDNS friends)

**Comment by diasdavid** [comment]
The majority of the discussion and folks are on this thread - https://github.com/nodeschool/discussions/issues/353#issuecomment-117156920

**Comment by jbenet** [comment]
confirmed going to CCC: @jbenet @diasdavid @lgierth @krl @kyledrake @mappum @mafintosh @maxogden -- anyone else want to join us? (@mafintosh @maxogden coming to battlemesh?)

**Comment by diasdavid** [comment]
Also, to have in mind, we should propose some IPFS sessions for [Open Code Town tent](https://events.ccc.de/camp/2015/wiki/Village:OpenCodeTown)

**Comment by diasdavid** [comment]
🚀
