### ISSUE TITLE
contribute.md for each repository

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#241]
It was brought up today in the All Hands call (ipfs/pm#243) that we could have a Contribute.md in each repository. As we already have a contribute section in every repo, as outlined by Standard Readme, this wouldn't be too much of an extra step, and it would flag everyone opening an issue or a PR on an IPFS repository to check the contributor guidelines. It could also hold a section for tests. 

I think this is a good idea. What do you think?

**Comment by dignifiedquire** [comment]
This is a pretty awesome example of a contributing file: https://github.com/zkat/pacote/blob/latest/CONTRIBUTING.md

**Comment by RichardLitt** [comment]
@dignifiedquire What do you think we could take from that?

**Comment by VictorBjelkholm** [comment]
I think the CONTRIBUTING.md @dignifiedquire linked is a very good example. Has a nice table of contents with many ideas on how people contribute, with links to each section explaining more. Seems to have come from this generator: https://www.npmjs.com/package/weallcontribute

**Comment by diasdavid** [comment]
Do we want a CONTRIBUTING.md per repo, or a main one to all repos that is linked from a CONTRIBUTING.md in every repo (so that Github reminds contributors to check it) ?

**Comment by dignifiedquire** [comment]
I think ideally we have the same file in every repo and a tool to sync it from a master file

**Comment by RichardLitt** [comment]
That'll quickly dirty up the git history. Might be better to have a CONTRIBUTING.md in each repo that just links to a central one. You can repurpose the Contribute section of the README to point to the main one, too.

**Comment by diasdavid** [comment]
Yeah, that's what I did here: https://github.com/libp2p/js-libp2p/blob/master/CONTRIBUTING.md

Looks good?

**Comment by RichardLitt** [comment]
LGTM.

**Comment by diasdavid** [comment]
moved to https://github.com/ipfs/testing/issues/48
