### ISSUE TITLE
Community Zoom Account

### ISSUE THREAD

**Issue by lgierth** [ipfs/community#245]
We've usually created meeting rooms using the Protocol Labs Zoom account -- it would be useful to have an account for the community that we can hand out to people that need to create meeting rooms, e.g. @sidharder.

**Comment by diasdavid** [comment]
@momack2 fixed this by creating 3 community accounts aaand creating a fantastic tutorial https://github.com/ipfs/pm/blob/master/HOST_A_CALL.md ❤️
