### ISSUE TITLE
Set up official IPFS forums site

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#250]
For background see https://github.com/ipfs/community/blob/master/decisions/community-forum-platform.md#decision The final proposal was titled **Use Discourse for All Community Support**. It was posted on https://www.loomio.org/d/imMrpwRF, specifying:

1. [x] Name a DRI for the rollover to Discourse and for ongoing management of Discourse @flyingzumwalt
2. [x] Set up discourse at discuss.ipfs.io subdomain #251
3. [ ] Recruit a group of moderators from community and get them set up with appropriate moderator powers
6. [ ] Use https://www.discourse.org/github to migrate the existing content from ipfs/community, ipfs/faq and ipfs/support to discourse and update the github repos to clearly redirect people to discuss.ipfs.io
7. [ ] Update ipfs/ipfs README to list discuss.ipfs.io as the main place to seek support
8. [ ] configure discourse to support posting via email (#255)
9. [ ] Announce our new discourse forum on IRC and on the mailing list

Ensure that:
- [x] https support is enabled
- [x] anonymous posting is enabled
- [x] people are able to interact with our discourse install as if it was an email mailing list

After a 3-month trial:

1. [ ] Decommission the google group, redirecting all mailing list users to subscribe to discourse in mailing list mode
2. [ ] Consider archiving ipfs/support, ipfs/faq and/or ipfs/community if they are no longer useful.

**Comment by VictorBjelkholm** [comment]
@flyingzumwalt the self-hosted instance is now up and running and content from our demo-instance has been migrated.

**Comment by diasdavid** [comment]
This has been done :) 🎉 good work everyone!

# => https://discuss.ipfs.io
