### ISSUE TITLE
Set up self-hosted discourse at discuss.ipfs.io

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#251]
This is part of #250

Tasks:
- [x] Deploy a copy of discourse 
- [x] Setup mailing with Mailgun
- [x] Configure discourse to support mailing list mode
- [x] Migrate Github Application to @ipfsbot
- [x] Set up discourse to handle https
- [x] Migrate theming
- [x] Create discuss.ipfs.io DNS entry that points to the discourse instance
- [x] Redirect ipfs.trydiscourse.com to discuss.ipfs.io

## Reference/Technical Instructions

You can run discourse using the [discourse_docker](https://github.com/discourse/discourse_docker) docker image. There are [Instructions for deploying the docker image on a hosted service like Digital Ocean](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md).

You can also [pay this guy $99 to set it up for you](https://www.literatecomputing.com/product/discourse-install/)

**Comment by VictorBjelkholm** [comment]
And all the checkboxes are now checked and our own self-hosted Discourse is hosted at https://discuss.ipfs.io/
