### ISSUE TITLE
configure discourse to support posting via email

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#255]
Need this in order to properly replace the mailing list. 

Currently in order to respond to our discourse threads you need to use the web ui. To enable posting/responding via email we need to set up a mailbox in gmail and point discourse at it.  @lgierth has the details.

adding this to #250

**Comment by Kubuxu** [comment]
I was able to respond to discourse with email, but it might be before we switched from try-discourse.

**Comment by lgierth** [comment]
I've set the from-address on notification emails to no-reply@ipfs.io for now -- another email from someone just ended up on the discuss@ipfs.io email list.

**Comment by diasdavid** [comment]
This seems like an infrastructure ticket.

@lgierth I didn't manage to understand if with https://github.com/ipfs/community/issues/255#issuecomment-301640653 this issue became 'handled'

**Comment by VictorBjelkholm** [comment]
Huh, this should already work, it worked when I first setup the Discourse instance. I will take a look at this.

**Comment by diasdavid** [comment]
Can we move this to infrastructure?? @eefahy

**Comment by diasdavid** [comment]
Created https://github.com/ipfs/infrastructure/issues/439
