### ISSUE TITLE
MozFest 2017 - October 27-29

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#257]
![image](https://user-images.githubusercontent.com/1211152/27159233-68f97332-5163-11e7-97ac-d92db244f8ba.png)

Looks like MozFest would be an extraordinary event for the IPFS community to meet and possibly give an update about what we are up to these days :)

We are still on time to propose sessions: https://mozillafestival.org/proposals (deadline Aug 1)

Thanks to @pgte for hinting me at this and http://maboa.it/decentralise-now/

**Comment by lgierth** [comment]
I would love to do something like an "IPFS Mission AMA/Q&A/Discussion" session. There's so much more to spread into the community than just purely technical things. (I'd also be up for co-hosting that session.)

**Comment by TKorr** [comment]
I live in london so would be up for meeting up/helping out
