### ISSUE TITLE
"Awesome Talks" playlist on Youtube

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/community#259]
Inspired by https://github.com/ipfs/research-CRDT/issues/6, it would be great if we had a public playlist on Youtube with bunch of talks/videos about IPFS and technologies that are related to IPFS.

**Comment by diasdavid** [comment]
Let's move this effort to https://github.com/ipfs/community/issues/260

@pgte could you share the talks you already have in your bookmarks on https://github.com/ipfs/community/issues/260 ? Thanks!
