### ISSUE TITLE
Help us curate our Youtube channel - Demos

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#260]
We've been producing a lot of great content together as a community for the last 3 years, however, as time passes it becomes harder and harder to find it!

After todays [demos](), I thought it would be great to have several playlists of the videos we upload, but also the ones that get published in other channels about IPFS.

Now you can find playlists for Demos, Talks, Interviews and more at 
https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew/playlists

![image](https://user-images.githubusercontent.com/1211152/27807762-dcec13ea-603a-11e7-9364-7fd167888bcf.png)

Help us curate these lists by adding to this issue, urls of videos that are missing.

Thanks!

**Comment by UltraFlow** [comment]
Thank you!

**Comment by kumavis** [comment]
here is the playlist from our eth-ipfs hack week kick off
https://www.youtube.com/playlist?list=PLvf2RZCNC-UD2RLRs8jnIkhG8iXiKIH9w

**Comment by pgte** [comment]
Some lectures on the topic of __CRDTs__:

* Coding CRDTs playlist: https://www.youtube.com/playlist?list=PLzUeAPxtWcqxBXjUelmcm5ORVjEpbUlHH
* Dmitry Ivanov & Nami Naserazad - Practical Demystification of CRDT (Lambda Days 2016): https://www.youtube.com/watch?v=PQzNW8uQ_Y4
* GOTO 2016 • Conflict Resolution for Eventual Consistency • Martin Kleppmann: https://www.youtube.com/watch?v=yCcWpzY8dIA
* ElixirConf 2015 - CRDT: Datatype for the Apocalypse by Alexander Songe: https://www.youtube.com/watch?v=txD1tfyIIvY

**Comment by diasdavid** [comment]
Found one from Carlos Baquero himself https://www.youtube.com/watch?v=y_ewFP-lgyM

**Comment by diasdavid** [comment]
Playlist here: https://www.youtube.com/watch?v=em9zLzM8O7c&list=PLuhRWgmPaHtSvjFsjaVm_Fj9nXuwW35Ai

**Comment by patcon** [comment]
Since you're already curating youtube playlists, you might also like to pay $1/month and get auto-generated video/audio podcasts :)
http://podsync.net/

And if so, feel free to pipe up on this issue to motivate the awesome dev on that project :)
https://github.com/podsync/issues/issues/3
