### ISSUE TITLE
Create a single go-contributor-guidelines document

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#262]
Following up the convo on https://github.com/ipfs/community/pull/202, it seems that overall, the go-ipfs contributors would be happy with having canonical contributor guidelines doc.

@lgierth assigning this to you as you were the last lead on https://github.com/ipfs/community/pull/202

**Comment by diasdavid** [comment]
There is only one now https://github.com/ipfs/community/blob/master/go-code-guidelines.md :)

**Comment by bmwiedemann** [comment]
hmm. somehow all of them are missing now, but the gitcop.com bot still referenced https://github.com/ipfs/community/blob/master/contribution-guidelines.md#a-license-and-a-signed-off-by-trailers-are-required
