### ISSUE TITLE
IPFS and map data

### ISSUE THREAD

**Issue by fastdraw07** [ipfs/community#264]
Could IPFS be used to decentralize Satellite Map data?

**Comment by magik6k** [comment]
It has been used for that already, see: https://ipfs.io/ipfs/QmNfwFPQqJARCQz87i1V3uAEF2t6WxAffTfA678Ad1JZiv/?/ipfs/QmUefFZttPf9xq4KTkk94rBbZEVrBsTreDi4JA8KYhQFX6/

https://github.com/davidar/ipfs-maps

**Comment by fastdraw07** [comment]
@magik6k Thank you for link. Very cool.

I'm thinking about a startup using maps and IPFS and one of the blockchains. If you know any really good devs, I'd appreciate the intor.

**Comment by diasdavid** [comment]
More notes on https://github.com/ipfs/notes/issues/142

**Comment by diasdavid** [comment]
In fact, mind if we redirect this convo to https://github.com/ipfs/notes/issues/142 ? Trying to keep the house organized so that we make it easier for newcomers :)
