### ISSUE TITLE
Is it a good idea to store confidential docs on IPFS?

### ISSUE THREAD

**Issue by smeeklai** [ipfs/community#265]
First of all, great job to all the creators of this project.

I just have a quick question about how would I use IPFS with my idea.

My idea is users can store their confidential docs on the IPFS. However, only people who are verified and granted right by me can access those files. Is it possible to use IPFS with the idea?

Cheers

**Comment by Stebalien** [comment]
At the moment, the only way to achieve this is through private networks where only authorized participants (those with the shared secret key) are allowed to join the network. We don't yet have access control on a file-by-file basis.

**Comment by zinovi** [comment]
Regardless, you should encrypt all your confidential files at rest. Then you could threat IPFS as untrusted storage and concentrate on protecting your keys.

**Comment by diasdavid** [comment]
Closing this issue in favor of continuing the conversation in one of the already open issues about [`private content`](https://github.com/ipfs/notes/issues?q=is%3Aissue+is%3Aopen+encryption+label%3A%22private+content%22)
