### ISSUE TITLE
Private Network with IPFS not working 

### ISSUE THREAD

**Issue by dineshrivankar** [ipfs/community#268]
We have created 2 nodes using stranded ( https://ipfs.io/docs/install/)
Both are connected to the public network and working fine.
Now we are trying to create a Private Network with these 2 nodes as described below, but data is not getting synced on both nodes.
https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks

Below is the responce when we start daemon 
```
$ipfs daemon --enable-pubsub-experiment

Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Swarm is limited to private network of peers with the swarm key
Swarm key fingerprint: 5c9869c16230b2b24f66f89a519043d1
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/1127.0.0.1/tcp/8080
Daemon is ready
```

**Comment by Kubuxu** [comment]
@dineshrivankar have you solved this?

**Comment by dineshrivankar** [comment]
@Kubuxu Yes , resolved by coping the swarm.key  in `~/.ipfs/swarm.key` for all nodes in th enetwork.
Also bootstrapped the main node with the other network address.
Hope its the correct way.

**Comment by hp1909** [comment]
In swarm.key what content should we copy? Only the key or the entire file content to other nodes?

**Comment by dineshrivankar** [comment]
@hp1909  we need to copy the entire file.
