### ISSUE TITLE
Barcelona Hack Day

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/community#270]
## Time

~~One of the days between 9th and 25th October, still not entirely decided.~~

~~**Preliminary date**: 24th of October~~

Confirmed date: **28th of October** from 14:00 (2PM) to 20:00 (8PM)

## Who is it for?

Anyone from beginners to people who want a deep dive into IPFS.

## Location

~~Currently `undefined`. @tomasdiez has previously offered a venue from Fab Lab Barcelona, so that might work this time around.~~

Fab Lab Barcelona - Carrer de Pujades, 102, 08002 Barcelona

## RSVP

Please RSVP here as the seats are limited: https://www.meetup.com/IPFS-BCN/events/244344626/

## What to do

I'll go through some of the basics from how to use the CLI/Terminal in general, introduction to distributed web and going through the major features of IPFS.

Then we can also have space to hack on IPFS things or really whatever people want to.

## Who will be attending?

I will be there. I think @nicola will be around BCN at this time as well. If you want to attend or help out plan it, please write your thoughts here :)

**Comment by xavivives** [comment]
I understand that is a one day thing. To be defined between the mentioned dates? Or multi-day event?

**Comment by VictorBjelkholm** [comment]
@xavivives one day thing! Could have been more clear, I'll update it. Thanks!

**Comment by JustinDrake** [comment]
Potentially interested in joining! The later the better, as it gives me time to organise travel.

**Comment by aaronwinter** [comment]
Please allow online attendance and set-up an IRC channel. I think you could attract volunteers from all over (including IPFS devs/maintainers).

**Comment by VictorBjelkholm** [comment]
@aaronwinter that's a really good idea, will make sure that happens. Cannot guarantee who from the core-team will attend though, but would be good to allow remote attendance.

**Comment by fcsonline** [comment]
I'm in

**Comment by andresgutgon** [comment]
I'm in too

**Comment by nicola** [comment]
I will be in!

**Comment by tomasdiez** [comment]
yes! We could do it at Fab Lab Barcelona: http://fablabbcn.org/, need to sync schedule but is doable

**Comment by fbaiodias** [comment]
I will be in too!

**Comment by gtrias** [comment]
I will be in too :)

**Comment by krbu** [comment]
I will be in!!

**Comment by JCsiroop** [comment]
I'll be in!!

**Comment by jachiang** [comment]
I'm will be in! Looking forward to meeting the IPFS community in Barcelona!

**Comment by nicola** [comment]
Only available dates for me are from Oct 23+ :(

**Comment by VictorBjelkholm** [comment]
So, preliminary date that hopefully works for as many as possible:

## 23th of October

Venue still TBD

**Comment by nicola** [comment]
(actually can I suggest 24th? on the 23rd I might be on a plane back during the day)

**Comment by VictorBjelkholm** [comment]
@nicola assumed incorrectly you'd landed here 22th and would be available 23th, so updated now! Thanks 👍

**Comment by jachiang** [comment]
Dear all, is this IPFS deep dive open to all interested blockchain devs/enthusiasts? I would love to attend, but want to make sure my presence would be appropriate/welcome. Cheers!! :)

**Comment by jefft0** [comment]
I'll be there.

**Comment by dasilvacontin** [comment]
Very interested as well! 😊

**Comment by mariondita** [comment]
I am in! yay! Thanks :D

**Comment by VictorBjelkholm** [comment]
## Finally have a solid date and venue!

The second hack day in Barcelona will be in Fab Lab Barcelona at 28th of October. More details are in this issue (top post) and also at the meetup page: https://www.meetup.com/IPFS-BCN/events/244344626/

Please RVSP as the seats are limited and it also becomes easier to figure out how much food + drinks are needed.

@jachiang you should for sure drop by, there is a lot of cross-pollination between the two worlds so would welcome you with open arms :)

**Comment by JustinDrake** [comment]
I can't make the 28th but I hope to see some of you a few days later at Devcon3!

**Comment by xavivives** [comment]
Same here ^^

**Comment by VictorBjelkholm** [comment]
Absolutely, I'll be there :)

**Comment by VictorBjelkholm** [comment]
This happened and was a lot of fun! Created a repository for all the information and some projects to hack on: https://github.com/VictorBjelkholm/ipfs-hack-day-barcelona-october-2017

Some photos from the event:

![photo6028182377886493225](https://user-images.githubusercontent.com/459764/32179968-b9ff952e-bd5e-11e7-9769-7ec56aba3280.jpg)
![photo6028182377886493226](https://user-images.githubusercontent.com/459764/32179969-ba3826aa-bd5e-11e7-86d8-181af760b99f.jpg)
![dnova5wxkaa376j](https://user-images.githubusercontent.com/459764/32180003-cbb8b55c-bd5e-11e7-92f1-0ab9319fcb2a.jpeg)
![screenshot from 2017-10-30 10-38-04](https://user-images.githubusercontent.com/459764/32180008-cff52952-bd5e-11e7-8baf-4e1dac3a113e.png)

**Already started to plan the next one, you can register for it here: https://www.meetup.com/IPFS-BCN/events/244637091/**
