### ISSUE TITLE
2018, February 3 & 4 - FOSDEM (Brussels)

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#271]
![image](https://user-images.githubusercontent.com/1211152/31457077-f7bb4450-aebb-11e7-8aeb-03cc1e61bb04.png)

### After the great fun of [FOSDEM 2016](https://github.com/ipfs/community/issues/88) and [FOSDEM 2017](https://github.com/ipfs/community/issues/194), here comes **FOSDEM 2018**.

**Who is planning on going next year?** Are you down for an IPFS community meetup while at the conf or post conf??

**Comment by chriscool** [comment]
I will likely go, and sure I would attend an IPFS community meetup before, after or during the conf.

**Comment by diasdavid** [comment]
Ok, let's get the conversation active in this thread. The ones I know going so far are:

- @diasdavid
- @flyingzumwalt 
- @miyazono 
- @nicola 
- @vmx
- @hacdias
- @chriscool 

Who else is joining? :)

**Comment by diasdavid** [comment]
@gpestana, @jgantunes, @diffcunha are you in as well?

**Comment by diasdavid** [comment]
Also @sublimino \o/

**Comment by stskeeps** [comment]
@stskeeps will :)

**Comment by gpestana** [comment]
I'm in and I'm down for the community meetup on the 1st or during the conf (leaving on Sunday).

**Comment by diffcunha** [comment]
I’m in @diasdavid

**Comment by diasdavid** [comment]
@hassy is also coming \o/

**Comment by diasdavid** [comment]
@gpestana you meant a meetup on the 2nd right? If not, why would the 1st be the best day?

**Comment by JGAntunes** [comment]
I'll have a project report and presentation due to February 3rd, so I'll be out unfortunately @diasdavid :cry:

**Comment by berry** [comment]
I am a loyal visitor of FOSDEM and interested in IPFS. Could you please sum up when and where on FOSDEM I can listen or participate in IPFS talks or meetings? Thanks very much.

**Comment by gpestana** [comment]
@diasdavid true, not the 1st but the 2nd of Feb works for me. Or during the conf :)

**Comment by diasdavid** [comment]
Thank you all that joined, it was really great to catch up with the community. See you again next year!

**Comment by gpestana** [comment]
Count me in for FOSDEM 2019!!
