### ISSUE TITLE
We just got a Meetup.com Pro account for IPFS \o/ 🎉

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#283]
Hi everyone, I've some exciting news!

We just got a Meetup.com Pro account 🌟 What this means is that:

- We will be able to sponsor the Meetup.com costs from local community organizers
- It will be easier to find local IPFS meetups
- We got this rad map -> https://www.meetup.com/pro/ipfs/ (still meetups to be added)

To make the map complete, it would be great to upgrade the community started meetups to the IPFS account so that they appear on the map. These are:

- ✅ https://www.meetup.com/Bratislava-IPFS-Meetup - organizer: @yangwao 
- ✅ https://www.meetup.com/Copenhagen-IPFS-Meetup - organizer: @neoteo 
- ✅ https://www.meetup.com/IPFS-London-Meetup - organizer: @JustinDrake
- ✅ https://www.meetup.com/IPFS-BCN - organiser: @VictorBjelkholm 
- https://www.meetup.com/Philadelphia-IPFS-Meetup - organiser: @flyingzumwalt 

@yangwao, @neoteo and @ianopolous, would you be cool with giving Organizer role to my account so that I can upgrade the meetup?

I've updated our list on the README -- https://github.com/ipfs/community/blob/master/README.md#meetup-list --.

**Comment by shtukas** [comment]
:+1:

**Comment by VictorBjelkholm** [comment]
I invited this account: https://www.meetup.com/IPFS-BCN/members/249142444/ to be a co-organizer for IPFS-BCN, is that enough or needs to be a full transfer?

**Comment by diasdavid** [comment]
@VictorBjelkholm unfortunately, Meetup will only let me upgrade if I am the main organizer. You need to step down, elect me, I need to accept, upgrade and then I can add you back as a co-organizer. Thanks!

**Comment by ianopolous** [comment]
@diasdavid I'm not an organiser of that group. So I don't have the permissions.

**Comment by diasdavid** [comment]
@ianopolous ah, I saw the pic with you and assumed it would be you. Do we known the handle of Justin Drake -- https://www.meetup.com/IPFS-London-Meetup/members/72369962/.

**Comment by JustinDrake** [comment]
To be honest, I didn't create the Meetup group and became admin by "accident". I don't live in London and I haven't organised a single meetup :( Does anyone more appropriate want to take over the London meetup?

**Comment by diasdavid** [comment]
@JustinDrake I believe @olizilla and @edsilv have been wanting to help out there. Could you give me the organizer role so that I can upgrade the account and invite everyone as an organizer? 

The steps to do that (because Meetup.com makes it a bit complicated) are:

- Step down as a Organizer
- Elect me as a Organizer
- I take the offer and upgrade the meetup
- I invite everyone to be a co-organizer
- ✅ 🎉🚀

**Comment by JustinDrake** [comment]
Done 👍

**Comment by NeoTeo** [comment]
Hey @diasdavid :) You seem to have two profiles on the Copenhagen Meetup and I can only hand over the group as organizer to the first David Dias. Shall I remove that from the group and see if it changes the options?

**Comment by diasdavid** [comment]
@NeoTeo you can give it to either, I can then transfer it again myself :)

**Comment by NeoTeo** [comment]
Done 👍

**Comment by diasdavid** [comment]
@NeoTeo you sure? I didn't receive any email.

**Comment by kasstawi** [comment]
Hi David, 

Chicago is here https://www.meetup.com/Chicago-IPFS-Filecoin/ 
We can organize and host IPFS meetups in Chicago. Please join so that I can elect you and the whole process.

**Comment by dongtianyi** [comment]
@diasdavid  My meetup.com account is https://www.meetup.com/members/247516461/
**[Beijing, China IPFS #282](https://github.com/ipfs/community/issues/282)**

**Comment by yangwao** [comment]
@diasdavid added you as co-organizer, will it work? 🚀

**Comment by diasdavid** [comment]
@yangwao all done \o/, thank you!

Just missing Philly, @flyingzumwalt ? :)

**Comment by dongtianyi** [comment]
@diasdavid  can you join 
https://www.meetup.com/Shenzhen-IPFS-Meetup/
and
https://www.meetup.com/Beijing-IPFS-Meetup/
in order to I can elect you as an Organizer ?
Thanks
Beijing, China IPFS #282

**Comment by diasdavid** [comment]
@dongtianyi just joined :) See instructions on how to effectively elect me as a Organizer here -- https://github.com/ipfs/community/issues/283#issuecomment-369199928 --.

**Comment by dongtianyi** [comment]
@diasdavid  done! elect you as an Organizer for both 
https://www.meetup.com/Beijing-IPFS-Meetup/ and https://www.meetup.com/Shenzhen-IPFS-Meetup/
