### ISSUE TITLE
Shenzhen, China IPFS

### ISSUE THREAD

**Issue by dongtianyi** [ipfs/community#288]
Meetup
Date：10, Mar
Details: http://mp.weixin.qq.com/s/imvW34IFW8JTbYWVv-Vg_g
and https://www.meetup.com/shenzhen-ipfs/events/248375272/

主题：IPFS和Filecoin的技术分享
主讲人：飞向未来
地点：银河创客咖啡
时间：2018.3.10 下午14：00
人数：80人

**Comment by diasdavid** [comment]
Machine translated version for those who are curious like me :)

```
Topic: Technical Sharing of IPFS and Filecoin
Speaker: Fly to the future
Location: Galaxy Chongke coffee
Time: 2018.3.10 at 14:00
Number of people: 80 people
```

**Comment by ahoebeke** [comment]
Hi Tainyi, the QR Code for the wechat group says there are more than 100 members and an invite is needed to join. 

I found your wechat contact on here (flytofuture_tt) and got in touch, but writing it here for others to see.
My Mandarin is limited, hope I'll understand something ;)

**Comment by dongtianyi** [comment]
@ahoebeke  yes, flytofuture_tt is official wechcat. Thank you.
@diasdavid  This is cool. lol

**Comment by dongtianyi** [comment]
@diasdavid  Too many people want to attend meetup(2018.3.10), I have decided one more meetup at 2018.3.11.

**Comment by ahoebeke** [comment]
@dongtianyi  Having 2 events in one weekend might mean that lessons learned from the first event cannot so quickly be adapted to improve the second meetup. It also means that people who attended the first time will not come again the next day for the same presentation.. which splits the community a bit.
That being said, it's great that you have so much energy! and that so many people are interested.

@diasdavid  how do such meetups usually get organised? Is there an IPFS-meetup guidelines document, best practices, maybe recommended PPT to save some time and be sure we've got the latest info? (Shared resources for all meetups, which could be more useful for workshops, dev demos etc)

**Comment by dongtianyi** [comment]
@ahoebeke  

> It also means that people who attended the first time will not come again the next day for the same presentation
Yes. This is right.  We are a big community!

**Comment by diasdavid** [comment]
Ahaha @dongtianyi you are unstoppable! Great work on gathering so much interest so quickly :)

@ahoebeke all good questions! We are working on creating a set of materials meetups can use (slidedecks, tutorials and so on) but they are not ready yet. Meanwhile you can use the IPFS Examples -- https://ipfs.io/docs/examples/  + https://github.com/ipfs/js-ipfs/tree/master/examples -- and libp2p Examples -- https://github.com/libp2p/js-libp2p/tree/master/examples. As for best practices, definitely make sure to go through the IPFS Community Code of Conduct -- https://github.com/ipfs/community/blob/master/code-of-conduct.md.

**Comment by dongtianyi** [comment]
@diasdavid  more and more meetups are planning.
Shanghai
Hangzhou
Fuzhou  (2018-03-24)
Chengdu
Xia'men
....
I am introducing IPFS/Filecoin to Chinese people.(Users, Developers, Miners,  and so on.)

**Comment by ahoebeke** [comment]
Wow!!

Makes me wonder, are there Chinese resources for IPFS? A Chinese-language version of the Github IPFS homepage would be useful maybe? @diasdavid @dongtianyi

**Comment by dongtianyi** [comment]
@ahoebeke   Yes, If so, It is very useful.  Actually, I have translated some blog for filecoin.io.
Maybe we can trans filecoin.io and ipfs.io homepage.

**Comment by dongtianyi** [comment]
> are there Chinese resources for IPFS

I am writing technical articles.
https://zhuanlan.zhihu.com/ipfsguide
or
Wechat Official account: IPFS指南 (ipfs_guide)

**Comment by buckle2000** [comment]
Sadly, the Chinese government already censored `ipfs.io`.
The reason, in my opinion, is that the best use case of IPFS in china is to break internet censorship.
