### ISSUE TITLE
Private IPFS not working probably due to network security?

### ISSUE THREAD

**Issue by ankitharrytom** [ipfs/community#291]
I have one IPFS on Windows and another one on Ubuntu (VM).
Ubuntu VM I am using as my bootstrap node:
Swarm key generated on Ubuntu is added to Windows .ipfs folder too.

Windows:
```
  "Addresses": {
    "API": "/ip4/10.207.141.19/tcp/5002",
    "Gateway": "/ip4/127.0.0.1/tcp/8081",
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4002",
      "/ip6/::/tcp/4002"
    ]
  },
  "Bootstrap": [
    "/ip4/10.207.131.11/tcp/4001/ipfs/QmR1gYQriBoYrUxVECKiUtpotZkSYdv6sjivb9aHXr2u3k"
  ],
```

Ubuntu:
```
  "Addresses": {
    "API": "/ip4/10.207.131.11/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
  "Bootstrap": [
    "/ip4/10.207.131.11/tcp/4001/ipfs/QmR1gYQriBoYrUxVECKiUtpotZkSYdv6sjivb9aHXr2u3k"
  ],
```

Windows response:
```
C:\Users\Administrator\Desktop\go-ipfs>SET LIBP2P_FORCE_PNET=1 && ipfs daemon
Initializing daemon...
Swarm listening on /ip4/10.207.141.19/tcp/4002
Swarm listening on /ip4/127.0.0.1/tcp/4002
Swarm listening on /ip4/169.254.122.247/tcp/4002
Swarm listening on /ip6/::1/tcp/4002
API server listening on /ip4/10.207.141.19/tcp/5002
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8081
Daemon is ready
```

Ubuntu response:
```
ankit@ankit-VirtualBox:~/.ipfs3$ export LIBP2P_FORCE_PNET=1 && IPFS_PATH=~/.ipfs3 ipfs daemon
Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Swarm is limited to private network of peers with the swarm key
Swarm key fingerprint: e6082b76e2cf7ffe64a2742c1b6f6302
Swarm listening on /ip4/10.207.131.11/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/172.18.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmR1gYQriBoYrUxVECKiUtpotZkSYdv6sjivb9aHXr2u3k
Swarm announcing /ip4/10.207.131.11/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.17.0.1/tcp/4001
Swarm announcing /ip4/172.18.0.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/10.207.131.11/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```

But there are not discovering each other:
ankit@ankit-VirtualBox:~/.ipfs3$ IPFS_PATH=~/.ipfs3 ipfs swarm peers
ankit@ankit-VirtualBox:~/.ipfs3$ 

Unless there is a wrong configuration above, my guess is there is some problem due to the network being a company network and some authentication/proxy issue coming in?

**Comment by Kubuxu** [comment]
looks like Windows is not loading the swarmkey, see that the output of the log does not contain `Swarm is limited to private network of peers with the swarm key`.

**Comment by ankitharrytom** [comment]
But then it daemon should not start, isn't it? I am setting the env variable LIBP2P_FORCE_PNET=1

**Comment by Kubuxu** [comment]
I don't know about windows, but this variable might not be propagating to go-ipfs.

**Comment by Kubuxu** [comment]
For future questions like this please use our support forum https://discuss.ipfs.io

**Comment by ankitharrytom** [comment]
Thanks @Kubuxu 
Looks like I should stick to Ubuntu for now since neither it seems to be taking Environment variable neither is it detecting the swarm.key file.
For future questions will use the forum as suggested.

**Comment by kareem-adel-1990** [comment]
how can i solve this issue

PS C:\go\bin> ipfs daemon
Initializing daemon...
go-ipfs version: 0.7.0       
Repo version: 10
System version: amd64/windows
Golang version: go1.14.4
2020-10-08T23:14:49.472+0200    ERROR   cmd/ipfs        error from node construction: could not 
build arguments for function "github.com/ipfs/go-ipfs/core/node".PeerWith.func1 (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:29): failed to build *peering.PeeringService: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Peering (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/pnet.go:21): failed to configure private network: expected file header /key/swarm/psk/1.0.0/, got: ��/key/swarm/psk/1.0.0/

.go:29): failed to build *peering.PeeringService: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Peering (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/pnet.go:21): failed to configure private network: expected file header /key/swarm/psk/1.0.0/, got: ��/key/swarm/psk/1.0.0/
PS C:\go\bin> ipfs init
generating ED25519 keypair...done
peer identity: 12D3KooWJQEdPFYJ924UApZsrSKHJedhAe1SD6gLpqXY9Cz56Yoo
initializing IPFS node at C:\Users\aast\.ipfs
Error: ipfs configuration file already exists!
Reinitializing would overwrite your keys.

PS C:\go\bin> ipfs daemon
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/windows
Golang version: go1.14.4
2020-10-08T23:16:24.405+0200    ERROR   cmd/ipfs        error from node construction: could not build arguments for function "github.com/ipfs/go-irguments for function "github.com/ipfs/go-ipfs/core/node".Peering (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/pnet.go:21): failed to configure private network: expected file header /key/swarm/psk/1.0.0/, got: ��/key/swarm/psk/1.0.0/

Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".PeerWith.func1 (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:29): failed to build *peering.PeeringService: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Peering (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/pnet.go:21): failed to configure private network: expected file header /key/swarm/psk/1.0.0/, got: ��/key/swarm/psk/1.0.0/
PS C:\go\bin> ipfs daemon
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/windows
Golang version: go1.14.4
2020-10-08T23:18:01.606+0200    ERROR   cmd/ipfs        error from node construction: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".PeerWith.func1 (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:29): failed to build *peering.PeeringService: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Peering (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/pnet.go:21): failed to configure private network: expected file header /key/swarm/psk/1.0.0/, got: ��/key/swarm/psk/1.0.0/

Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".PeerWith.func1 (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:29): failed to build *peering.PeeringService: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Peering (github.com/ipfs/go-ipfs@v0.7.0/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/go-ipfs/core/node/libp2p".PNet (github.com/ipfs/go-ipfs@v0.7.0/core/node/libp2p/pnet.go:21): failed to configure private network: expected file header /key/swarm/psk/1.0.0/, got: ��/key/swarm/psk/1.0.0/
