### ISSUE TITLE
Fuzhou, China IPFS

### ISSUE THREAD

**Issue by dongtianyi** [ipfs/community#293]
Meetup
Date：27, Mar
Details: [微信公众号](http://mp.weixin.qq.com/s/fUK9TAXJ3hh2ypTtvgsvew)
and [报名](https://www.weixinyunduan.com/wx/pub/yunduanwx/index.php?g=Wap&m=Selfform&a=index&token=476765&id=11058)

主题：IPFS和Filecoin的技术分享
主讲人：飞向未来(董天一)
地点：福州国脉综合楼一层
时间：2018.3.24 下午14：00
人数：不限

**Comment by dongtianyi** [comment]
@diasdavid  Hi, David, I am arranging Fuzhou meetup at 3.24. 
and I create a group  https://www.meetup.com/Fuzhou-IPFS-Meetup
Can you join this group and I can elect you as an ORGANIZER ?

**Comment by diasdavid** [comment]
@dongtianyi no one is stopping @dongtianyi \o/ I've just joined with my account to that one too :)

**Comment by dongtianyi** [comment]
@diasdavid  elect you as an ORGANIZER!  Done!

**Comment by diasdavid** [comment]
@dongtianyi I don't think you have, could you double check? https://www.meetup.com/Fuzhou-IPFS-Meetup/members/249142444/

**Comment by dongtianyi** [comment]
@diasdavid do it again！
