### ISSUE TITLE
Supported node versions

### ISSUE THREAD

**Issue by achingbrain** [ipfs/community#303]
Does anyone think it's worthwhile adding a section to `js-code-guidelines.md` stating which node versions are supported?  LTS + Current or something?

**Comment by VictorBjelkholm** [comment]
Yeah, we've established guidelines for this somewhere, tried finding where that discussion was held, but couldn't find it.

But plan is to support LTS + Current (as of writing, it's 8.11.1 LTS and 10.0.0), just as you said.
