### ISSUE TITLE
Add libp2p bi-weekly call to IPFS Community Calendar

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#305]
@mgoelzer is going to start convening bi-weekly libp2p calls. Let's give him access to the IPFS community calendar so he can add the calls there.

**Comment by flyingzumwalt** [comment]
@mgoelzer annoyingly, you need an @ipfs.io google account in order to have edit permissions on the IPFS Calendar. I'm not sure who has the admin privileges to give you one of those accounts.

**Comment by flyingzumwalt** [comment]
(turns out I have those admin privileges) @mgoelzer you've got an ipfs.io account and that account is able to edit the calendar.

**Comment by mgoelzer** [comment]
Thanks!  It's on the IPFS Community Calendar now.

**Comment by gpestana** [comment]
This is cool, looking forward for the calls!

**Comment by diasdavid** [comment]
Done here https://github.com/libp2p/pm#bi-weekly-call
