### ISSUE TITLE
IPFS links is being banned by Twitter

### ISSUE THREAD

**Issue by kasstawi** [ipfs/community#323]
Thanks to Chris Burniske for discovering this [issue](https://twitter.com/cburniske/status/1003008818643685376). 

I made a test here and here's a [message](https://twitter.com/Elkasstawi/status/1003144426187886592) I got

**Comment by kyledrake** [comment]
@kasstawi can you confirm quickly that this is resolved? Didn't know if that was why you closed this issue.

**Comment by kasstawi** [comment]
Yes. It was resolved https://twitter.com/ammori/status/1003330613175255042?s=21
