### ISSUE TITLE
common hours

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/community#33]
Hey Everyone!
I would like to have some common hours on weekdays where everyone is online and available. Working distributed is hard, and even more so when nobody is around to answer questions when you have them. I'm thinking a span of three to four hours, possibly 16:00Z to 19:00Z (plus or minus an hour either direction). This is already the time we do sprint checkins, So I think its fairly reasonable to ask everyone to be 'online' during this time.

Thoughts? Discussion?

**Comment by lgierth** [comment]
These times work well for me, and it's good to have people around for questions or bouncing ideas.

**Comment by diasdavid** [comment]
16:00Z to 19:00Z works good for me. Tuesdays and Thursdays I typically have training starting at 19:10Z,  I wouldn't have to miss anything :):)

**Comment by jbenet** [comment]
ok sounds good, i'll be around 16:00Z - 19:00Z from now on.

**Comment by jbenet** [comment]
updated in the pm doc. https://github.com/ipfs/pm/ 
(16:00Z is so early!)
