### ISSUE TITLE
JavaScript Projects: run browser tests in CI only

### ISSUE THREAD

**Issue by mikeal** [ipfs/community#338]
One thing I've found that makes contributing very difficult to our JavaScript projects is the browser tests. I've never actually been able to successfully run *any* of our browser tests in any of the JS projects I've contributed to.

I've gotten in the habit of running `test:node` and then committing and push with`--no-verify` which is not a great solution.

There's probably a lot that we can do to improve the runability and reliability of the browser tests, like moving to puppeteer, but that's going to take time. In the meantime, I'd like to remove this barrier to contribution by changing the JS project `pre-commit` and `pre-push` definitions to run `test:node` only.

We should make sure that CI is running the browser tests before contributions get merged, but having them run before every commit and push is rather painful.

**Comment by diasdavid** [comment]
Moving this one to https://github.com/ipfs/testing/issues/159
