### ISSUE TITLE
Berlin, Germany (Oct 11, 2018) IPFS

### ISSUE THREAD

**Issue by svitekpavel** [ipfs/community#339]
Date: October 11th, 2018
City: Berlin, Germany
Location: Base58 (Chausseestr. 86, Berlin - Mitte)

More info: https://www.meetup.com/IPFS-Berlin/events/254816369/

**Comment by mikeal** [comment]
Awesome!

I've already scheduled some tweets to go out of IPFSBot about it the day before and day of :)
