### ISSUE TITLE
Setting up a matrix community and bridging it to discord

### ISSUE THREAD

**Issue by swedneck** [ipfs/community#351]
Hi all!

I'd really like to improve the IPFS (and other protocol labs projects) rooms on Matrix.
My suggestions are to:

- a) Remake the currently bridged rooms, and manually bridge them to IRC.
This is needed because the current rooms were created by the IRC bridge, and it's thus impossible to make anyone admin in them.

- b) Make a Protocol Labs community (+protocol-labs:matrix.org) and add the now remade rooms to it.
Making a community would help organize the rooms and make it easier to find them.

- ~~c) Bridge the rooms to Discord. (https://discord.gg/24fmuwR)
A bridge to discord makes it much easier for the average joe to get into IPFS (and other projects), as they most likely already use Discord and are hesitant to use IRC or Matrix.~~ Done!

**Comment by diasdavid** [comment]
Agreed on a), https://riot.im/app/#/group/+ipfs:matrix.org is currently kind of painful to manage as only @Stebalien can do it. @Stebalien thoughts?

I don't think b) is necessary or do we want to call it protocol labs

Given that we have the Matrix community, riot.im makes it super easy. I don't see why creating another bridge to discord c) would make it simpler.

**Comment by swedneck** [comment]
It may be easy for you, but for a lot of people they just don't want to use anything they're not used to.
Bridging to discord would help make IPFS much more approachable for the average person.

**Comment by diasdavid** [comment]
> Bridging to discord would help make IPFS much more approachable for the average person.

It just sounds you are trading the cost of creating a Matrix account by a Discord account. I don't believe that the "average person" (here meaning, the number of users that both use one of these tools and are part of the IPFS community) is actually large and therefore, the "average person" they will have to create an account in one of them.

**Comment by diasdavid** [comment]
@swedneck not necessarily. I'm just not get your point and shared with the understanding I have.

**Comment by ThibaultLemaire** [comment]
I can relate to not wanting to be forced to create a new account, and given the discord user base is pretty large I can see the use of a bridge.

Although, it could be argued that people interested in ipfs would not be that reluctant to create a new account in matrix, at least for now because it remains a techy subject.

The truth is without actual data on the subject it's hard to decide. So what's the cost of setting up and maintaining a Discord bridge? We could set it up for a trial period to get some feedback on the subject, and then decide whether to keep it or not?

**Comment by swedneck** [comment]
I already have the bridge software running on my server, and it's already bridging 2 communities (linux gaming and thinkpad), so there would really be no cost to running the bridge.

**Comment by postables** [comment]
Personally while I have no qualms with IRC, I don't think IRC is very condusive to a vibrant community as it will most likely only be used by developers. IMO it's also hard to have long-term, engaging discussions over IRC. I think using discord allows you to cultivate a more vibrant community, not just of developers but also general people who may be interested in IPFS, IPLD, etc..

**Comment by Stebalien** [comment]
> Agreed on a), https://riot.im/app/#/group/+ipfs:matrix.org is currently kind of painful to manage as only @Stebalien can do it. @Stebalien thoughts?

+ipfs:matrix.org (community) is unrelated to #ipfs:matrix.org (room). Remaking the room won't fix the fact that, at the moment, communities can have only one admin (as far as I can tell). At the moment, that community only really exists to reserve the name.

> Given that we have the Matrix community, riot.im makes it super easy. I don't see why creating another bridge to discord c) would make it simpler.

The idea behind bridges is that it gives users choice. They can choose to use whatever protocol they want and still participate in the same room.

Basically, it's not an either-or, it's a both. IMO, as long as setting up the bridge/server is easy and doesn't hurt either the IRC or matrix users, we might as well offer the choice.

> Personally while I have no qualms with IRC, I don't think IRC is very condusive to a vibrant community as it will most likely only be used by developers. IMO it's also hard to have long-term, engaging discussions over IRC. I think using discord allows you to cultivate a more vibrant community, not just of developers but also general people who may be interested in IPFS, IPLD, etc..

So does matrix. Personally, I have absolutely no intention of *supporting* or *encouraging* users to use a closed communication platform, I just see no issue interoperating with it.

**Comment by dignifiedquire** [comment]
Leaving my 2cents, please enable the discord bridge, for me personally the UX of discord is worlds better than matrix/riot/<insert irc client>, at least today.

**Comment by ramined** [comment]
Hey guys, I'm the admin on the IPFS Discord.

Let's keep things simple: we all want to have more IPFS fans. Having the bridge helps with this goal.
I don't see the upside in not collaborating. I think we can try it, see if it works, and if we're not happy with it, we'll roll back.

Cool?

**Comment by shokuz** [comment]
Hey guys, I'm the admin on the IPFS Discord.

Let's keep things simple: we all want to have more IPFS fans. Having the bridge helps with this goal.
I don't see the upside in not collaborating. I think we can try it, see if it works, and if we're not happy with it, we'll roll back.

Cool?

**Comment by shokuz** [comment]
Done!

**Comment by dud1337** [comment]
Seems the last update here was well before Riot's UI and cross-signing updates. Was this reconsidered?

**Comment by swedneck** [comment]
There's nothing official but shokunin's startup is sponsoring a matrix server which is currently bridging #ipfs:matrix.org to discord!

**Comment by mvdan** [comment]
Worth noting that IPFS on Matrix, bridged to other places like IRC and Discord, happened earlier this year - including more rooms like #libp2p: https://docs.ipfs.io/community/chat/
