### ISSUE TITLE
Calendar for syncing travels

### ISSUE THREAD

**Issue by lgierth** [ipfs/community#36]
We should write down who's where when, so that we can optimize for meatspace time. Preferrably in some kind of calendar tool.

**Comment by jbenet** [comment]
yes! 

We need:
- individuals to have their own cal, or be able to otherwise explicitly mark their indiviudal locations + travel in a calendar
- have one calendar for sprints, discussions, etc.
- have one calendar for meetups, talks, etc

Google calendar can do all this. I have google apps setup for @ipfs.io -- so can hang out people addresses to match their github usernames, and they can make public calendars there. but not sure if something better exists already, or something easier. if you know, speak up!

**Comment by RichardLitt** [comment]
We also need to record birthdays! 

I think we should just use Google. @jbenet What do we need to start accessing and writing to that calendar?

**Comment by RichardLitt** [comment]
:cake: :cake: :cake:

**Comment by RichardLitt** [comment]
Google Calendar has [an API](https://developers.google.com/google-apps/calendar/v3/reference/events) which we can use to automatically create events from JSON, preferably from a file with Birthdays and travel plans in this repository. There's at least one [active wrapper](https://www.npmjs.com/package/google-calendar) for node that we can use to both a) streamline importing into Google Calendar and b) as part of a module which takes easy-to-read JSON and makes it better Google stuff. 

Thoughts? Might be easier just to have a calendar and add people to it, Google actually has spent a lot of time thinking about tooling.

**Comment by jbenet** [comment]
I think you're right. Google calendar is likely the best thing so far.

does it make sense to make a +Community? idk what tooling is available there.

**Comment by RichardLitt** [comment]
I don't think a Google Plus community would work. I'm in charge of a 700~ one, and there's no good tooling for having people add to calendars I think. Why don't we just use the Google Apps calendar, and have the single source of truth be the calendar, not a JSON file? 

We'd need a one-off add of birthdays (admin (me) can do that). And then we'd need people to add their travel plans. I still think this is better than jerryrigging a JSON subset. I think we may have found a hole in the remote-team market; good calendar syncing for remote teams.

**Comment by jbenet** [comment]
Haha yep! You're right, sounds good. 



—

**Comment by jbenet** [comment]
@RichardLitt could you set this up on as an ipfs.io GApps calendar?

**Comment by RichardLitt** [comment]
@jbenet I can't at the moment - I don't have any IPFS app passwords. Can we talk about this?

**Comment by RichardLitt** [comment]
This has been done. https://www.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84%40group.calendar.google.com&ctz=America/New_York

Added a few people. Where should this calendar be publicized?

**Comment by jbenet** [comment]
I wonder how this would scale to having 20 or 30 people list out where
they'll be on one cal. Along with events it will get very noisy.

We could

- have one cal for events
- have one cal for where people are

**Comment by RichardLitt** [comment]
I think that's a good idea.

**Comment by chriscool** [comment]
Are we supposed to add things by ourselves to the calendar now?

**Comment by RichardLitt** [comment]
@chriscool If you know of any events that ought to be added to the calendar, then yes! Let me know if you need help doing that.

**Comment by RichardLitt** [comment]
Closing this, as the calendars have been created and information on them has been added to the README. Reopen as issues emerge.
