### ISSUE TITLE
Bug in IPFS Community Calendar

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#360]
Something is wrong with the IPFS Community calendar iCal feed. When you load it in Apple's Calendar app, it shows **IPFS Project WG Weekly Sync Up** as a three week long event, covering the whole calendar for all of those weeks. Multiple people have reported this, multiple people have tried to fix it, but the problem persists.

Suggested fix that didn't work:
1. In calendar.google.com, Unsubscribe from the IPFS Community calendar
2. In Apple Calendar, refresh your feeds, watch the calendar disappear
3. In calendar.google.com, Re-subscribe to the IPFS Community calendar

_This doesn't work. Sometimes it makes the bad event go away for a few minutes, but then it comes back._

Please leave this issue open until at least 2 people who use Apple Calendar confirm that it's fixed.

cc @mikeal @daviddias @momack2

**Comment by mikeal** [comment]
This is really bad, it's making the calendar totally unusable.

<img width="1096" alt="screen shot 2018-11-19 at 11 31 45 am" src="https://user-images.githubusercontent.com/579/48730304-cbe00480-ebee-11e8-9aed-5bf0843e8d0b.png">

**Comment by momack2** [comment]
I just imported the calendar from https://calendar.google.com/calendar/ical/ipfs.io_eal36ugu5e75s207gfjcu0ae84%40group.calendar.google.com/public/basic.ics and I don't see this recurring event. Can you add more context about how you have linked ical to gcal and if any of the debugging options listed [here](https://productforums.google.com/forum/#!topic/calendar/YjeHy8gk0JE), [here](https://productforums.google.com/forum/#!topic/calendar/o8m_8RCnzNo;context-place=topicsearchin/calendar/ical$20sync$20deleted$20event), and [here](https://productforums.google.com/forum/#!topic/calendar/F0rJ4OciszY;context-place=topicsearchin/calendar/ical$20sync$20deleted$20event) worked for you? 

Based on the fact it doesn't show up on clean installs, I'd expect that deleting or declining the recurring event should remove the block and make the calendar usable again.

**Comment by mikeal** [comment]
@momack2 are you using iCal?

**Comment by momack2** [comment]
Yep. Hadn't before (this was my first import), but I imported it into ical and get a completely normal looking cal:
![screen shot 2018-11-19 at 2 04 34 pm](https://user-images.githubusercontent.com/618519/48737882-1455ed00-ec04-11e8-9148-c2cb1abfe832.png)

**Comment by mikeal** [comment]
So strange, I was seeing it on every subscribe, using either the in account subscription or the iCal feed.

BTW, I deleted the offending event and it seemed to fix it, and I'm still seeing a correct "IPFS Project WG Weekly Sync Up" for tomorrow.
