### ISSUE TITLE
Seattle IPFS Meetup - July

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#37]
We've been talking about the idea of making a IPFS meetup (or meetups) while a big part of the team is here. It is time to organize the troops and make it happen!  :)

Date - Thursday, July 23th 
Fodd - Thai Catering - http://www.kaosamai.com/
Lineup:
  - Juan - IPFS
  - Jeromy - The guts of IPFS (lots of Code) (+ cool demos)
  - Trevor - Docker & IPFS
  - Krl IPFS apps
  - Next 
  - Come hack with us (IPFS Seattle Hack Day)

**Comment by whyrusleeping** [comment]
also demos!

**Comment by whyrusleeping** [comment]
for food we could get taco del mar to cater, i've had them cater all the hackathons i ran back at school, and it was good stuff.

**Comment by wking** [comment]
On Wed, Jul 08, 2015 at 11:04:06AM -0700, David Dias wrote:
>  - [ ] Date

I am agnostic on venues and food, but would prefer the 22nd–24th or
29th–31st.  I could probably swing the Sundays (19th and 26th) if we
need a non-weekday time.  Mondays and Tuesdays are hard, and Saturdays
it's just me and the baby ;).

**Comment by jbenet** [comment]
Weds and Thus are good days for meetups in general. (dont conflict with
peoples weekend plans). Maybe we can do two, next week and the following?

**Comment by whyrusleeping** [comment]
@jbenet could you contact someone at google freemont about hosting a meetup for us there?

**Comment by whyrusleeping** [comment]
I want to have the meetup on the 22nd, (next thursday)

**Comment by whyrusleeping** [comment]
food: thai catering :smile:

**Comment by wking** [comment]
On Tue, Jul 14, 2015 at 11:54:13AM -0700, Jeromy Johnson wrote:
> I want to have the meetup on the 22nd, (next thursday)

Next Thursday looks like the 23rd, and that works for me.  If we want
a follow-up meeting the week after, I'm fine with either the 29th or
30th.

**Comment by jbenet** [comment]
Ok, i'll see about a venue.

**Comment by whyrusleeping** [comment]
@wking right, 23rd is what i meant >.>

**Comment by whyrusleeping** [comment]
alright, after venue time and food is mostly figured, we need to decide on a format and content. What are we going to do at this meetup? and for how long? do we want talks? demos? presentations? or just casual hanging out and chatting?

**Comment by wking** [comment]
On Tue, Jul 14, 2015 at 01:24:14PM -0700, Jeromy Johnson wrote:
> What are we going to do at this meetup? and for how long? do we want
> talks? demos? presentations? or just casual hanging out and
> chatting?

+1 to some chatting, but we might also want to do a “cleanup open
issues / PRs” sprint.  I could go either way on talks, demos, and
presentations.

**Comment by diasdavid** [comment]
@jbenet let's book ImpactHub for the meetup and start announcing it. Feel free to add me to the thread and I can take that from now.

I'll take care of creating attending.io and broadcast it everywhere.

Everyone ok with outline? https://github.com/ipfs/community/issues/37#issue-93852749

**Comment by diasdavid** [comment]
started here: http://attending.io/events/ipfs-meetup
need:
 - [ ] confirm the outline
 - [ ] get the fancy background image from ipfs.io (only managed to find the edited version)
 - [ ] get confirmation of space
 - [ ] calling for Thai catering

**Comment by diasdavid** [comment]
@kbala would be interested in doing a demo of the stuff you've been developing with machine learning?

@wking, @krl can I get your confirmation/availability to be present and deliver a talk/demo?

**Comment by krl** [comment]
yep!

**Comment by diasdavid** [comment]
@kyledrake, I was thinking, would you like to come up to Seattle and talk about Neocities and IPFS for the meetup? :)

**Comment by kyledrake** [comment]
@diasdavid I could swing that. I would need a place to stay for the night (doesn't have to be fancy).

**Comment by diasdavid** [comment]
@kyledrake , @heems will leave us Thursday at 5pm, so you can definitely take the extra bed :)

**Comment by diasdavid** [comment]
This was successfully done :)
