### ISSUE TITLE
/blob/master/contributing.md 404

### ISSUE THREAD

**Issue by NukeManDan** [ipfs/community#373]
[`https://github.com/ipfs/community/blob/master/contributing.md`](https://github.com/ipfs/community/blob/master/contributing.md)

gives a 404... linked in many `https://github.com/ipfs-shipyard/...README.md` docs, like : https://github.com/ipfs-shipyard/ipfs-desktop through a gif like this:

![image](https://user-images.githubusercontent.com/35669742/49277181-f70ff280-f43d-11e8-8cda-828d4e3437ea.png)

**Comment by marten-seemann** [comment]
I already fixed that in a few libp2p repos, but there's a lot more work to do...

**Comment by NukeManDan** [comment]
is there a way to let the org (https://github.com/ipfs-shipyard/ ) owners know to start patching this up?

**Comment by NukeManDan** [comment]
@alanshaw @daviddias @fsdiogo @hacdias @lgierth @marcooliveira @olizilla @satazor @travisperson @vasco-santos @victorb  

hate to ping you for something minor, but a lot of repos need a tiny fix :point_up: 
~https://github.com/ipfs/community/blob/master/contributing.md~ => https://github.com/ipfs/community/blob/master/CONTRIBUTING.md

**Comment by fsdiogo** [comment]
Thanks for the heads up @NukeManDan, I'll go through the main repos in Shipyard and fix that!

**Comment by vasco-santos** [comment]
I have some repos with that url outdated, thanks @NukeManDan 

Regarding some `libp2p` modules, @mgoelzer we are using the contribute gif of `IPFS` in several ones, such as [libp2p/js-libp2p-connection-manager](https://github.com/libp2p/js-libp2p-connection-manager). We do not have a `libp2p` gif. Should we ask for one and point to [libp2p/community/CONTRIBUTE.md](https://github.com/libp2p/community/blob/master/CONTRIBUTE.md)?

**Comment by mgoelzer** [comment]
@vasco-santos Yes, thanks for raising it.  For all libp2p repos, we should be at a minimum be deleting the "Contribute to IPFS" image now, and ideally we should get our own libp2p image.

For the time being, I've just been inserting these in libp2p repos as I come across them (the suggestion of @daviddias):

```
[![](https://img.shields.io/badge/project-libp2p-yellow.svg?style=flat-square)](http://libp2p.io/)
[![](https://img.shields.io/badge/pm-waffle-yellow.svg?style=flat-square)](http://github.com/libp2p/libp2p)
[![](https://img.shields.io/badge/freenode-%23libp2p-yellow.svg?style=flat-square)](http://webchat.freenode.net/?channels=%23libp2p)
```

You can see an example of them at the top of [go-libp2p-crypto/README.md](https://github.com/libp2p/go-libp2p-crypto/blob/master/README.md) which were added by PR [#52](https://github.com/libp2p/go-libp2p-crypto/pull/52).
