### ISSUE TITLE
IPFS Community WG Q1 2019 OKR's

### ISSUE THREAD

**Issue by mikeal** [ipfs/community#376]
It's OKR time!

Let's talk about what we can accomplish in Q1 of 2019.

For reference, these are the milestone's already in our [Roadmap](https://github.com/ipfs/community/blob/master/ROADMAP.md).

* ProtoSchool
  * Milestone #2 (Q1 2019): Public Launch
  * Milestone #3 (Q1 2019): ProtoSchool Roadmap
* Automated Workflow Enhancements
  * Milestone #1 (Q1 2019): Review existing Probot and GitHub Actions

**Comment by mikeal** [comment]
In Q1 2019 I want to re-write the README in this repository, it is wildly out of date :)

**Comment by mikeal** [comment]
In Q1 we should also instrument custom analytics using [GA events](https://developers.google.com/analytics/devguides/collection/analyticsjs/events). We should identify a few things to track and instrument them now and in the future we can add more data points, the important thing is to figure out how we want to instrument them to enable better iteration in the future.

**Comment by mikeal** [comment]
So, we need to get a handle on the "Entry Points" by which the community discovers IPFS.

We have a plan to build two new entry points: ProtoSchool and "The Publication." However, we haven't really cataloged the existing entry points we are hosting. There are many websites and documentation sites we haven't really cataloged or thought about in a holistic way.

We're also being asked to take on the maintenance of some of these resources https://github.com/ipfs/awesome-ipfs/issues/66#issuecomment-445657477 which could be a tremendous burden if these sites only continue to increase in numbers without a clear understanding of the audience each one is targeted at, how effective it currently is, and where it ranks against the other priorities we have across all the entry points for our community.

At the very least, in Q1 I want to get a taxonomy of all the entry points we currently have and get access to metrics on all the ones where metrics are available.

**Comment by mikeal** [comment]
Some more entry points to consider https://github.com/ipfs/community/issues/369

**Comment by daviddias** [comment]
Hi Community WG! Mind creating a PR to just like https://github.com/ipfs/team-mgmt/pull/794 or https://github.com/ipfs/team-mgmt/pull/793 and point to this discussion so that all the Working Groups can find your OKR Planning?

**Comment by pkafei** [comment]
Just to clarify for Q1 2019 I will be:

1. Working on the site taxonomy which falls under [Document Improvement](https://github.com/ipfs/community/blob/master/ROADMAP.md#documentation-improvements). Creating a logical site taxonomy that will help new users and contributors learn and grasp the high level concepts of IPFS. @mikeal do you have any examples of open source projects that has well organized docs and tutorials? 

2. Tackling automated workflow enhancements https://github.com/ipfs/community/issues/369.

**Comment by mikeal** [comment]
> Creating a logical site taxonomy that will help new users and contributors learn and grasp the high level concepts of IPFS.

I think the taxonomy will be most useful to *us* :) We don't yet have a good grasp of all of these resources :)

> @mikeal do you have any examples of open source projects that has well organized docs and tutorials?

Yes, but I'm trying to find some that have a similar level of new concepts they are trying to convey like we do. I'll try to pop back into this thread with some in a few days after I've given it more thought.

**Comment by mikeal** [comment]
@pkafei a few more things I'd add.

* Improvements to the new developer experience in `js-ipfs`. (stuff like the ready state change https://github.com/ipfs/js-ipfs/issues/1762)
* Improvements to the new contributors experience. Automation is part of it, and captured by your other point, but we also may want to split the contributing documentation into a doc for committers and a doc for first time contributors that is more minimal.

**Comment by mikeal** [comment]
@terichadbourne following up from our conversation earlier, you'll be tackling:

* Simple file sharing in IPFS, ProtoSchool tutorial. (I'll work on the plumbing for this)
* Launch "The Publication"

**Comment by daviddias** [comment]
@terichadbourne given that the common interface is the [spreadsheet](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=1876434856), can you make sure that who uses that entry point can find where you have the OKRs for the round?

**Comment by terichadbourne** [comment]
@daviddias I just added the link to the [spreadsheet](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=1876434856) and updated the headlines in the spreadsheet to match those in our OKRs. If that's not what you had in mind, let's circle back with @mikeal when he's back to make sure everyone's on the same page.

**Comment by daviddias** [comment]
It's exactly what I had in mind, but better given that you also added a preview by listing the objectives :) Thank you!
