### ISSUE TITLE
⚙️ FOSDEM 2019 🎊

### ISSUE THREAD

**Issue by daviddias** [ipfs/community#378]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1211152/49957794-cf6e5f00-ff00-11e8-821b-acc6ce13a56f.png">

After the much fun from FOSDEM adventures in [2018](https://github.com/ipfs/community/issues/271), [2017](https://github.com/ipfs/community/issues/194) and [2016](https://github.com/ipfs/community/issues/88), a bunch of us intend to go there again!

Who is planning to go? Shall we do another IPFS Meetup while there?

**Comment by fabiosantoscode** [comment]
I'm in!

**Comment by gpestana** [comment]
Going and 💯 thumbs up for an IPFS meetup!

**Comment by pgte** [comment]
I'm going!

**Comment by pkafei** [comment]
I'll be there

**Comment by chriscool** [comment]
Going and going to the [Git Merge](git-merge.com) too.

**Comment by tdantas** [comment]
I'm going

**Comment by terichadbourne** [comment]
I'll be there and am hoping to attend Git Merge as well.

**Comment by mikeal** [comment]
FOMO!

**Comment by joaosantos15** [comment]
I'm going too!

**Comment by daviddias** [comment]
Sharing an update here with you all! A bunch of the IPFS Core Devs and Working Groups contributors will be attending FOSDEM (17 to be exact) and we would love to make sure to meet with the broad IPFS Community while we are there!

I'll try to keep this issue updated with the whereabouts and gathering plans.

### Meanwhile, what are the sessions you are most excited about for FOSDEM 2019??? Share it with us!

I'm so excited!!! ✨ 🤩 ⚡️

**Comment by r0kk3rz** [comment]
I'll be there, it would be great to meet up with you guys!

**Comment by mib-kd743naq** [comment]
> I'll try to keep this issue updated with the whereabouts and gathering plans.

@daviddias sooooo it's day 1 of FOSDEM 2019. How is that update coming? :stuck_out_tongue:
