### ISSUE TITLE
Trip to Portlandia!

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#38]
So, we are (finally!) putting on the schedule some dates for our {Mesh, Hack}/{RoadTrip, Train} to Portlandia, OR :)

We have two options currently and would love to know how would it work best for you, options are
- Sun 19th to Tue 21th or Wed 22th
- Sun 26th to Tue 28th

How does these dates sound, @kyledrake [btw](http://assets3.thrillist.com/v1/image/882396/size/tl-horizontal_main/10-reasons-portland-trumps-seattle), @maxogden, @bcomnes @caseorganic ?

####  Monday

  - 7:25am - 11:05am - Seattle -> Portland on the Mesh Train (501 Amtrak Cascades)
  - Meet with Kyle
  - Probably work from CTRLH?

#### Tuesday

  - Start hacking early at CTRLH
  - Consider going to the [Kubernetes launch](https://www.eventbrite.com/e/kubernetes-10-launch-after-hours-party-tickets-16980424908)
  - Meet up [Puppet Labs OSCON 2015 "Open" House](https://www.eventbrite.com/e/puppet-labs-oscon-2015-open-house-tickets-17371853682), promotional code is `Attendee`

#### Wednesday

  - Juan gets the train back to Portland
  - Spend the day working with Amber and Kyle
  - [IPFS meetup at CTRLH](http://attending.io/events/ipfs-portland-meetup-the-permanent-web)

#### Thursday

  - 8:20am - 12:00pm - Portland -> Seattle Mesh Train (500 Amtrak Cascades)
  - [IPFS meetup at Seattle's Impact Hub](http://attending.io/events/ipfs-seattle-july-2015)

**Comment by kyledrake** [comment]
The 19th to the 22nd are during OSCON, so there's a bunch of tech people in town during that block. Probably your best days for networking.

Both date ranges work fine for me!

**Comment by kyledrake** [comment]
I'll probably be at this on Tuesday https://www.eventbrite.com/e/kubernetes-10-launch-after-hours-party-tickets-16980424908

**Comment by maxogden** [comment]
I'm hosting a JS BBQ on the 23rd: https://ti.to/maxogden/jsbbq-pdx-2

On Friday, July 17, 2015, Kyle Drake <notifications@github.com> wrote:

> I'll probably be at this on Tuesday
> https://www.eventbrite.com/e/kubernetes-10-launch-after-hours-party-tickets-16980424908
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipfs/community/issues/38#issuecomment-122465519>.
>


-- 
Sent from my phone

**Comment by bcomnes** [comment]
I'm out of town 26-28, but am around the rest of the time!  Would be great to kick it while your here :)

**Comment by diasdavid** [comment]
It's happening, tomorrow we'll drive down :)

**Comment by kyledrake** [comment]
Cool, let me know when you're getting here and where you are.

**Comment by diasdavid** [comment]
@krl @jbenet @heems @mappum and me (@diasdavid) all aboard the meshtrain! 

@whyrusleeping fancy joining us?

I found this on the Amtrak website: `501 Amtrak Cascades 7:25am - 11:05am`

**Comment by kyledrake** [comment]
@diasdavid How long are you in PDX? I might be able throw an impromptu IPFS meetup here, but it needs to happen like fast (I usually need a little more advance notice).

**Comment by bcomnes** [comment]
woo! :tada: :balloon: :beers:

**Comment by jbenet** [comment]
![](http://gateway.ipfs.io/ipfs/QmQc3daooyaGEaqK8oRPG58M8cvnJtA9qQsBoKGXuWszvK/itshappening.gif)

### thanks to @diasdavid and @kyledrake for organizing all the things.

**Comment by kyledrake** [comment]
Here we go:

http://attending.io/events/ipfs-portland-meetup-the-permanent-distributed-web
http://calagator.org/events/1250468792

**Comment by kyledrake** [comment]
Distribute these links on your respective social network things :)

**Comment by kyledrake** [comment]
Other things:

Puppet Labs open house, @diasdavid is handling tix for the IPFS crew https://www.eventbrite.com/e/puppet-labs-oscon-2015-open-house-tickets-17371853682

I'm going to the Kubernetes launch, if anyone is interested feel free. Not sure how long I'll be there but I'm going to check it out: http://kuberneteslaunch.com/

**Comment by diasdavid** [comment]
@feross keeping you posted of the events schedule ^^ :) Good time to book that flight

**Comment by opn** [comment]
Hey @maxogden and @jbenet  I'm not in Portland today - but would love to see some progress getting Fedwiki running on IPFS. Will be having our weekly Hangout with Ward in a couple of hours - I'll bring it up. Good chance to meet? Would be great to get this sorted before Chaos Communication Camp in August?
