### ISSUE TITLE
Define a policy for licensing repos

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/community#386]
Over at `ipfs/docs`, I’ve created a PR to add a license. It’s just MIT to keep it simple, but we have a variety of different licensing schemes across repos (taken from [this survey of repos](https://docs.google.com/spreadsheets/d/1IDVAGfniyHCJLIxLc3y7K7YTOFGCtgwTVCZEojtNLlw/edit#gid=0)):

- MIT for most repositories
- CC-BY-SA (Attribution-ShareAlike 3.0 Unported)
  - [ipfs/logo](https://github.com/ipfs/logo)
  - [ipfs/pm](https://github.com/ipfs/pm)
- CC-BY-SA (Attribution-ShareAlike 4.0 International)
  - [ipfs/artwork](https://github.com/ipfs/artwork)
- CC-BY 3.0 US (Attribution 3.0 United States)
  - [ipfs/apps](https://github.com/ipfs/apps)
- CC0 (CC0 1.0 Universal, i.e. Public Domain)
  - [ipfs/awesome-ipfs](https://github.com/ipfs/awesome-ipfs)
  - [ipfs/reading-list](https://github.com/ipfs/reading-list)
- Combo: CC-BY-SA (Attribution-ShareAlike 3.0 Unported) for docs and MIT for code
  - [ipfs/community](https://github.com/ipfs/community)
- Combo: CC-BY (Attribution only, no Share-Alike Clause) for *output*, MIT for source
  - [ipfs/website](https://github.com/ipfs/website)

(Side note: a bunch of these use CC 3.0 licenses. CC has since released a 4.0 round of licenses, so we may want to update those. I’m not sure what the changes were, though.)

Is there a more cohesive and coherent policy we can make around licensing?

**Comment by daviddias** [comment]
Tagging @ianjdarrow to this one

**Comment by Mr0grog** [comment]
I think this was resolved in #298. Are you revisiting it, or did I just fail to close this when we added the doc?

**Comment by daviddias** [comment]
@Mr0grog, @ianjdarrow will be posting an update to the Licensing Policy soon that will simplify it dramatically for maintainers and contributors. tl;dr; it will be a double license of Apache 2 + MIT, but I defer the explanation to @ianjdarrow.

**Comment by daviddias** [comment]
The update is here -> https://github.com/ipfs/team-mgmt/issues/849

Closing this issue, let's continue in https://github.com/ipfs/team-mgmt/issues/849
