### ISSUE TITLE
Community Map 

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#39]
Can someone make a map for ipfs/community with our general locations? (i.e. city).

Bonus points if it tracks the peer.ID of a node we can individually configure via a file on github or ipfs :) 

Basically, the webui connections map, but with a given set of peer.IDs instead of the routing table.

![](http://gateway.ipfs.io/ipfs/Qmb6pBxmrpm84umrLiQVSKcp5wtz21p2D6uV3nVbMjx2DJ/cap.png)

@krl can you post here once the connections app is extracted and works?

**Comment by diasdavid** [comment]
@RichardLitt would you be interested in making this?

**Comment by RichardLitt** [comment]
@diasdavid yes, but I have some higher priorities at the moment.

**Comment by thebillmar** [comment]
Does this help?
https://goo.gl/k7ADGj
There is a lot that can be done, such as adding kml data, etc.
Let me know what's missing, etc.

**Comment by RichardLitt** [comment]
@thebillmar nice work. I'm not sure Google Maps will be extensible enough for us to work in. Maybe as a widget, but I think something that showed peers as well as meetups would be good.

**Comment by thebillmar** [comment]
I will add dynamic objects of peers (people) in our meeting next.  Its
actually one of the sample uses of IPFS that I plan to demo at our April 30
workshop.

There is a lot of functionality behind this seemingly simple MyApps UI.
For instance, dynamic objects can be added such as cell phone locations
within Google Earth moving around in a custom 3D model.  Check out the
things you can do with KML format.

I would be happy to add your peers to this map then interact with it via
some kind of widget, etc.
