### ISSUE TITLE
IPFS Denver Meetup: 2/13

### ISSUE THREAD

**Issue by NukeManDan** [ipfs/community#392]
Very excited to announce partnering with ETHDenver and Chainshot on this:

# ChainShot Collaborative Coding: Merkle Trees
![download](https://user-images.githubusercontent.com/35669742/52157027-53171300-2649-11e9-877c-465460a66eff.png)

See https://github.com/ProtoSchool/Denver/issues/8 to RSVP and join the Proto.school Denver community!

**Comment by NukeManDan** [comment]
Great content. Will update with video soon!

@Dan-Nolan, @Roots2D - you are rocks stars! 

Pics: https://photos.app.goo.gl/qEMB23w49XsH7KGK6

**Comment by Dan-Nolan** [comment]
These are great! Thanks so much, Dan!
