### ISSUE TITLE
2nd IPFS Hong Kong Meetup + Introducing Protoschool HK!

### ISSUE THREAD

**Issue by kk3wong** [ipfs/community#396]
2nd IPFS Hong Kong Meetup + Introducing Protoschool HK!
Tuesday, February 26, 2019
7:00 to 9:00 pm

Bitwork
7/F, 18 Sheung Yuet Road, Kowloon Bay · Hong Kong

https://www.meetup.com/Hong-Kong-IPFS-Meetup/events/258784575/

**Comment by NukeManDan** [comment]
Best of Luck @kk3wong ! Wishing Denver wasn't so far away. Would love to join ya! :grinning:

**Comment by kk3wong** [comment]
@NukeManDan Thanks a lot!! Wish your Denver 1st IPFS Meetup will go smooth as well! We will have chance to meet up someday definitely! :grin:
