### ISSUE TITLE
Grants for community building 

### ISSUE THREAD

**Issue by NukeManDan** [ipfs/community#398]
I would love to drive more interest in the Denver meetups for @IPFS and @protoschool

We have had a few recent big turnouts to meetups and funds to foster and accelerate growth and support the present community are needed. (see #392 #395 )

Is there a way to apply for funding for community building officially? If not, are there plans for this?

**Comment by terichadbourne** [comment]
@NukeManDan I’d like to better understand the need you see. Would you mind sharing some concrete examples of how grant funding would be spent and how this would translate into community growth?

**Comment by NukeManDan** [comment]
@terichadbourne, thanks for the reply!

There are mostly direct (and a few indirect) types of costs that would be ideal to assist in:
  - Venue fees + rental equipment ( screes, projectors, whiteboards... )
  - Food + Supplies, Transportation + delivery  
  - Marketing and promotion (flyers, ads,meetup.com fees  - and an easy to get on [IPFS pro account](https://www.meetup.com/pro/ipfs/))
  - Time and effort towards organizing, promoting, running, and producing media for and of the events

Organizers (like myself) run these events because they care, are passionate, and also get credibility/status in the community. But that only goes so far, especially when more than time is required to facilitate the events. That is why many seek official sponsors of events to help.

I think @IPFS should really consider at least a mechanism to request reimbursing direct costs of events. When all you are asking for is time, the barrier to entry for IPFS specific events goes way way down.  I suspect you will see a large increase in adoption of new groups with that mechanism in place! :grinning:

**Comment by NukeManDan** [comment]
One possible way we may get outside funds into this effort is via donations that are then used to "bounty" meetups! I know the @gitcoinco team well, and think @protoschool would be an ideal fit for a gitcoin grant! Specifically here to fund production of tutorials from the community via bounties.

https://gitcoin.co/grants/

What do you think about that @terichadbourne?
