### ISSUE TITLE
How the Internet Works

### ISSUE THREAD

**Issue by pkafei** [ipfs/community#405]
We should have a primer that discusses how the internet works so folks will better appreciate some of the protocols that we are offering alternatives for. The primer will go over core concepts like HTTP, TCP/IP, NAT, DNS. 

Not sure if this would ultimately live on the libp2p or ipfs site.

**Comment by terichadbourne** [comment]
What format do you have in mind for this @pkafei? I’m wondering whether it’s something that would make sense as a text-only tutorial on ProtoSchool that could be linked to from both sites.

**Comment by pkafei** [comment]
I think a text-only ProtoSchool tutorial is a good idea. This could start out as a quick introduction to basic network programming concepts.

**Comment by daviddias** [comment]
Check out Networks Land http://networks.land, it packs a ton of explanations, activities to do alone or as a group activity and resources for paced reading tacking different parts at different times.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1211152/57195551-583f7300-6f54-11e9-94b1-7f0202b259a6.png">

**Comment by daviddias** [comment]
Also, coursera has really great courses on Networks Architecture, Protocols and more https://www.coursera.org/browse/computer-science/computer-security-and-networks

**Comment by miyazono** [comment]
Depending on the level you want, [this SciShow series](https://www.youtube.com/watch?v=1UStbvRnwmQ&list=PLsNB4peY6C6KR6fQo_LD1C3p840waQKJR) is a good coverage in ~30 minute

**Comment by daviddias** [comment]
Another great one **https://www.coursera.org/learn/peer-to-peer-protocols-local-area-networks**

**Comment by terichadbourne** [comment]
@pkafei If you decide you do like the idea of doing this as a ProtoSchool tutorial, you can check out the  instructions for building at https://github.com/ProtoSchool/protoschool.github.io and put in a new tutorial issue to start drafting a content outline before you build. I'm happy to answer any questions!

**Comment by pkafei** [comment]
Thank you for the instructions! I won't be able to put this together this quarter, but will revisit it later on this year.
