### ISSUE TITLE
Weekly IPFS contributor office-hours

### ISSUE THREAD

**Issue by olizilla** [ipfs/community#407]
There is a lot going on in IPFS land. It can be difficult for potential new contributors to know where to start.

Let's dedicate one hour per week to an open-to-all office-hours video call, where we make ourselves available to help answer questions from the community. Are you keen to contribute to IPFS but don't know where to start? Come and ask!

If we can do it every week, and it helps a curious person make their first contribution, it's worth it. I think an ideal format would be, we annouce it on the next IPFS weekly, that two members of the core team will be available for 1 hour before the IPFS weekly, to answer all and any questions you may have about IPFS and how to contribute. We may not have all the answers, but we'd direct you to the right person or repo, and follow up later with more complex ones that we can't easily triage on the call.

We could encourage people to comment on an issue before-hand to give us a heads up. We could create an issue on this repo ipfs/community for the both the IPFS weekly call, and the office hours session before hand, like we do over on ipfs/team-mgmt to give us something we can point people at ahead of time that isn't a google calendar.

I'm happy to run the first few sessions to get the ball rolling. I'll set up the issues and annouce it on the next IPFS weekly call (2019-04-29) if folks are in favour of it. I'd sit on the call, and see who turns up. In idle moments, I'd go through recent questions on discuss.ipfs.io and SO, and announce on freenode #ipfs to ask all the things. I'd summarise the session on the issue for posterity, and the questions asked would be used to help prioritise improvements to our documentation.

**Comment by momack2** [comment]
WONDERFUL IDEA! Let's do it! Happy to also attend and meet with anyone who shows up. We should also tweet about it!

**Comment by jimpick** [comment]
I'll join in. It's a bit early here (8am), but it sounds like fun!

**Comment by Stebalien** [comment]
This event is now on the community calendar:

https://github.com/ipfs/community#community-calendar

(closing to cleanup this issue tracker a bit)
