### ISSUE TITLE
Move contributor principles to main CONTRIBUTING.md

### ISSUE THREAD

**Issue by daviddias** [ipfs/community#409]
@momack2 pointed out that the Go team has a set of principles explicitly written at https://github.com/ipfs/community/blob/master/CONTRIBUTING_GO.md#contributor-principles. I would argue that these are pretty much universal for the whole IPFS project and that it would make more sense to have it at the CONTRIBUTING.md, reserving the _JS and _GO for language specifics.

Shall I make the change?

**Comment by hsanjuan** [comment]
Yes. Per the contributing principles you should have made the change and not asked for permission! :-)
