### ISSUE TITLE
IPFS Berlin Meetup

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#41]
# IPFS Berlin Meetup

Hey Everyone, _very last minute_ we're organizing an IPFS Berlin Meetup.

It is **tonight** (Thursday 08-27) at 20:00 at [c-base](http://www.c-base.org/) ([location](https://www.google.de/maps/place/c-base/@52.5129992,13.4200814,17z/data=!3m1!4b1!4m2!3m1!1s0x47a84e3b41c73ea7:0x94a319a092a3e717)). Sorry for the short notice! But come hang out!

```
c-base @ 20:00
Rungestraße 20
10179 Berlin
```

The format will be straight forward:

- 10min - "What is IPFS" from @jbenet (hopefully can skip if most people know)
- 10min - Install IPFS + 5min basic demo @jbenet
- 40min+ - Demos! \o/

_**Post below if you would like to demo something.**_  @lgierth, @krl, and I have plenty of stuff, too. And feel free to bring any burning questions!

Cheers,
Juan

**Comment by jbenet** [comment]
cc @lgierth @krl @ehd @grncdr @leif @david415 @trentmc0 @subtly @bnvk @opn @ebuchman @ehmry 

spread the word!

**Comment by bnvk** [comment]
@jbenet cool, thanks for the invite. I'll try to head there with my visiting friends after dinner at 20:30 - 21:00 ish!

**Comment by ec1oud** [comment]
I'm a Qt developer and will probably be in Berlin for https://qtcon.org/  - would you guys like to have a meetup around the same time, perhaps on Sunday evening, 4 September, or Monday?

**Comment by haywirez** [comment]
Is this still happening? Any upcoming meetups?

**Comment by VictorBjelkholm** [comment]
@haywirez haven't seen anything been planned for a while. If you're not afraid of travelling, I'm hosting meetups every now and then in Barcelona, Spain. Subscribe to https://www.meetup.com/IPFS-BCN/ for announcements regarding the next one
