### ISSUE TITLE
Amending Commits document unclear about force pushing

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#43]
I just did my first two PRs to go-ipfs, which requires a license and sign off. I ran the script, but am unsure if I really ought to be force pushing, and whether gitcop is OK with that. The [amending commits](https://github.com/ipfs/community/blob/master/docs/amending-commits.md) doc doesn't mention force pushing at all. 

Should it? I think a message saying the following would be good: "If your first PR was caught by GitCop, run the script, and force push to fix the issue. **Only do this** if your PR has not been merged yet."

**Comment by chriscool** [comment]
I agree that it would be nice for contributors if the doc mentioned force pushing.

> "If your first PR was caught by GitCop, run the script, and force push to fix the issue. Only do this if your PR has not been merged yet.

Running the script is not enough, you have to amend after that before force pushing. I will send a PR to the doc to try to improve on that. Thanks!

**Comment by jbenet** [comment]
i think this is fixed.
