### ISSUE TITLE
Create an 'IPFS Weekly Call' playlist on youtube?

### ISSUE THREAD

**Issue by achingbrain** [ipfs/community#436]
All the (community focused) weekly call videos are lumped in with the (company focused) all-hands meetings.

How about splitting them out into their own playlist?

**Comment by momack2** [comment]
I believe they do have their own playlist, the category on the channel
section is just looking for any newly added video.

**Comment by hsanjuan** [comment]
Pretty sure last time I ran a weekly IPFS call I added the recording into its own playlist. So closing as done.
