### ISSUE TITLE
ProtoSchool Taipei - Deep Dive into IPFS and Filecoin (Oct 21, 2019)

### ISSUE THREAD

**Issue by ccomeon** [ipfs/community#441]
ProtoSchool Taipei - Deep Dive into IPFS and Filecoin

Activity content:

Schedule: October 21st, 2019 19:00-22:00 (GMT+8)

Location: Syntrend Creative Park 11/F

Attending guest:
Raúl Kripalani - Technical Lead, libp2p
Jeromy Johnson - Technical Lead, Filecoin
Kevin Hoo - ProtoSchool Taipei Chapter Co-organizer
Jim Lin - ProtoSchool Taipei Chapter Co-organizer
Kevin Wong - ProtoSchool Hong Kong Chapter Organizer

Activity process:

18 : 30 - 19 : 00 Door Open & Networking
19 : 00 - 19 : 10 Intrudction of Speakers
19 : 10 - 19 : 20 Welcome to ProtoSchool Taipei － Kevin Hoo
19 : 20 - 20 : 30 Technical Deep Dive into libp2p － Raúl Kripalani
20 : 30 - 21 : 40 Development of Filecoin － Jeromy Johnson
21 : 40 - 22 : 00 Networking

Meetup Link:
https://www.meetup.com/IPFS-Taiwan/events/265679767/

**Comment by hsanjuan** [comment]
Closing as this probably happened already!
