### ISSUE TITLE
Fórum da Governação da Internet - Nov 13, 2019 Covilhã, Portugal

### ISSUE THREAD

**Issue by daviddias** [ipfs/community#444]
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/1211152/67676762-87bebd80-f982-11e9-8030-3d7daaaee3fa.png">

A few of us are planning to attend the "Oitava edição da Iniciativa Portuguesa do Fórum da Governação da Internet". 2019 is the first year that this event appeared on my radar and given all the recent work we've seen happening in portugal, it will be a good opportunity to page in on what each initiative is doing and how IPFS can contribute.

[Event Schedule](https://governacaointernet.pt/pdf/PT-IGF-programa%20completo%2018OUT.docx)

<img width="647" alt="image" src="https://user-images.githubusercontent.com/1211152/67677244-d751b900-f983-11e9-850a-5ed95af41185.png">
<img width="658" alt="image" src="https://user-images.githubusercontent.com/1211152/67677253-de78c700-f983-11e9-9177-88d579ab3880.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/1211152/67677261-e33d7b00-f983-11e9-973f-d0bb4420ad40.png">

If you are planning to attend, leave a comment on this issue :) 

So far we have:

- @daviddias 
- @hugomrdias 
- @satazor 
- @joaosantos15

I've also opened at thread at https://dd.indie.host/t/oitava-edicao-da-iniciativa-portuguesa-do-forum-da-governacao-da-internet/1041

**Comment by joaosantos15** [comment]
Here's a pdf version of the schedule (instead of he website's .docx)
[programa igf 2019.pdf](https://github.com/ipfs/community/files/3778576/programa.igf.2019.pdf)
