### ISSUE TITLE
Uploading large number of files

### ISSUE THREAD

**Issue by sohansoharab** [ipfs/community#475]
It is observed that, increase in number of files, uploading speed decreases drastically. But developers are maybe trying to improve latency for large files. 
_**But is there any optimization technique or procedure to have the normal upload speed in case of uploading large number of files recursively?**_

**Comment by jessicaschilling** [comment]
Hi @sohansoharab - suggest that you ask this question in the official forums at https://discuss.ipfs.io. This repo isn't really intended for support. Thanks!
