### ISSUE TITLE
Send stickers to hackerspaces 

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#50]
We're happy to send some IPFS stickers to hackerspaces. Just let us know what address and whom to ship them to.

**Comment by exiledsurfer** [comment]
Metalab Vienna
Rathausstraße 6, 1010 Vienna Austria
c/o The Sticker Box

**Comment by ang-st** [comment]
Tetalab
12, rue Ferdinand Lassalles
31200 Toulouse France

**Comment by RichardLitt** [comment]
One from #91:

Benton C Bainbridge
91 East 208 Street #3B
Bronx, NY 10467
USA

**Comment by twentytwoo** [comment]
May Winfrey

32 Lister Road
Scunthorpe
DN15 8AE
North Lincolnshire
England

**Comment by nikhilshekhawat** [comment]
suite 500, 2100 N Alafaya Trail, Orlando, Fl-32826

**Comment by whyrusleeping** [comment]
The @whyrusleeping sticker vault.

(aka, i'm out of stickers, you should send me some more)

**Comment by w33tmaricich** [comment]
Alexander Maricich

501 Central Ave
Glen Burnie
MD
21061 
USA

**Comment by Hexagon6** [comment]
Starship-Factory
Auf dem Wolf 13
4052 Basel
Switzerland

Greetings :)

**Comment by halseth** [comment]
Johan T. Halseth
Stemmeveien 32
5009 Bergen
Norway

**Comment by yangwao** [comment]
For hackerspace Progressbar, Bratislava, Slovakia

Matej Nemcek
Pod Zecakom 48
841 03 Bratislava
Slovakia

**Comment by EliasGabrielsson** [comment]
Elias Gabrielsson
Ulrikedalsvägen 26c 1101
22458 Lund
Sweden

**Comment by RichardLitt** [comment]
Actively working on this. Will be sending these soon, I hope.

**Comment by jmsmcfrlnd** [comment]
Would love to have some sent to my favorite local hackerspace, thank you. -james

CT Hackerspace Inc.
30 Echo Lake Road
Watertown, CT 06795

[www.cthackerspace.com](http://www.cthackerspace.com/)

**Comment by thebillmar** [comment]
For upcoming meetups with Desert Blockchain

Bill Mar
2992 N Miller Rd #220B
Scottsdale, AZ 85251
480-818-5745

**Comment by gavinmcdermott** [comment]
Gavin McDermott
899 Pine Street #802
San Francisco, CA 94108

Thanks!

**Comment by whyrusleeping** [comment]
Could everyone please update their post with "Received" upon receiving stickers (and maybe the date you received them on?)

**Comment by RichardLitt** [comment]
@whyrusleeping They're not sent yet. I've had a lot of difficulty uploading a new pattern; have some in the mail to my house, now, and hope to send to all of these next week.

**Comment by tjayrush** [comment]
Great Hill Corporation
1142 Stony Lane
Galdwyne, PA 19035 USA

**Comment by ligi** [comment]
c-base e.V.
rungestrasse 20
10179 berlin
GERMANY
c/o sticker box

**Comment by rjrotheryjr** [comment]
Richard Rothery
P.O. Box 208
Allenwood, NJ, USA 08720

**Comment by RichardLitt** [comment]
I am sending these tomorrow!

**Comment by condiosluzverde** [comment]
¡Thank You!

----
james mcfarland
james@jamesmcfarland.com
www.jamesmcfarland.com

**Comment by yangwao** [comment]
Ďakujeme! (Thank you in Slovak) :)

**Comment by RichardLitt** [comment]
Most of these have now been sent out. Sending the last batch tomorrow morning!

**Comment by rjrotheryjr** [comment]
Awesome can hardly wait. Many Thanks ;-)

**Comment by RichardLitt** [comment]
All sent!

**Comment by condiosluzverde** [comment]
Weehaw

----
james mcfarland
james@jamesmcfarland.com
www.jamesmcfarland.com

**Comment by rjrotheryjr** [comment]
Received...Many Thanks :)

**Comment by condiosluzverde** [comment]
FYI: CT HackerSpace in Watertown CT has received stickers. YEHA
Thanks Rich,
-james

--
  James McFarland
  james@jamesmcfarland.com



On Fri, Sep 2, 2016, at 09:42 AM, Richard Rothery wrote:
> Received...Many Thanks :)
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/ipfs/community/issues/50#issuecomment-244378041

**Comment by Hexagon6** [comment]
Thank you! Received many many stickers. Will make good use of it :smiley:

**Comment by yangwao** [comment]
Houston, ipfs stickers has just landed. 
https://goo.gl/photos/5ZEXq84Bj2eesaVE6
It's time to setup IPFS meetup with local earth citizens.

**Comment by RichardLitt** [comment]
Closing in favor of #175.

**Comment by heaven00** [comment]
just wondering how far do you guys deliver them ?

**Comment by RichardLitt** [comment]
@heaven00 See #175. You can order them now from Stickermule, they will get to you. :)
