### ISSUE TITLE
Signed up to support savecrypto.org

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#52]
I signed up IPFS as a project supporting https://savecrypto.org/ -- please sign and/or get your orgs to.

**Comment by jbenet** [comment]
![](http://ipfs.io/ipfs/QmeWnLPPvFaV6M3MpU88F7FGHTqSrekNBbo48KzVFd5b9W/cap.png)

**Comment by jbenet** [comment]
in good company :)

**Comment by jbenet** [comment]
I'll leave this issue op

**Comment by RichardLitt** [comment]
:+1: Fully support this!
