### ISSUE TITLE
#ipfs on freenode has been left an empty shell

### ISSUE THREAD

**Issue by crabbedhaloablution** [ipfs/community#571]
Even though there are 1000 members of #ipfs on freenode, nobody is talking in there, questions from IRC users go unanswered. Did the Matrix bridge get shut off after[this commit](https://github.com/ipfs/community/commit/15bb7abfa9bbc0a44334aaa7c1c246ff192b846b), leaving the ghosts of former users?
If #ipfs is to be Matrix-only, wouldn't it be nicer to turn off the lights when you leave?

**Comment by Stebalien** [comment]
The topic was updated reflect the move but it looks like that change didn't replicate to the IRC side. Thanks for the heads-up, I've fixed it and have posted a short announcement.
