### ISSUE TITLE
Add roles for the listed people

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/community#6]
Things like community advocate, go developer, supreme interplanetary ruler, etc... That will give anyone who reads the list a better idea of what the people listed do.
Say aye, if you also think this is a good idea.

**Comment by jbenet** [comment]
agree it would be easier for new people to get to know the community with this, but may also have the negative effect of making people feel somewhat boxed within boundaries. I tend to like organic growth where anyone can suggest things. maybe this is a threshold thing-- i.e. once the community is larger the benefit will be larger than the drawback

**Comment by dylanPowers** [comment]
I kinda agree so I'm going to go ahead and close this.
