### ISSUE TITLE
ipfs/ipfs Contribute File

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#63]
https://github.com/ipfs/ipfs/blob/master/CONTRIBUTE.md does not link to ipfs/community/contribute.md, and I think it should. 

I also think that it and https://github.com/ipfs/go-ipfs/blob/master/contribute.md have content which should be merged. So, I think I should rewrite them both to make them more project specific, and take out overlapping statements and put that into ipfs/community/contribute.md. Opening this here to see if there is consensus on this before I open PRs.

**Comment by jbenet** [comment]
Sounds good :+1:
