### ISSUE TITLE
IPFS Meetup London -- starts tonight at 5:30pm

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#68]
Hey everyone -- @jamescarlyle and I organized a meetup tonight, after the [Ethereum Devcon1](http://devcon.ethereum.org). 

### (Inaugural) IPFS London Meetup 

- **Time:** Nov 10 at 5:30pm
- **Location:** The Grocer at 3 Crispin Pl (Spitalfields market)

![](https://ipfs.io/ipfs/QmcrVLgQaTc9sNQBrK5bHpMiyPpJqCy6ubrH6Hv4yxPo5C/the-map-to-ipfs-london-meetup.png)

**Comment by RichardLitt** [comment]
Nice! Added to the calendar, although it is now... :)

**Comment by jbenet** [comment]
Thanks everyone for coming! Great success!

![](https://pbs.twimg.com/media/CTeOCMiWcAARr-m.jpg:large)

**Comment by bcomnes** [comment]
Wow looks fun :)

**Comment by RichardLitt** [comment]
Woo! I'm glad this was good.
