### ISSUE TITLE
Setup IPFS Implementer's Sync

### ISSUE THREAD

**Issue by BigLep** [ipfs/community#753]
https://discord.com/channels/806902334369824788/942673321852563456/956661219765395556

**Comment by BigLep** [comment]
2022-04-05 conversation: remaining items:
1. get the event on IPFS community calendar
2. create notes document in IPFS public notion

**Comment by BigLep** [comment]
https://www.notion.so/pl-strflt/IPFS-Implementors-Sync-66bc757298674c1bac6885ecec1b3085

**Comment by BigLep** [comment]
@aschmahmann : any luck on getting access to the IPFS Community calendar so can this there?

**Comment by BigLep** [comment]
2022-05-03 note: we'll resolve this when adjusted and put it as a recurring event on the calendar.

**Comment by aschmahmann** [comment]
It's now a recurring event on the community calendar with multiple hosts for the zoom call.
