### ISSUE TITLE
Malicious user easy can change website content manipulate files

### ISSUE THREAD

**Issue by mx5kevin** [ipfs/community#764]
When one user seeding a file or another content and stop seeding another user easy way change the files. Example HTML files with files. There is no protection to the site admin protect his website like a private key. Anyone can replace the original files. The security are extremely poor. I can't find an option to restore the original URL the site, or a trusted way to modify the files only by the owner. A child can hack the files, system security is a disaster. The user does not even know from the content downloaded the original owner or downloading a malicious modified content. From another computer if the original content owner is offline files can be changed without any problems. And other users download these manipulated files.

**Comment by reidlw** [comment]
Please see "Content Addressing" - https://docs.ipfs.tech/concepts/what-is-ipfs/#content-addressing - which is how IPFS addresses the issues you are raising.
