### ISSUE TITLE
IPFS needs a way to combat content abuse 

### ISSUE THREAD

**Issue by ossimantylahti** [ipfs/community#769]
Recently in my e-mail inbox there is an flow of phish sites hosted on ipfs.io addresses. For example:

![image](https://user-images.githubusercontent.com/37711285/201181643-1ea3eb94-b036-4ea7-a669-729ab35f98b4.png)

This leads to a site hosted at ipfs.io like this:

![image](https://user-images.githubusercontent.com/37711285/201181345-93c888fe-74c2-41f9-9855-be799f7f9526.png)

Due to the nature there does not seem any way of intelligently reporting and taking down these kind of blatant phishing and abusive ipfs.io sites. As the technology becomes more common, there **will** be more abusive uses. 

IPFS.io needs a way to combat this kind of content abuse. It is better to think this before someone starts hosting kiddie porn and the community finds itself in the front page of New York Times.

IPFS already has a Code of Conduct (https://github.com/ipfs/community/blob/master/code-of-conduct.md). But the process is apparently manual and does not really take spam in account. A way of freezing malicious content should be implemented.

**Comment by achingbrain** [comment]
Please see https://github.com/ipfs/community/blob/master/SECURITY.md#reporting-abuse
