### ISSUE TITLE
Redundant project-directory.md + contributors (suggest merge)

### ISSUE THREAD

**Issue by mekarpeles** [ipfs/community#77]
Proposing moving information about developer tools from ipfs/ipfs/project-directory.md to ipfs/community

**Comment by RichardLitt** [comment]
Can you explain this a bit better?

**Comment by mekarpeles** [comment]
@RichardLitt `ipfs/project-directory.md` is being merged into `ipfs/ipfs/README.md`.  A good portion of `project-directory.md` contains community information which belongs in `ipfs/community/contributing.md` -- see PR https://github.com/ipfs/community/issues/78

**Comment by RichardLitt** [comment]
@mekarpeles Was this only discussed in https://github.com/ipfs/ipfs/pull/125?

**Comment by RichardLitt** [comment]
I ask because it's not clear to me what the reasoning would be for moving information out of project-directory, or for splitting it into multiple repositories.

**Comment by mekarpeles** [comment]
Eliminating project-directory.md? Or in eliminating project-directory.md, moving content into their respective repositories? See also https://github.com/ipfs/specs/pull/45 (ipfs/project-directory.md -> ipfs/specs). The direction was informed by ipfs/ipfs#125 however, you can follow the comments on https://github.com/ipfs/ipfs/pull/126

**Comment by mekarpeles** [comment]
Let's centralize the conversation on https://github.com/ipfs/ipfs/pull/125

**Comment by RichardLitt** [comment]
Cool. 

Aside: I am really confused by the process of making an issue as a stub, making a PR, and pointing the PR to the stub as a justification for the PR. That seems circular. An issue doesn't need to be created to make a PR, and the PR should, in the commit log, justify why it itself exists; ie, point to past conversations, and so on. Any new viewer should be able to see why a PR exists just by looking at it itself, even if it does refer to an older issue.

**Comment by mekarpeles** [comment]
@RichardLitt I don't have a good reason for that. I have a habit of labeling branches with a prefix of issue numbers so I can revisit their origins and engage in conversation prior to PR. Happy to use an alternate method the team prefers.

**Comment by RichardLitt** [comment]
Opening an issue is totally cool, if you're going to be naming your PR after it. But it's really helpful to have the logic behind the PR somewhere - just having a stub doesn't help people (like me, earlier) understand why you're doing something.

**Comment by jbenet** [comment]
this was resolved elsewhere-- thanks again everyone
