### ISSUE TITLE
Fishing using ifps one more case...

### ISSUE THREAD

**Issue by DavidLep0le** [ipfs/community#773]
Hello, 
i paste the link receive this day:
[https://gateway.ipfs.io/ipfs/QmQ9stUqowWyFgb3NTPdDpApsHkCjgYWttHEphqn1mWcF4#lep0le@tntb.net](url)
and a screen capture: 
![Capture du 2023-03-14 16-50-18](https://user-images.githubusercontent.com/74555046/225058844-ff9771bc-e86c-4278-b4ab-b2bbeba41904.png)
and a screen capture of the mail  involved in this tentative :+1: 
![Capture du 2023-03-14 16-52-20](https://user-images.githubusercontent.com/74555046/225059592-cf6c08ac-74ff-4c1c-b4e8-adcb0d42413e.png)

Please make something to secure use of your software...

**Comment by darkwiz666** [comment]
Does this even having anything to do with the core development of IPFS? 😒

**Comment by DavidLep0le** [comment]
If your software allow to make bad things , YES it's an issue for you...

**Comment by darkwiz666** [comment]
> If your software allow to make bad things

So basically everything on the internet. This boils down to you being mad you got phised and your email used to spam...may as well complain about HTML or any other webhost having clone pages too, and you complained on their dev page instead of flagging the page in the application, thinking something would be done about it...

**Comment by DavidLep0le** [comment]
First i'm not complaining on everythings. Just i notice your software is used to make attempts of phishing. 
After i'm not trying to make you trouble. Just when you develop something, you need to anticipate bad uses. If not there's a problemif ethic and of efficency. I try to undersand what is ipfs... And it seems to be an alternative infrastructure  to the web. Sale goals, same issues, each system need regulation. And in my mind it's in the core project...

**Comment by achingbrain** [comment]
Please see: https://github.com/ipfs/community/blob/master/SECURITY.md#reporting-abuse
