### ISSUE TITLE
Copyright stuff

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#79]
At some point we lost the discussion on copyright and how the DCO works. how it works in a commit is there, but the large discussion we grabbed from Docker's contribute.md is gone. we should add it back so people can understand what it means legally.

**Comment by RichardLitt** [comment]
I'm not sure I can remember the older discussion, might have been moved before I got here. I can search for it, though? Do you know what files it was in?

**Comment by jbenet** [comment]
Contribute.md i think-- if not look at Docker's, wherever they explain their use of DCO? not sure if i wrote it or took it from theirs.

**Comment by RichardLitt** [comment]
Do you mean https://github.com/ipfs/community/pull/31?

**Comment by jbenet** [comment]
i think we covered it already? i recall writing something about DCO recently in a PR with you

**Comment by RichardLitt** [comment]
Closed in https://github.com/ipfs/community/pull/83.
