### ISSUE TITLE
IRC Channel - Bots are down

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/community#80]
The history stopped being logged to botbot.me last night and `.tell` and `!pin` do not work anymore

**Comment by Dignifiedquire** [comment]
cc @jbenet @lgierth @diasdavid

**Comment by diasdavid** [comment]
freenode was under DDOS https://twitter.com/search?q=%23freenode

**Comment by Dignifiedquire** [comment]
That's why we need something like https://github.com/haadcode/anonymous-networks instead of irc :)

**Comment by Dignifiedquire** [comment]
Everything is back even botbot.me history :)
