### ISSUE TITLE
FOSDEM 2016, 30 & 31 January 2016 Brussels

### ISSUE THREAD

**Issue by chriscool** [ipfs/community#88]
I will probably go to the [FOSDEM 2016](https://fosdem.org/2016/).
If others are planning to go, it would be nice if we could organize something there.

**Comment by diasdavid** [comment]
I'm probably going to, last year was a blast! And it is the only conference I know with a dedicated RF track :)

**Comment by sleep-walker** [comment]
Hm, I expected some IPFS related talk and found nothing...

**Comment by chriscool** [comment]
You could have contacted me as I was there and we could have talked about it.

**Comment by sleep-walker** [comment]
The thing is that it could bring more attention to this project. If I have question I can always ask on IRC...

**Comment by RichardLitt** [comment]
Yeah. Would have liked to have been there and submitted something, but most of us were tired after ArcticJS. Next year, maybe! 

@chriscool, hope you had fun.

**Comment by chriscool** [comment]
Yeah, it was really nice! I bumped into many people I know, and there were some interesting talks!

**Comment by diasdavid** [comment]
Hi everyone that subscribed to this issue, are you planning on going to FOSDEM in 2018? Follow up on the new issue https://github.com/ipfs/community/issues/271
