### ISSUE TITLE
need a FAQ

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/community#9]

**Comment by dylanPowers** [comment]
With content like https://github.com/ipfs/ipfs#faq? Any specific questions to answer come to mind?

**Comment by jbenet** [comment]
i think there's a lot of questions that come up on irc. when questions come up on irc or in email that are good faq candidates, let's add them to an issue here.

Ideally, i think we should use a repo, like `ipfs/faq` as the source of FAQs. then, we can use the github API to extract the questions + first post body (as the answer), and generate a FAQ page. I think this leverages a great conversation platform (github) + having a nice page in http://ipfs.io/docs/faq that can be linked to + consumed.

**Comment by dylanPowers** [comment]
We have https://github.com/ipfs/faq so I'd call this closed
