### ISSUE TITLE
@jbenet will be offline for a couple weeks

### ISSUE THREAD

**Issue by jbenet** [ipfs/community#90]
Hey everyone, I've told a few people about this, but now more broadly:

### I'll be traveling with family from 12/18 - 1/5 

(going to New Zealand!) I will have sporadic internet access, but will only be attending to very pressing things-- hotfixes, emerging issues, and so on. If I don't get to your PRs, comments, messages, or email, please be patient. Occasionally, I may address longer discussions and some CR, but it would be very high latency.

If you need to reach me urgently, [email me](mailto:juan@ipfs.io) and tag the subject with `URGENT: `, like so:

```
Subject: URGENT: everything exploded!
```

Thanks! See you soon :)

### On go-ipfs

`go-ipfs` is the most important repo I maintain. Things should wait for my CR before merge, _except for_ the following (CRed by several people pls):

- bugfixes that bring master back to green
- more tests
- things for merging 0.4.0

### On merging 0.4.0

The big thing coming up is merging dev0.4.0 into master. If happens before I return, I can make time to CR this, as it is very important. (most of it is CRed already, so shouldn't be a big thing).

- [ ] any last things @whyrusleeping wants to merge
- [ ] require ipfs-update to be working reliably 
  - [ ] that means fully tested!
- [ ] require fs-repo-migration to be working reliably
  - [ ] that means fully tested!
- [ ] require resolution to the "upgrade path" problem:
  - [ ] things should not "stop working" for users
  - [ ] links should not be broken (eg https://ipfs.io links)
  - [ ] ideally as many people upgrade to 0.4.0 as we can
  - [ ] discuss with various people with stake on this
  - [ ] I think the https://ipfs.io gateway should resolve content on both networks
  - [ ] Maybe we should enable the new handshake as _another_ swarm addr for now, and overtime (by `0.4.x` or `0.5.x`) remove it with a migration. (i.e. people with `0.4.x` could run both protocols for now)

**Comment by diasdavid** [comment]
Enjoy the Holidays and New Zealand, I've heard it is extraordinarily beautiful! :)

**Comment by harlantwood** [comment]
Visit the fjords at the bottom of the south island if you can, preferably by kayak!  

![](http://youonlyliveonce.com.au/wp-content/uploads/2014/11/Screen-Shot-2014-11-28-at-4.51.23-pm.jpg)

**Comment by RichardLitt** [comment]
Have a ton of fun, Juan. :)
