### ISSUE TITLE
Change freejs button back to freenode on all repos

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#93]
This was a mistaken change. Opening this issue as a reference.

**Comment by RichardLitt** [comment]
I think that's all of them. Sorry about the carpetbombing, this needed to be done.

**Comment by RichardLitt** [comment]
Forgot about @diasdavid's repos. Oh man. I think that is it, now.

**Comment by diasdavid** [comment]
Thank you :):):)

**Comment by RichardLitt** [comment]
No problem. :)

**Comment by RichardLitt** [comment]
Reopen if anyone finds any more.
