### ISSUE TITLE
up-for-grabs label

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/community#94]
We should make it easier to identify low hanging fruit. Currently, we have the 'difficulty:easy' label, and 'help-wanted'. I think we should highlight these somewhere. At the least, we should link to [this search](https://github.com/search?utf8=%E2%9C%93&q=label%3A%22difficulty%3A+easy%22+user%3AIPFS&type=Issues&ref=searchresults) across our repos for these labels. 

We should also think about merging these into one label, or highlighting one of the to add to [up-for-grabs.net](http://up-for-grabs.net/#/). I think that would be awesome. Don't you?

**Comment by jbenet** [comment]
+1 for adding to up-for-grabs. that's what "Help Wanted" means.

**Comment by Dignifiedquire** [comment]
I'm -1 for merging, as eg in the webui there are tasks that I would like help with but they are more difficult on some level. So it's great I can assign help wanted and a level. 
I like the idea of having a place where this search is linked to though.

**Comment by RichardLitt** [comment]
If you assign `help wanted`, you should assign a `difficulty` too, to make it easier. That should alleviate the concerns you raise, @Dignifiedquire, right?

**Comment by Dignifiedquire** [comment]
@RichardLitt yes sounds good to me

**Comment by RichardLitt** [comment]
Ok: I am going to add "needs review", "difficulty:*", and "help wanted" to every IPFS repo. i'll make sure they all have the same color. 

Repos to add to: 

ipfs/ipfs
ipfs/js-ipfs
ipfs/website
ipfs/go-ipfs
ipfs/js-ipfs-api
ipfs/ipfs-hubot
ipfs/webui
ipfs/starlog
ipfs/examples
ipfs/logo
ipfs/astralboot
ipfs/specs
ipfs/container-demos
ipfs/infrastructure
ipfs/community
ipfs/pm
ipfs/papers
ipfs/faq
ipfs/fs-repo-migrations
ipfs/npm-go-ipfs
ipfs/py-ipfs
ipfs/notes
ipfs/blockchain-data
ipfs/http-api-spec
ipfs/js-ipfsd-ctl
ipfs/ipfs-geoip
ipfs/blog
ipfs/archive-format
ipfs/go-ipfs-api
ipfs/station

How does this sound to everyone?

**Comment by Dignifiedquire** [comment]
Thanks but please make sure if they exist they are kept so I don't have to relabel everything

**Comment by RichardLitt** [comment]
Good call.

**Comment by RichardLitt** [comment]
Tested: my script works fine. I am using https://www.npmjs.com/package/github-labels, and I will create a config file in this repo with the labels we'll standardize across repos.

**Comment by Dignifiedquire** [comment]
schweet :smile_cat:

**Comment by jbenet** [comment]
:+1:

**Comment by RichardLitt** [comment]
Done.

**Comment by RichardLitt** [comment]
This has been reopened because I need to re-add them to some issues, or find a way of doing that automatically.

**Comment by RichardLitt** [comment]
Opened bug issue here: https://github.com/popomore/github-labels/issues/17

**Comment by RichardLitt** [comment]
Add to:
 - [ ] ipfs/glossary
 - [ ] ipfs/go-libp2p-loggables
 - [ ] ipfs/go-libp2p-crypto

**Comment by diasdavid** [comment]
Wasn't familiar with http://up-for-grabs.net/#/tags/JavaScript, pretty cool!

**Comment by RichardLitt** [comment]
Just checked; there are 301 issues in IPFS on up-for-grabs. Directed someone to it today. \o/
