### ISSUE TITLE
Speaker needed for a talk in Strasbourg (France) in March

### ISSUE THREAD

**Issue by alexAubin** [ipfs/community#98]
Hi,

we are a small hackerspace in Strasbourg (France) and are planning a conference in March 4th to present to the general public some technologies/projects/initiatives regarding the future of the Internet, and in particular decentralized/distributed technologies. (See the website of [our project](https://avenirsdinter.net/))

Therefore we would be glad to have a (french) speaker come talk about IPFS :).

The talk would be about 20-30 min long, oriented towards explaining how IPFS works for the general public, and why it matters. There would be about 3 others talks, foreseen to be related to self-hosting technologies (such as La Brique Internet, Yunohost), associative ISP (c.f. FFDN) and decentralized social networks (e.g. Movim)

We offer to pay the transport fees, + around 200€ for the talk.

**Comment by chriscool** [comment]
Maybe I could do it. I am French living near Paris and I work part time on IPFS.

**Comment by chriscool** [comment]
Closing this as the March 4 event is over anyway.
